### ISSUE TITLE
[v0.11.0]Migration Error

### ISSUE THREAD

**Issue by toyama0919** [getredash/redash#1165]
Migration error occurred.

### 0023_add_notification_destination.py
https://github.com/getredash/redash/blob/master/migrations/0023_add_notification_destination.py#L30

insert notification_destination user_id is hard cording (user_id = 1)..

```
Apply new migrations? (make sure you have backup) [Y/n] Y
Applying 0023_add_notification_destination.py...
[stgredash01] run: sudo sudo -u redash PYTHONPATH=. bin/run python migrations/0023_add_notification_destination.py
[stgredash01] out: sudo: unable to resolve host ip-10-0-91-221
[stgredash01] out: sudo: unable to resolve host ip-10-0-91-221
[stgredash01] out: [2016-07-01 13:22:35,867][PID:22392][WARNING][redash.query_runner] GoogleSpreadsheet query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[stgredash01] out: [2016-07-01 13:22:35,933][PID:22392][WARNING][redash.query_runner] Hive query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[stgredash01] out: [2016-07-01 13:22:35,935][PID:22392][WARNING][redash.query_runner] Vertica query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[stgredash01] out: [2016-07-01 13:22:35,936][PID:22392][WARNING][redash.query_runner] TreasureData query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[stgredash01] out: [2016-07-01 13:22:35,947][PID:22392][WARNING][redash.query_runner] Microsoft SQL Server query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[stgredash01] out: [2016-07-01 13:22:36,069][PID:22392][ERROR][peewee] INSERT INTO "notification_destinations" ("org_id", "user_id", "name", "type", "options", "created_at") VALUES (%s, %s, %s, %s, %s, %s) RETURNING "id" [1, 1, u'HipChat', u'hipchat', '{"url": "https://hipchat.com/v2/room/670754/notification?auth_token=3139ccbf0e8977454df1ac47345ff1"}', datetime.datetime(2016, 7, 1, 13, 22, 36, 67469)]
[stgredash01] out: Traceback (most recent call last):
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
[stgredash01] out:     cursor.execute(sql, params or ())
[stgredash01] out: IntegrityError: insert or update on table "notification_destinations" violates foreign key constraint "notification_destinations_user_id_fkey"
[stgredash01] out: DETAIL:  Key (user_id)=(1) is not present in table "users".
[stgredash01] out:
[stgredash01] out: Traceback (most recent call last):
[stgredash01] out:   File "migrations/0023_add_notification_destination.py", line 63, in <module>
[stgredash01] out:     options=options
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4001, in create
[stgredash01] out:     inst.save(force_insert=True)
[stgredash01] out:   File "/opt/redash/redash.0.11.0.b2005/redash/models.py", line 99, in save
[stgredash01] out:     super(BaseModel, self).save(*args, **kwargs)
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4148, in save
[stgredash01] out:     pk_from_cursor = self.insert(**field_dict).execute()
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2858, in execute
[stgredash01] out:     cursor = self._execute()
[stgredash01] out:   File "/opt/redash/redash.0.11.0.b2005/redash/metrics/database.py", line 50, in metered_execute
[stgredash01] out:     result = real_execute(self, *args, **kwargs)
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
[stgredash01] out:     return self.database.execute_sql(sql, params, self.require_commit)
[stgredash01] out:   File "/opt/redash/redash.0.11.0.b2005/redash/metrics/database.py", line 22, in execute_sql
[stgredash01] out:     result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
[stgredash01] out:     self.commit()
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
[stgredash01] out:     reraise(new_type, new_type(*exc_value.args), traceback)
[stgredash01] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
[stgredash01] out:     cursor.execute(sql, params or ())
[stgredash01] out: peewee.IntegrityError: insert or update on table "notification_destinations" violates foreign key constraint "notification_destinations_user_id_fkey"
[stgredash01] out: DETAIL:  Key (user_id)=(1) is not present in table "users".
```

**Comment by arikfr** [comment]
Thanks for reporting! I overlooked it when merging. Will fix it now.
