### ISSUE TITLE
Python Data Source Based Queries throw error

### ISSUE THREAD

**Issue by kausikram** [getredash/redash#1169]
Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

Python Data Source based queries throw a NoneType Error

### Steps to Reproduce

1. Enable Python Data Sources and Create a Data Source
2. Create a simple python script to display a list
3. You will end up getting an error saying: 

Error running query: 'NoneType' object has no attribute 'annotate_query'

The Stacktrace from celery_error is as follows:
`[2016-07-05 13:02:17,300: ERROR/MainProcess] Task redash.tasks.execute_query[429418e3-d170-404d-b602-c4819ee6ef5a] raised unexpected: AttributeError("'NoneType' object has no attribute 'annotate_query'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2020/redash/tasks/base.py", line 13, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2020/redash/tasks/queries.py", line 440, in execute_query
    return QueryExecutor(self, query, data_source_id, metadata).run()
  File "/opt/redash/redash.0.12.0.b2020/redash/tasks/queries.py", line 389, in run
    annotated_query = self._annotate_query(query_runner)
  File "/opt/redash/redash.0.12.0.b2020/redash/tasks/queries.py", line 415, in _annotate_query
    if query_runner.annotate_query():
AttributeError: 'NoneType' object has no attribute 'annotate_query'
`

### Technical details:

* Redash Version: 0.12.0+b2020
* Browser/OS: Ubunutu
* How did you install Redash: GCE Image + Upgrade

**Comment by arikfr** [comment]
You can get this error message if the data source type isn't enabled. How did you enable it? Edited `.env`?

**Comment by kausikram** [comment]
That is correct. And restarted supervisord.

**Comment by kausikram** [comment]
I am sorry this was my mistake. I had'nt properly restarted my celery instances. Marking this as closed.

**Comment by Amirashaker** [comment]
how did you restart celery instances ?? @kausikram
