### ISSUE TITLE
Execute query does not end in IE11

### ISSUE THREAD

**Issue by deecay** [getredash/redash#1172]
### Issue Summary

Re:dash 0.10.1+b1836 installed with bitnami.
Browser: IE11

Executing query in query editor does not return results/errors. Launching Developper Tools from F12 solves the issue. Adding 
`var console={};console.log=function(){};`
at the header of app_layout.html didn't help.
### Steps to Reproduce
1. Execute any query in IE 11.

**Comment by arikfr** [comment]
When you open the Developer Tools, do you see any debug messages there?

**Comment by deecay** [comment]
`Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: column in table.columns track by column, Duplicate key: XXXXXXX
http://errors.angularjs.org/1.2.18/ngRepeat/dupes?p0=column%20in%20table.columns%20track%20by%20column&p1=XXXXXXX
   at Anonymous function (http://10.22.89.37/scripts/plugins.ec2c390a.js:7:4649)
   at r (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:20791)
   at c.prototype.$digest (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:21489)
   at c.prototype.$apply (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:23013)
   at l (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:2097)
   at v (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:4467)
   at w.onreadystatechange (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:5007)
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: column in table.columns track by column, Duplicate key: XXXXXXX
http://errors.angularjs.org/1.2.18/ngRepeat/dupes?p0=column%20in%20table.columns%20track%20by%20column&p1=XXXXXXX
   at Anonymous function (http://10.22.89.37/scripts/plugins.ec2c390a.js:7:4649)
   at r (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:20791)
   at c.prototype.$digest (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:21489)
   at c.prototype.$apply (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:23013)
   at l (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:2097)
   at v (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:4467)
   at w.onreadystatechange (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:5007)
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: column in table.columns track by column, Duplicate key: XXXXXXX
http://errors.angularjs.org/1.2.18/ngRepeat/dupes?p0=column%20in%20table.columns%20track%20by%20column&p1=XXXXXXX
   at Anonymous function (http://10.22.89.37/scripts/plugins.ec2c390a.js:7:4649)
   at r (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:20791)
   at c.prototype.$digest (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:21489)
   at c.prototype.$apply (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:23013)
   at l (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:2097)
   at v (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:4467)
   at w.onreadystatechange (http://10.22.89.37/scripts/plugins.ec2c390a.js:5:5007)
SNIP( ... repeated for all columns)/SNIP
HTML5 notifications are not supported.
HTML5 notifications are not supported.
`
I see Duplicate erros and 2 messages about HTML5. Main window looks like it's working fine.

**Comment by deecay** [comment]
I have found some interesting solution in [this thread](http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http).

Adding 
`if(!a.defaults.headers.get){a.defaults.headers.get={};}a.defaults.headers.get['If-Modified-Since']='Mon, 26 Jul 1997 05:00:00 GMT';a.defaults.headers.get['Cache-Control']='no-cache';a.defaults.headers.get['Pragma']='no-cache';`
to `scripts.js` solved the issue, but it breaks map visualization for Chrome ( and IE ). `plugins.js` might need to be changed to counter the above patch. Something like
`(function() {
    $.ajaxSetup({ cache: true }); 
})();`

**Comment by deecay** [comment]
Does not happen in v1.0.0-rc.1.
Closing.

**Comment by arikfr** [comment]
Thank you for the update!
