### ISSUE TITLE
SAML login route /saml/login returns status 500 Internal Server Error

### ISSUE THREAD

**Issue by jfairchild** [getredash/redash#1190]
### Issue Summary

SAML login route 500s
![image](https://cloud.githubusercontent.com/assets/1012652/16886598/2c65be7a-4aa3-11e6-812f-c5f873c278a8.png)
Version: Re:dash 0.11.0+b2016

### Steps to Reproduce

1. Setup SAML via OKTA
2. Set SAML env vars: REDASH_SAML_METADATA_URL and REDASH_SAML_CALLBACK_SERVER_NAME
2. Restart redash
3. Use the SAML login link

Behavior:
500 status error
curl:
```
HTTP/1.1 500 INTERNAL SERVER ERROR
Content-Type: text/html
Date: Fri, 15 Jul 2016 19:43:21 GMT
Server: nginx/1.4.6 (Ubuntu)
Content-Length: 291
Connection: keep-alive

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Expected Behavior: Redirect to Okta login

### Technical details:

* Redash Version:  0.11.0+b2016
* How did you install Redash: AWS AMI and fabric update script

Log:
```
[2016-07-15 19:36:09,189][PID:5072][ERROR][redash] Exception on /saml/login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.0.11.0.b2016/redash/authentication/saml_auth.py", line 105, in sp_initiated
    saml_client = get_saml_client()
  File "/opt/redash/redash.0.11.0.b2016/redash/authentication/saml_auth.py", line 67, in get_saml_client
    spConfig.load(saml_settings)
  File "/usr/local/lib/python2.7/dist-packages/saml2/config.py", line 353, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/usr/local/lib/python2.7/dist-packages/saml2/config.py", line 293, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/usr/local/lib/python2.7/dist-packages/saml2/config.py", line 396, in load_metadata
    disable_ssl_certificate_validation=disable_validation)
  File "/usr/local/lib/python2.7/dist-packages/saml2/mdstore.py", line 757, in __init__
    self.security = security_context(config)
  File "/usr/local/lib/python2.7/dist-packages/saml2/sigver.py", line 1037, in security_context
    xmlsec_binary = get_xmlsec_binary(_path)
  File "/usr/local/lib/python2.7/dist-packages/saml2/sigver.py", line 190, in get_xmlsec_binary
    raise SigverError("Can't find %s" % bin_name)
SigverError: Can't find ['xmlsec1']
[2016-07-15 19:36:09,191][PID:5072][INFO][metrics] method=GET path=/saml/login endpoint=saml_auth.sp_initiated status=500 content_type=? content_length=-1 duration=134.59 query_count=0 query_duration=0.00
```

**Comment by arikfr** [comment]
Install xmlsec1 (`apt-get install -y xmlsec1`).

**Comment by jfairchild** [comment]
That worked!

One note, I had to include the protocol (http://) in `REDASH_SAML_CALLBACK_SERVER_NAME`
I just had the hostname, which did not work.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
