### ISSUE TITLE
KeyError: 'dbName'

### ISSUE THREAD

**Issue by Leekao** [getredash/redash#1231]
Installed reDash, added a data source and called it 'staging_DB', then I added another DB and accidentally called it also 'staging_DB', then i saw "saving failed" msg, realized my mistake and changed the name to 'production_DB', got another 'saving failed', refresh the page and got internal server error, this is the trace from the log:

[2016-08-09 13:36:57,329][PID:30985][ERROR][redash] Exception on /api/data_sources [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/redash/current/redash/handlers/base.py", line 25, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/redash/current/redash/permissions.py", line 41, in decorated
    return fn(*args, **kwargs)
  File "/opt/redash/current/redash/handlers/data_sources.py", line 66, in get
    d = ds.to_dict()
  File "/opt/redash/current/redash/models.py", line 378, in to_dict
    'syntax': self.query_runner.syntax,
  File "/opt/redash/current/redash/models.py", line 454, in query_runner
    return get_query_runner(self.type, self.options)
  File "/opt/redash/current/redash/query_runner/__init__.py", line 148, in get_query_runner
    return query_runner_class(configuration)
  File "/opt/redash/current/redash/query_runner/mongodb.py", line 101, in __init__
    self.db_name = self.configuration["dbName"]
  File "/opt/redash/current/redash/utils/configuration.py", line 73, in __getitem__
    raise KeyError(item)
KeyError: 'dbName'

**Comment by Leekao** [comment]
I tried re-installing, didn't help.

**Comment by arikfr** [comment]
We keep the issue tracker for actionable (confirmed) bug reports and feature requests. Please use the _Support_ category in our [discussion forum](https://discuss.redash.io/c/support) for other questions.

When you post your question there, please add some additional information that will help understand what happened like:

1. What version of Redash do you use?
2. How did you install Redash?
3. What OS/browser?
4. What type of data source did you create?

Thanks.
