### ISSUE TITLE
Query Snippet table is not created

### ISSUE THREAD

**Issue by bwtakacy** [getredash/redash#1442]
Hi,

### Issue Summary

I found the below error messages are shown in api_error.log

```
[2016-12-02 14:50:19,405][PID:444][ERROR][redash] Exception on /api/query_snippets [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/redash/redash-v0.12.0.b2449/redash/handlers/base.py", line 25, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/redash/redash-v0.12.0.b2449/redash/handlers/query_snippets.py", line 64, in get
    return [snippet.to_dict() for snippet in models.QuerySnippet.all(org=self.current_org)]
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2689, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2682, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/opt/redash/redash-v0.12.0.b2449/redash/metrics/database.py", line 50, in metered_execute
    result = real_execute(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2371, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/redash/redash-v0.12.0.b2449/redash/metrics/database.py", line 22, in execute_sql
    result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/playhouse/postgres_ext.py", line 369, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/site-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: relation "query_snippets" does not exist
LINE 1: ...description", "t1"."user_id", "t1"."snippet" FROM "query_sni...
```

I think `bin/run ./manage.py database create_tables` forgets to create the `query_snippets` table.
Because in `redash/models.py` the target list of tables to be created, `all_models` does not have `QuerySnippet` class.

```
all_models = (Organization, Group, DataSource, DataSourceGroup, User, QueryResult, Query, Alert, Dashboard, Visualization, Widget, Event, NotificationDestination, AlertSubscription, ApiKey, AccessPermission, Change)


def init_db():
    default_org = Organization.create(name="Default", slug='default', settings={})
    admin_group = Group.create(name='admin', permissions=['admin', 'super_admin'], org=default_org, type=Group.BUILTIN_GROUP)
    default_group = Group.create(name='default', permissions=Group.DEFAULT_PERMISSIONS, org=default_org, type=Group.BUILTIN_GROUP)

    return default_org, admin_group, default_group


def create_db(create_tables, drop_tables):
    db.connect_db()

    for model in all_models:
        if drop_tables and model.table_exists():
            model.drop_table(cascade=True)

        if create_tables and not model.table_exists():
            model.create_table()

    db.close_db(None)
```

### Technical details:

* Redash Version: 0.12.0.b2449
* Browser/OS: Amazon Linux AMI release 2016.09
* How did you install Redash: use `setup/amazon_linux/bootstrap.sh` with some customize

**Comment by arikfr** [comment]
👍 I updated the bootstrap.sh file to create this table.

**Comment by arikfr** [comment]
Oops, I just noticed you used the Amazon Linux bootstrap file but I updated the Ubuntu one :-(

**Comment by bwtakacy** [comment]
Thanks for quick fix 😄 

I will do similar in my amazon linux scripts.

**Comment by shamsulbuddy** [comment]
@arikfr  : I can see that this issue still persist in latest Docker Image . Do you suggest any fix ?
