### ISSUE TITLE
Issue in connecting with cassandra datasource

### ISSUE THREAD

**Issue by sivasankar95** [getredash/redash#1481]
Hi i am using cassandra database and i have a issue with connecting the database. If I test connection for the data source its showing this error 
![image](https://cloud.githubusercontent.com/assets/10654388/21416922/c7ee884c-c83c-11e6-8ad8-883c3caaa680.png)
and my log trace back is 
Traceback (most recent call last):
  File "cassandra/cluster.py", line 844, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11894)
    self.control_connection.connect()
  File "cassandra/cluster.py", line 2055, in cassandra.cluster.ControlConnection.connect (cassandra/cluster.c:39529)
    self._set_new_connection(self._reconnect_internal())
  File "cassandra/cluster.py", line 2090, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:40461)
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {u'192.168.0.117': TypeError('ref() does not take keyword arguments',)})

I can access the database by using my java code the database is up and running. I cant connect using redash. Can someone help with is issue??? and thanks in advance..

**Comment by yershalom** [comment]
Hi @sivasankar95 
What cassandra version and package are using?
What version of cassandra-driver is installed?

**Comment by arikfr** [comment]
Closing for inactivity. Feel free to reopen with extra information. Thanks 👍

**Comment by datatechyogi** [comment]
I am having same issue.Can you please let me know the solution.

**Comment by datatechyogi** [comment]
Cassandra Driver 3.1.1

**Comment by yershalom** [comment]
@datatechyogi Hi,
What cassandra version and distro are you running?

**Comment by datatechyogi** [comment]
3.x

**Comment by pushkarv** [comment]
I also have the similar issue.   here is the log output:     using Cassandra 3.0.11.1564

server_1    | [2017-07-09 04:59:29,101][PID:16][WARNING][cassandra.cluster] [control connection] Error connecting to 0.0.0.0:
server_1    | Traceback (most recent call last):
server_1    |   File "cassandra/cluster.py", line 2081, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:40178)
server_1    |     return self._try_connect(host)
server_1    |   File "cassandra/cluster.py", line 2101, in cassandra.cluster.ControlConnection._try_connect (cassandra/cluster.c:40691)
server_1    |     connection = self._cluster.connection_factory(host.address, is_control_connection=True)
server_1    |   File "cassandra/cluster.py", line 789, in cassandra.cluster.Cluster.connection_factory (cassandra/cluster.c:9765)
server_1    |     return self.connection_class.factory(address, self.connect_timeout, *args, **kwargs)
server_1    |   File "cassandra/connection.py", line 306, in cassandra.connection.Connection.factory (cassandra/connection.c:5650)
server_1    |     conn = cls(host, *args, **kwargs)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/cassandra/io/asyncorereactor.py", line 162, in __init__
server_1    |     self._connect_socket()
server_1    |   File "cassandra/connection.py", line 340, in cassandra.connection.Connection._connect_socket (cassandra/connection.c:6948)
server_1    |     raise socket.error(sockerr.errno, "Tried connecting to %s. Last error: %s" % ([a[4] for a in addresses], sockerr.strerror or sockerr))
server_1    | error: [Errno 111] Tried connecting to [('0.0.0.0', 9042)]. Last error: Connection refused
server_1    | [2017-07-09 04:59:29,102][PID:16][ERROR][cassandra.cluster] Control connection failed to connect, shutting down Cluster:
server_1    | Traceback (most recent call last):
server_1    |   File "cassandra/cluster.py", line 844, in cassandra.cluster.Cluster.connect (cassandra/cluster.c:11894)
server_1    |     self.control_connection.connect()
server_1    |   File "cassandra/cluster.py", line 2055, in cassandra.cluster.ControlConnection.connect (cassandra/cluster.c:39529)
server_1    |     self._set_new_connection(self._reconnect_internal())
server_1    |   File "cassandra/cluster.py", line 2090, in cassandra.cluster.ControlConnection._reconnect_internal (cassandra/cluster.c:40461)
server_1    |     raise NoHostAvailable("Unable to connect to any servers", errors)
server_1    | NoHostAvailable: ('Unable to connect to any servers', {u'0.0.0.0': error(111, "Tried connecting to [('0.0.0.0', 9042)]. Last error: Connection refused")})
server_1    | [2017-07-09 04:59:29,103][PID:16][INFO][metrics] method=POST path=/api/data_sources/1/test endpoint=datasourcetestresource status=200 content_type=application/json content_length=167 duration=12.41 query_count=4 query_duration=3.94
nginx_1     | 172.18.0.1 - - [09/Jul/2017:04:59:29 +0000] "POST /api/data_sources/1/test HTTP/1.1" 200 163 "http://localhost/data_sources/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36" "-"

**Comment by yuric22** [comment]
Replicating the answer [I've posted here](https://discuss.redash.io/t/how-to-add-cassandra-data-source/800/6):

I had the same `Unable to connect to any servers` problem after installing Redash **2.0.0.b2990** in AWS EC2 using the [ami-2d3c0a56 pre-baked AMI](https://redash.io/help-onpremise/setup/setting-up-redash-instance.html).

I've solved it by forcing the `cassandra-driver` reinstall to the [newest version I found](https://github.com/datastax/python-driver/releases), then restarting Redash services, all as root:

`$ pip install cassandra-driver==3.12 --force-reinstall --upgrade`
`$ supervisorctl restart all`

And I used @leinad_87  tip above to check the installed version: `pip list | grep cassan`

Using a Cassandra server with these versions: `cqlsh 5.0.1 | Cassandra 3.6 | CQL spec 3.4.2`
