### ISSUE TITLE
Invalid cert for www.googleapis.com

### ISSUE THREAD

**Issue by rockwotj** [getredash/redash#1503]
### Issue Summary

Trying to login on a custom install of Redash and it seems to not be able to finish the google oauth for authentication. I believe I have the setup correct, and if I `curl` that URL from the box I get no cert errors, so I'm not sure what's going on.

### Technical details:

* Redash Version: v0.12.0.b2449
* Browser/OS: Chrome/MacOs
* How did you install Redash: Building from source

* Python version:
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2

Stack Trace:

[2017-01-03 17:59:52,404][PID:1477][INFO][metrics] method=GET path=/oauth/google endpoint=google_oauth.authorize status=500 content_type=? content_length=-1 duration=4.48 query_count=0 query_duration=0.00
[2017-01-03 17:59:53,785][PID:1478][INFO][requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): www.googleapis.com
[2017-01-03 17:59:53,804][PID:1478][ERROR][redash] Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Production/redash/releases/current/redash/authentication/google_oauth.py", line 100, in authorized
    profile = get_user_profile(access_token)
  File "/Production/redash/releases/current/redash/authentication/google_oauth.py", line 34, in get_user_profile
    response = requests.get('https://www.googleapis.com/oauth2/v1/userinfo', headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by arikfr** [comment]
Do you have `certifi` installed?

**Comment by rockwotj** [comment]
Yes, I fixed it by exporting the environment variable: `REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt` Not sure what was going on with the certs that `certifi` uses? It should trust that cert.
