### ISSUE TITLE
Query Embed Not Working Angular Injection Issue (Redash 1.0.0 Beta)

### ISSUE THREAD

**Issue by GAwadhwalAtlassian** [getredash/redash#1577]
Hello,

I am encountering an issue after upgrading to the beta channel 1.0.0, which has broken all embeds.

Embeds result in this:
<img width="715" alt="screen shot 2017-02-08 at 9 43 12 am" src="https://cloud.githubusercontent.com/assets/24925514/22759106/5b665d78-eea5-11e6-8f81-ab0c460dcc7e.png">

Looking at the Chrome Console (using chrome Version 56.0.2924.87 (64-bit) MAC OSX)

I get these errors, related to angular injection i believe

`Error: [$injector:unpr] Unknown provider: eProvider <- e
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=eProvider%20%3C-%20e
    at https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:377
    at https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:21267
    at Object.i [as get] (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:20223)
    at https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:21352
    at i (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:20223)
    at r (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:20523)
    at Object.a [as invoke] (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:20695)
    at u.instance (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:7:14796)
    at f (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:7:1725)
    at a (https://redashdev1.data.internal.atlassian.com/vendor.601f68ed8a144c72b637.js:6:30356) <div ng-view="" class="ng-scope">
(anonymous) @ angular.js:13920
`

I upgraded from 0.12 via the upgrade script to the beta channel, and this is running on an EC2 server with a RDS database. 

I have restarted the server etc, to no avail.

**Comment by arikfr** [comment]
Fixed in #1607.
