### ISSUE TITLE
Create admin from clean database tables

### ISSUE THREAD

**Issue by zodman** [getredash/redash#1608]
### Issue Summary

Ubuntu with python2.7 and virtualenv. i running the bootstrap.sh step by step

### Steps to Reproduce

```
(env)web@ns2:~/redash.interalia.net/redash$ ./manage.py users create --admin --password admin "Admin" "admin"
Creating user (Admin, admin) in organization default...
Admin: True
Login with Google Auth: False

Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    manager()
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/export/web/redash.interalia.net/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/export/web/redash.interalia.net/redash/redash/cli/users.py", line 81, in create
    groups = build_groups(org, groups, is_admin)
  File "/export/web/redash.interalia.net/redash/redash/cli/users.py", line 21, in build_groups
    groups = [org.default_group.id]
AttributeError: 'NoneType' object has no attribute 'default_group'
```

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by zodman** [comment]
i think the organization "default" didnt exists

**Comment by zodman** [comment]
(env)web@ns2:~/redash.interalia.net/redash$ ./manage.py org list
(env)web@ns2:~/redash.interalia.net/redash$

**Comment by arikfr** [comment]
Is this the master branch?

**Comment by zodman** [comment]
yes!

**Comment by arikfr** [comment]
The default organization is created when you finish the quick setup flow -- just open the app in the browser and finish the setup. It will create both the organization and the first admin user.

**Comment by zodman** [comment]
mmm on the bootstrap.sh are out update because is not necesary create admin user because it will be ask on finish setup

**Comment by arikfr** [comment]
That's correct. The bootstrap script is still designed to work with the stable releases. Once final version of v1.0.0 is released, I'll update the bootstrap script.
