### ISSUE TITLE
bootstrap.sh failing with error : peewee.ProgrammingError: relation "query_snippets" already exists

### ISSUE THREAD

**Issue by SnchitGrover** [getredash/redash#1620]
[2017-02-21 10:11:44,118][PID:22373][INFO][requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): metadata.google.internal
[2017-02-21 10:11:44,120][PID:22373][WARNING][redash.query_runner] BigQueryGCE query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2017-02-21 10:11:44,406][PID:22373][ERROR][peewee] CREATE TABLE "query_snippets" ("id" SERIAL NOT NULL PRIMARY KEY, "updated_at" timestamp with time zone NOT NULL, "created_at" timestamp with time zone NOT NULL, "org_id" INTEGER NOT NULL, "trigger" VARCHAR(255) NOT NULL, "description" TEXT NOT NULL, "user_id" INTEGER NOT NULL, "snippet" TEXT NOT NULL, FOREIGN KEY ("org_id") REFERENCES "organizations" ("id"), FOREIGN KEY ("user_id") REFERENCES "users" ("id")) []
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: relation "query_snippets" already exists

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4055, in create_table
    db.create_table(cls)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3152, in create_table
    return self.execute_sql(*qc.create_table(model_class, safe))
  File "redash/metrics/database.py", line 22, in execute_sql
    result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: relation "query_snippets" already exists

**Comment by arikfr** [comment]
You probably used a newer tarball/version where this was fixed (that query snippets table wasn't part of the list of all models). Anyway, you can ignore this, as this is the last line in the script.

Because we intend the script to be used with regular releases, where this issue doesn't exist, I'm closing this. Feel free to follow up with questions if you have.
