### ISSUE TITLE
cassandra-driver fails to compile during redash installation

### ISSUE THREAD

**Issue by vorou** [getredash/redash#1632]
### Issue Summary

I'm trying to install redash using Docker Compose method. It fails on cassandra-driver installation. Also, it takes a looot of time to complete (i.e., fail). I'm on CentOS 7.3.1611 x64, smallest possible droplet on DigitalOcean. See full log at the bottom.

Running
```
pip install cassandra-driver
```
completes in a couple of seconds w/o any errors. So, I guess the docker container is missing something, but I'm not sure how to investigate it further.

Also saw the same problem when tried to install it locally on Ubuntu 14.04 (in VirtualBox on Windows). It's gone away when I switched to Ubuntu 16.04.

### Steps to Reproduce

```
docker-compose -f docker-compose.production.yml run --rm server create_db
```

### Technical details:

* Redash Version: the one which is in Docker right now, not sure how to check it.
* Browser/OS: CentOS 7.3.1611 x64
* How did you install Redash: docker compose

```
Running setup.py bdist_wheel for cassandra-driver: started
  Running setup.py bdist_wheel for cassandra-driver: still running...
  Failed building wheel for cassandra-driver
  Running setup.py bdist_wheel for cassandra-driver: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-I0qwhg/cassandra-driver/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpPvzsubpip-wheel- --python-tag cp27:
  Unable to find pgen, not compiling formal grammar.
  warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.pxd' under directory 'Cython/Utility'
  x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-I0qwhg/cassandra-driver/setup.py", line 430, in <module>
      run_setup(None)
    File "/tmp/pip-build-I0qwhg/cassandra-driver/setup.py", line 428, in run_setup
      **kw)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

  ----------------------------------------
  Running setup.py clean for cassandra-driver
```

**Comment by vorou** [comment]
It turns out 512MB is not enough to compile cassandra-driver. I [turned the swap on](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-centos-7), and now it works.

Here's a [relevant SO answer](http://stackoverflow.com/a/25584112/1085375), just in case.
