### ISSUE TITLE
Permission modal broken in 1.0.0 b2777 RC1

### ISSUE THREAD

**Issue by majofi** [getredash/redash#1633]
I installed the RC on an Ubuntu 14 using the bootstrap script and the updater afterwards.
Everything went smoothly and redash works well. But I activated the "REDASH_FEATURE_SHOW_PERMISSIONS_CONTROL" feature and the modal opens but there are no users listed. Looking at the console I see a JS error which is not really pointing to me the problem (due to uglifying). How can I force webpack to not uglify and recreate the assets on live so I can create a better bug report?

Nevertheless the JS error:

`Error: [$injector:unpr] Unknown provider: eProvider <- e
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=eProvider%20%3C-%20e
    at http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:377
    at http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:21267
    at Object.i [as get] (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:20223)
    at http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:21352
    at i (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:20223)
    at r (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:20523)
    at Object.a [as invoke] (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:20695)
    at u.instance (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:7:14796)
    at f (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:7:1725)
    at a (http://redash.curated-shopping.io/vendor.665084fc1a2e4009e212.js:6:30356) <div class="modal-content" uib-modal-transclude="">
(anonymous) @ vendor.665084fc1a2e4009e212.js:7`

**Comment by ifeldmanAtlassian** [comment]
Same issue happens to us
