### ISSUE TITLE
Upgrading redash caused internal server errors, fixed by creating symlink

### ISSUE THREAD

**Issue by r-tock** [getredash/redash#1635]
Looks like the path may have changed. I had to alias
`ln -s client/ rd_ui` to make it work again.

Upgraded from 1.0.0 rc1 to 1.0.0 rc2
```
[2017-02-26 17:35:09,227][PID:619][ERROR][redash] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/redash/redash.1.0.0-rc.2.b2777/redash/handlers/static.py", line 30, in index
    return send_file(full_path, **dict(cache_timeout=0, conditional=True))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/opt/redash/redash.1.0.0-rc.2.b2777/redash/../rd_ui/dist/index.html'
[2017-02-26 17:35:09,227][PID:619][INFO][metrics] method=GET path=/ endpoint=redash.index status=500 content_type=? co
```

**Comment by arikfr** [comment]
Did you remove the `REDASH_STATIC_ASSETS_PATH` definition from your `.env` file?

**Comment by r-tock** [comment]
Nope, that was it, removed the config and deleted the symlink.

**Comment by carambola** [comment]
Had the exact same error. Using `ln -s client/ rd_ui` seems to solve this issue.

**Comment by roeyyaniv** [comment]
Had the exact same issue. using `ln -s client/ rd_ui` seems to resolve this issue.
