### ISSUE TITLE
fails to build a production image with docker-compose

### ISSUE THREAD

**Issue by gingerlime** [getredash/redash#1655]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

I've cloned the repo on a DO droplet with docker preinstalled (`docker --version` shows `Docker version 17.03.0-ce, build 60ccb22`). I've run `docker-compose -f docker-compose.production.yml run --rm server create_db` as detailed on the installation guide, but it fails with a build error (See below)

### Steps to Reproduce

1. `docker-compose -f docker-compose.production.yml run --rm server create_db`
2. This is the error (sorry, pretty long, but I removed all the previous successful output):

```
  x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 430, in <module>
      run_setup(None)
    File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 428, in run_setup
      **kw)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
  
  ----------------------------------------
  Failed building wheel for cassandra-driver
  Running setup.py clean for cassandra-driver
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QrWpXN/cassandra-driver/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Unable to find pgen, not compiling formal grammar.
  warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
  warning: no files found matching '*.pxd' under directory 'Cython/Utility'
  x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 430, in <module>
      run_setup(None)
    File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 428, in run_setup
      **kw)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
  
  ----------------------------------------
  Failed cleaning build dir for cassandra-driver
  Running setup.py bdist_wheel for wtforms: started
  Running setup.py bdist_wheel for wtforms: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/36/35/f3/7452cd24daeeaa5ec5b2ea13755316abc94e4e7702de29ba94
  Running setup.py bdist_wheel for oauthlib: started
  Running setup.py bdist_wheel for oauthlib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e7/4e/b5/c36a97caf4408037eb35aeb1e0a80d95ea0c521a562c3488a3
  Running setup.py bdist_wheel for alembic: started
  Running setup.py bdist_wheel for alembic: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/37/02/8e/1b941acb6b5c81a5c3cc10b6ac6532f488ee04c694544cfe6d
  Running setup.py bdist_wheel for Flask-Script: started
  Running setup.py bdist_wheel for Flask-Script: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e2/ea/d8/8d114e46cef819f7d9879504a7f9cb2a88a479af2858223d9f
  Running setup.py bdist_wheel for billiard: started
  Running setup.py bdist_wheel for billiard: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/11/68/13/9f46e6b8760998754ce90ef87103ea7f4e80504ffc9f93a362
  Running setup.py bdist_wheel for zope.interface: started
  Running setup.py bdist_wheel for zope.interface: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/00/aa/8b/f1d1eb398423e59894b45ee151344e243808156c2d182c9f4e
  Running setup.py bdist_wheel for msgpack-python: started
  Running setup.py bdist_wheel for msgpack-python: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/2c/e7/e7/9031652a69d594665c5ca25e41d0fb3faa024e730b590e4402
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for pycryptodome: started
  Running setup.py bdist_wheel for pycryptodome: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/82/80/08/e4cb0e06e4df5c5104899de9018e1829683c28c0ee9c45f4a1
  Running setup.py bdist_wheel for Mako: started
  Running setup.py bdist_wheel for Mako: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/34/be/28/7999aa61d80a775c9e85a5a7d345777f73e87e6e30573e9551
  Running setup.py bdist_wheel for python-editor: started
  Running setup.py bdist_wheel for python-editor: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/84/d6/b8/082dc3b5cd7763f17f5500a193b6b248102217cbaa3f0a24ca
  Running setup.py bdist_wheel for anyjson: started
  Running setup.py bdist_wheel for anyjson: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/06/3d/74/f64c3ce3266df2598031818ecc86bc25c8ccede0723973f119
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
Successfully built itsdangerous MarkupSafe httplib2 Flask-Admin Flask-SQLAlchemy Flask-Migrate flask-mail flask-sslify Flask-Limiter passlib aniso8601 blinker psycopg2 SQLAlchemy sqlparse honcho statsd RestrictedPython pysaml2 pycrypto funcy semver pystache cryptography simplejson coverage pymongo google-api-python-client gspread impyla MySQL-python oauth2client pyhive pyOpenSSL vertica-python td-client dql sasl thrift thrift-sasl wtforms oauthlib alembic Flask-Script billiard zope.interface msgpack-python future pycryptodome Mako python-editor anyjson pycparser
Failed to build cassandra-driver
Installing collected packages: itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, Flask, httplib2, wtforms, Flask-Admin, six, pytz, python-dateutil, aniso8601, Flask-RESTful, Flask-Login, requests, oauthlib, requests-oauthlib, Flask-OAuthLib, SQLAlchemy, Flask-SQLAlchemy, Mako, python-editor, alembic, Flask-Script, Flask-Migrate, blinker, flask-mail, flask-sslify, limits, Flask-Limiter, passlib, psycopg2, redis, sqlparse, honcho, statsd, gunicorn, billiard, anyjson, amqp, kombu, celery, jsonschema, RestrictedPython, decorator, paste, zope.interface, WebOb, repoze.who, pycrypto, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, pysaml2, funcy, contextlib2, raven, semver, xlsxwriter, pystache, parsedatetime, simplejson, nose, coverage, funcsigs, pbr, mock, pymongo, google-api-python-client, gspread, thrift, impyla, influxdb, MySQL-python, oauth2client, pyhive, vertica-python, msgpack-python, urllib3, td-client, pymssql, docutils, jmespath, botocore, dynamo3, pyparsing, dql, sasl, thrift-sasl, futures, cassandra-driver, ijson, boto3, pyasn1-modules, future, pycryptodome, snowflake-connector-python, simple-salesforce, certifi
  Running setup.py install for cassandra-driver: started
    Running setup.py install for cassandra-driver: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QrWpXN/cassandra-driver/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-CJHxjF-record/install-record.txt --single-version-externally-managed --compile:
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 430, in <module>
        run_setup(None)
      File "/tmp/pip-build-QrWpXN/cassandra-driver/setup.py", line 428, in run_setup
        **kw)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QrWpXN/cassandra-driver/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-CJHxjF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-QrWpXN/cassandra-driver/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'server' failed to build: The command '/bin/sh -c pip install -r requirements.txt -r requirements_dev.txt -r requirements_all_ds.txt' returned a non-zero code: 1
```

### Technical details:

* Redash Version: using `master` from a freshly cloned repo
* Browser/OS: Ubuntu 16.04 with docker `17.03.0-ce` and docker-compose `docker-compose version 1.9.0, build 2585387`
* How did you install Redash: `docker-compose -f docker-compose.production.yml run --rm server create_db`

**Comment by avlad** [comment]
also test 5 different versions 9tags) - no one not start, loop of errors and nothing more

try to build on Debian Wheezy from bootstrap script - same result


so the question - ANY version of docker image or bootstrap script work from scratch? (without  pain :-) )

**Comment by arikfr** [comment]
What is the size of the DO droplet? (memory wise)

**Comment by avlad** [comment]
6G

**Comment by arikfr** [comment]
RAM?

**Comment by avlad** [comment]
if I correct understand question - setting for docker 4cpu, 6Gb RAM

but errors go by circle:
  __import__(module)
  File "/opt/redash/current/redash/__init__.py", line 60, in <module>
    reset_new_version_status()
  File "/opt/redash/current/redash/version_check.py", line 34, in reset_new_version_status
    latest_version = get_latest_version()
  File "/opt/redash/current/redash/version_check.py", line 40, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))

**Comment by arikfr** [comment]
6GB of RAM is plenty enough, but the question was to @gingerlime - as I think he has a different problem.

In your case, can you describe how you're setting things up?

**Comment by avlad** [comment]
in my case - open kitematic, search for reddish official, and select any of versions
same as for all other docker images which I use for test

for Debian - it was other problem with a lot of missed dependencies and unresolved packages, for this reason I decide start tests with docker

**Comment by arikfr** [comment]
But... are you running Redis & PostgreSQL alongside it?

**Comment by avlad** [comment]
Short Description
Official Docker images for the Re:dash project.
Full Description
We upload a new image for every CI build. The latest stable version tagged as latest.


this is all hat You have on docker hub page :-) - https://hub.docker.com/r/redash/redash/
so, I need setup additional machines? ok

**Comment by gingerlime** [comment]
@arikfr Thanks for the tip. I think the droplet was simply running out of memory. It worked after adding more memory!
