### ISSUE TITLE
After a failed query to Analytics, Redash is crash looping any ideas how to stop it?

### ISSUE THREAD

**Issue by r-tock** [getredash/redash#1672]
After a failed query to Analytics, Redash is crash looping any ideas how to stop it?

```==> ../logs/celery_error.log <==
[2017-03-16 19:51:43,994][PID:12510][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[2017-03-16 19:51:44,183][PID:12510][INFO][redash.query_runner.google_analytics] cannot import name SignedJwtAssertionCredentials
Traceback (most recent call last):
File "/usr/local/bin/celery", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/celery/main.py", line 14, in main
_main()
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
cmd.execute_from_commandline(argv)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
super(CeleryCommand, self).execute_from_commandline(argv)))
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 279, in execute_from_commandline
argv = self.setup_app_from_commandline(argv)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
self.app = self.find_app(app)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 503, in find_app
return find_app(app, symbol_by_name=self.symbol_by_name)
File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 355, in find_app
sym = symbol_by_name(app, imp=imp)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 506, in symbol_by_name
return imports.symbol_by_name(name, imp=imp)
File "/usr/local/lib/python2.7/dist-packages/kombu/utils/imports.py", line 56, in symbol_by_name
module = imp(module_name, package=package, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
return imp(module, package=package)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/opt/redash/redash.1.0.0-rc.2.b2777/redash/init.py", line 70, in <module>
reset_new_version_status()
File "/opt/redash/redash.1.0.0-rc.2.b2777/redash/version_check.py", line 34, in reset_new_version_status
latest_version = get_latest_version()
File "/opt/redash/redash.1.0.0-rc.2.b2777/redash/version_check.py", line 40, in get_latest_version
return redis_connection.get(REDIS_KEY)
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
return self.execute_command('GET', name)
File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
connection.send_command(args)
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
self.send_packed_command(self.pack_command(*args))
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
self.connect()
File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
==> ../logs/supervisord.log <==
2017-03-16 19:51:44,509 INFO exited: redash_celery_scheduled (exit status 1; not expected)
==> ../logs/api_error.log <==
[2017-03-16 19:51:44 +0000] [12539] [INFO] Starting gunicorn 19.7.0
[2017-03-16 19:51:44 +0000] [12539] [INFO] Listening at: http://127.0.0.1:5000 (12539)
[2017-03-16 19:51:44 +0000] [12539] [INFO] Using worker: sync
==> ../logs/supervisord.log <==
2017-03-16 19:51:44,540 INFO spawned: 'redash_celery_scheduled' with pid 12549
==> ../logs/api_error.log <==
[2017-03-16 19:51:44 +0000] [12550] [INFO] Booting worker with pid: 12550
[2017-03-16 19:51:44 +0000] [12554] [INFO] Booting worker with pid: 12554
==> ../logs/celery_error.log <==
[2017-03-16 19:51:44,583][PID:12528][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
```

**Comment by arikfr** [comment]
`redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

Looks like your Redis server is down. 

In the future, please use the [forum](discuss.redash.io) for support/usage questions. Thanks!

**Comment by r-tock** [comment]
Thanks, filed https://discuss.redash.io/t/redash-crash-looping/504
