### ISSUE TITLE
Upgrade from redash.0.12.0.b2449 to redash.1.0.3.b2850 results in internal server error on Ubuntu 14.04

### ISSUE THREAD

**Issue by dvuxmatcha** [getredash/redash#1794]
### Steps to Reproduce

1. Update REDASH_DATABASE_URL from "postgresql://redash" to "postgresql:///redash" in .env
2. Remove REDASH_STATIC_ASSETS_PATH from .env
3. ```wget https://raw.githubusercontent.com/getredash/redash/master/bin/upgrade```
4. ```chmod +x upgrade```
5. ```sudo ./upgrade```

The API is still working as expected after the upgrade but accessing the web interface results in a 500 page with the following message: 

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

### Technical details:

* Redash Version: 1.0.3.b2850
* Browser/OS: Chrome 59.0.3071.71 (Official Build) beta (64-bit)/Ubuntu 14.04
* How did you install Redash: With the Ubuntu 14.04 provisioning script provided by Redash in the past

```
drwxr-xr-x 6 redash root       4096 May 29 17:39 .
drwxr-xr-x 3 root   root       4096 Mar  6 18:16 ..
lrwxrwxrwx 1 root   root         30 May 29 17:14 current -> /opt/redash/redash.1.0.3.b2850
-rw-r--r-- 1 redash nogroup     355 May 29 17:39 .env
drwxr-xr-x 2 redash nogroup    4096 Apr 26 21:29 logs
drwxr-xr-x 8 redash nogroup    4096 Apr 25 10:54 redash.0.12.0.b2449
drwxr-xr-x 9 redash root       4096 May 29 17:23 redash.1.0.3.b2850
-rw-r--r-- 1 root   root    6585226 Apr 18 16:34 redash.1.0.3.b2850.tar.gz
drwxr-xr-x 2 redash nogroup    4096 Mar  7 10:26 supervisord
```

/opt/redash/current/client/dist also exists.

**Comment by arikfr** [comment]
Please check `/opt/redash/logs/api_error.log` for relevant error messages when getting the 500 page.

Also if you have the output of the upgrade process please share it as well.

**Comment by dvuxmatcha** [comment]
The issue was actually resolved by a restart of the VM running our Redash instance, although a restart of the database also seemed to be sufficient in a previous debugging attempt.

/opt/redash/logs/api_error.log output:

```
[2017-05-29 17:16:19,160][PID:20107][ERROR][redash] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2449/redash/handlers/static.py", line 60, in index
    client_config=json.dumps(client_config))
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html
```

I do not have the output of the upgrade process anymore but it went smoothly and no error messages were thrown.

Given that the issue no longer exists since the restart, feel free to close this unless you'd like more information from me. Thanks!

**Comment by aauVadim** [comment]
Hey guys, 
Currently I'm trying to upgrade from 0.12 ver to 1.0.3 version. 
I'm running into a similar problem with my instance.

Here is an output of api_error.log

```
[2020-11-15 23:25:23,376] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/redash/redash-1.0.3/redash/handlers/static.py", line 30, in index
    return send_file(full_path, **dict(cache_timeout=0, conditional=True))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/opt/redash/redash-1.0.3/redash/../client/dist/index.html'
[2020-11-15 23:25:23,376][PID:1673][ERROR][redash] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/redash/redash-1.0.3/redash/handlers/static.py", line 30, in index
    return send_file(full_path, **dict(cache_timeout=0, conditional=True))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/opt/redash/redash-1.0.3/redash/../client/dist/index.html'
[2020-11-15 23:25:23,379][PID:1673][INFO][metrics] method=GET path=/ endpoint=redash.index status=500 content_type=? content_length=-1 duration=22.72 query_count=2 query_duration=3.19

```

on my machine that directory `/opt/redash/redash-1.0.3/redash/../client/dist/` does not exist. 

Trying to install/upgrade Redash 1.0.3 myself, due to upgrade script from: 
`https://raw.githubusercontent.com/getredash/redash/master/bin/upgrade` is only aimed to upgrade to latest version, which is v8 at this point. 


Please help.
