### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'settings' 

### ISSUE THREAD

**Issue by dsingaravelan** [getredash/redash#1795]
Hi I have followed this link for redash installation. 

when I run the below command I got this error 
_sudo -u redash bin/run ./manage.py org set_google_apps_domains http://mydomain.com_

this is the complete error details:

Traceback (most recent call last):
  File "/opt/redash/redash.1.0.1.b2833/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/redash/redash.1.0.1.b2833/redash/cli/organization.py", line 17, in set_google_apps_domains
    organization.settings[k] = domains.split(',')
AttributeError: 'NoneType' object has no attribute 'settings'

I executed  this command as Root.

**Comment by nnabinh** [comment]
Same thing happens to me

**Comment by arikfr** [comment]
You need to finish the setup process first (open the app in the browser and follow instructions).

We should probably clarify this in the docs:

> **Before you can continue, it will ask you to create your admin account. Once this is done, you can start using Redash.** But to make it useful, there are a few more steps that you need to manually do to complete the setup:

**Comment by zachliu** [comment]
in case anyone is still seeing this in the latest 9.0.0-beta version, you still need to finish the setup process first :grin:
