### ISSUE TITLE
some weird error messages in log file.

### ISSUE THREAD

**Issue by hey-jude** [getredash/redash#1827]
### Issue Summary

Sometimes, error message on supervisor redash server stderr log
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Logged from file request.py, line 32
```

### Steps to Reproduce

Don't know.

### Technical details:

* Redash Version: 1.0.3
* Browser/OS: Chrome / Macosx
* How did you install Redash: Using ec2 ami.

**Comment by arikfr** [comment]
I believe [this change](https://github.com/getredash/redash/commit/7d5d7c4a6b6c609ed925f48bfebd114dbdf152dc#diff-fcd0d1979009d178bca52ed6d0801bb6R31) fixes this issue.

**Comment by hey-jude** [comment]
👍
