### ISSUE TITLE
imapla beeswax TypeError: expecting tuple of size 3 for list/set type args

### ISSUE THREAD

**Issue by yuua** [getredash/redash#1840]
Hi ! 
Thank you for this great tool!!

Since an error occurred in the latest version, I made an issue
Is there a way to solve this error?

### Issue Summary

using re:dash Dockerhub latest version(1.0.3) 
An error occurs when using Impala as a data source.

+ Error message 

 `TypeError: expecting tuple of size 3 for list/set type args`

### Steps to Reproduce

1. This is the first step

+ data_sources imapla adding

2. This is the second step, etc.

+ It happens with test connection and query execution

An error occurs

![2017-06-23 11 23 29](https://user-images.githubusercontent.com/1557081/27464117-92c563e8-5806-11e7-96ea-2d37595f82ee.png)

+ stack trace

```
worker_1    | [2017-06-22 10:20:14,869: ERROR/Worker-3] expecting tuple of size 3 for list/set type args
worker_1    | Traceback (most recent call last):
worker_1    |   File "/app/redash/query_runner/impala_ds.py", line 106, in run_query
worker_1    |     cursor.execute(query)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/dbapi/beeswax.py", line 156, in execute
worker_1    |     self._execute_sync(op)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/dbapi/beeswax.py", line 162, in _execute_sync
worker_1    |     operation_fn()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/dbapi/beeswax.py", line 154, in op
worker_1    |     query)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_rpc/beeswax.py", line 258, in execute_statement
worker_1    |     rpc_result = __do_rpc(lambda: service.query(query))
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_rpc/beeswax.py", line 352, in __do_rpc
worker_1    |     ret = rpc()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_rpc/beeswax.py", line 258, in <lambda>
worker_1    |     rpc_result = __do_rpc(lambda: service.query(query))
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_thrift_gen/beeswax/BeeswaxService.py", line 141, in query
worker_1    |     self.send_query(query)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_thrift_gen/beeswax/BeeswaxService.py", line 148, in send_query
worker_1    |     args.write(self._oprot)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/impala/_thrift_gen/beeswax/BeeswaxService.py", line 765, in write
worker_1    |     oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
worker_1    | TypeError: expecting tuple of size 3 for list/set type args
```
### Technical details:

* Redash Version: v1.0.3
* Browser/OS: mac os x
* How did you install Redash: Docker

Thank you.

**Comment by yuua** [comment]
Thrift=0.9.3 works well. 
Thrift = 0.10.0 is an error.
