### ISSUE TITLE
Alerts not working for webhook destination

### ISSUE THREAD

**Issue by jeduardo** [getredash/redash#1948]
### Issue Summary

When an alert is triggered over a condition for a given query, whilst the email is sent successfully, the webhook is not called. The following exception can then be found in the redash_celery-stderr file:
```
[2017-09-05 16:55:37,742: ERROR/Worker-9] redash.tasks.check_alerts_for_query[2ea2214a-e80d-46c7-a257-7d54e61fbbb0]: Error with processing destination
Traceback (most recent call last):
  File "/opt/redash/redash.1.0.1.b2833/redash/tasks/alerts.py", line 23, in notify_subscriptions
    subscription.notify(alert, alert.query_rel, subscription.user, new_state, current_app, host)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
DetachedInstanceError: Parent instance <AlertSubscription at 0x7fb7f98890d0> is not bound to a Session; lazy load operation of attribute 'user' cannot proceed
```

### Steps to Reproduce

1. Create a new webhook destination
2. Create a new alert over the condition of a query
3. Set the webhook as one possible destination
4. Trigger the alert

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 1.0.1+b2833
* Browser/OS: Ubuntu Server 16.04 LTS
* How did you install Redash: online installation script.

**Comment by arikfr** [comment]
Fixed already. Please upgrade to v2.
