### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by crooy** [getredash/redash#2150]
We appear to be having this issue: https://github.com/mozilla/redash/issues/63

I think this might be related to https://github.com/lepture/example-oauth2-server/issues/24

```
[2017-12-11 08:33:44,374] ERROR in app: Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 97, in authorized
    access_token = resp['access_token']
TypeError: sequence index must be integer, not 'str'
[2017-12-11 08:33:44,374][PID:19908][ERROR][redash] Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 97, in authorized
    access_token = resp['access_token']
TypeError: sequence index must be integer, not 'str'
```

**Comment by crooy** [comment]
i can confirm that this helps https://github.com/mozilla/redash/commit/65142e398035a61acc8cb427e2eeed0427b8f7b4

**Comment by crooy** [comment]
although it also required me to do `sudo pip uninstall pyopenssl ; sudo pip install pyopenssl` afterwards to fix the following error:

```
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
[2017-12-11 09:31:59,713][PID:7538][ERROR][redash] Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 104, in authorized
    profile = get_user_profile(access_token)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 36, in get_user_profile
    response = requests.get('https://www.googleapis.com/oauth2/v1/userinfo', headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

**Comment by arikfr** [comment]
I think we move pyOpenSSL from `requirements_all_ds.txt` to `requirements.txt`... and we can definitely update flask-oauthlib. Want to make this pull request?

**Comment by crooy** [comment]
sure will do
