### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by roydar** [getredash/redash#2164]
Please fix

we get error , cron jobs  not work

[2017-12-15 10:58:08,391][PID:20658][ERROR][MainProcess] Task redash.tasks.refresh_queries[40b3a799-9464-447e-997f-ac4f9163c394] raised unexpected: OverflowError('Python int too large to convert to C long',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.3.0.0.b3134/redash/worker.py", line 71, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.3.0.0.b3134/redash/tasks/queries.py", line 275, in refresh_queries
    for query in models.Query.outdated_queries():
  File "/opt/redash/redash.3.0.0.b3134/redash/models.py", line 914, in outdated_queries
    if should_schedule_next(retrieved_at, now, query.schedule, query.schedule_failures):
  File "/opt/redash/redash.3.0.0.b3134/redash/models.py", line 769, in should_schedule_next
    next_iteration += datetime.timedelta(minutes=2**failures)
OverflowError: Python int too large to convert to C long

just fixed it with comment out this line
#next_iteration += datetime.timedelta(minutes=2**failures)

This error since version 2.x

Please can you fix it in next releases

**Comment by guidopetri** [comment]
Hi @roydar , is this still happening with the latest redash? We have a `preview` image on dockerhub you can use. Since 2017 we've upgraded lots of things so I wouldn't be surprised if this got fixed a long while ago.
