### ISSUE TITLE
Can't create user from CLI with manage.py

### ISSUE THREAD

**Issue by nateevans** [getredash/redash#2168]
### Issue Summary
When trying to create a User through the command line, I'm running into python errors. I realize I can create the user through the GUI, but I am provisioning with Ansible and want to automate as much as possible.

#### Here's the command I tried:
(running through docker, but I doubt that would make a difference)

**Create user without organization or groups**
```
docker exec -it redash_server /app/manage.py users create user@mail.com joesmith --admin --password=mypassword123
```
**Expectation**: The user would be created and defaults would be used for organization and group

**Actual Result**: 
```
root@ubuntu-test:~# docker exec -it redash_server /app/manage.py users create user@mail.com joesmith --admin --password=mypassword123
[2017-12-18 21:02:12,146][PID:212][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2017-12-18 21:02:12,163][PID:212][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Creating user (user@mail.com, joesmith) in organization default...
Admin: True
Login with Google Auth: False

Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/app/redash/cli/users.py", line 82, in create
    groups = build_groups(org, groups, is_admin)
  File "/app/redash/cli/users.py", line 22, in build_groups
    groups = [org.default_group.id]
AttributeError: 'NoneType' object has no attribute 'default_group'
```

### Technical details:

* Redash Version: Redash 3.0.0
* Python 2.7.12
* Browser/OS: Ubuntu 16.04
* How did you install Redash: Docker install

**Comment by kyoshidajp** [comment]
That reason is default organization and groups does not exist.

When you create user by GUI, `setup` method will create it.
https://github.com/getredash/redash/blob/release/3.0.x/redash/handlers/setup.py#L22

I have requested feature #2179 for this situation. If the PR is merged, we can create user with organization and groups, like this.

```
docker exec -it redash_server /app/manage.py users create_root user@mail.com joesmith \
--password mypassword123 --org default
```

**Comment by kyoshidajp** [comment]
The easiest way is an emulating POST action via GUI by CLI.

For example:

```
docker exec -it redash_server wget localhost:5000/setup --post-data="name=joesmith&email=user@mail.com&password=mypassword123&security_notifications=y&newsletter=y&org_name=default" -O /dev/null
```

I think this is a hacky solution :neckbeard:

**Comment by gramakri** [comment]
Same as #1608

**Comment by arikfr** [comment]
You can either create the organization using the setup flow or use the (not so-) new `create_root` CLI command to create both the first admin and organization.
