### ISSUE TITLE
Internal server error after authenticating using google

### ISSUE THREAD

**Issue by Mallouly** [getredash/redash#2190]
* Redash Version 3.0
* How did you install Redash - aws image

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
[2017-12-31 15:43:44,386] ERROR in app: Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 104, in authorized
    profile = get_user_profile(access_token)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 36, in get_user_profile
    response = requests.get('https://www.googleapis.com/oauth2/v1/userinfo', headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
[2017-12-31 15:43:44,386][PID:12974][ERROR][redash] Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 104, in authorized
    profile = get_user_profile(access_token)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 36, in get_user_profile
    response = requests.get('https://www.googleapis.com/oauth2/v1/userinfo', headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
[2017-12-31 15:43:44,387][PID:12974][INFO][metrics] method=GET path=/oauth/google_callback endpoint=google_oauth_callback status=500 content_type=? content_length=-1 duration=197.36 query_count=0 query_duration=0.00

any suggestions?

**Comment by 10kc-awright** [comment]
I had a very similar problem, saw the cert verification failure when trying to google auth, but also got it when trying to upgrade. 

Ended up manually uninstalling pyopenssl ` sudo pip uninstall pyopenssl` and installing it again `sudo pip install pyopenssl`and then restarting services from `/opt/redash/current` with `sudo supervisorctl restart all` and everything came up fine and authentication works with google.

It looks like https://github.com/getredash/redash/pull/2154 was supposed to fix this, not sure what's up.

**Comment by Mallouly** [comment]
thanks! it's working now

**Comment by RichardLitt** [comment]
Also related to #2150.

**Comment by kyoshidajp** [comment]
This issue has been solved. Feel free to reopen if happens again.
