### ISSUE TITLE
Upgrade after create AWS instance

### ISSUE THREAD

**Issue by xpromx** [getredash/redash#2229]
Hello!, 

I just created a new Instance in AWS and run the upgrade script, but it's not working. how can i fix it? i want to run the version 3.x of redash.

````
...:/opt/redash/current$ sudo bin/upgrade
Starting Redash upgrade:
Found version: 3.0.0
Current version: 2.0.0+b2990
* Before doing an upgrade, please make sure you have a backup.
* If you have any issues, please refer to the troubleshooting section in the upgrade guide:
  https://redash.io/help-onpremise/maintenance/how-to-upgrade-redash.html
* If the upgrade guide doesn't help, you can ask for help on the forum (https://discuss.redash.io).   

Full CHANGELOG for this release: https://github.com/getredash/redash/blob/master/CHANGELOG.md
Continue with upgrade? (y/n): y
Downloading release tarball...
Unpacking to: redash.3.0.0.b3134...
Changing ownership to redash...
Linking .env file...
Installing new Python packages (if needed)...
Running migrations (if needed)...
Failed running: sudo -u redash bin/run ./manage.py db upgrade
Exit status: 1
Output:
[2018-01-18 09:21:56,172][PID:1565][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2018-01-18 09:21:56,199][PID:1565][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/opt/redash/redash.3.0.0.b3134/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 228, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 201, in load_app
    rv = self.create_app(self)
  File "/opt/redash/redash.3.0.0.b3134/redash/cli/__init__.py", line 15, in create
    app = current_app or create_app()
  File "/opt/redash/redash.3.0.0.b3134/redash/__init__.py", line 134, in create_app
    limiter.init_app(app)
  File "/usr/local/lib/python2.7/dist-packages/flask_limiter/extension.py", line 180, in init_app
    ** self._storage_options
  File "/usr/local/lib/python2.7/dist-packages/limits/storage.py", line 37, in storage_from_string
    return SCHEMES[scheme](storage_string, **options)
  File "/usr/local/lib/python2.7/dist-packages/limits/storage.py", line 373, in __init__
    self.initialize_storage(uri)
  File "/usr/local/lib/python2.7/dist-packages/limits/storage.py", line 377, in initialize_storage
    if not self.storage.ping():
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 682, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by arikfr** [comment]
Check the exception message: looks like Redis having trouble saving to disk. Maybe you ran out of disk space?

Also, GitHub issues are for actionable issues. For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
