### ISSUE TITLE
Python query runner not working in Docker

### ISSUE THREAD

**Issue by giansegato** [getredash/redash#2328]
### Issue Summary

Redash is installed using Docker on an AWS machine. When trying to run this query (basically a hello world):

```
result = {
    "rows": [
        {
            "users": "Hi"
        }
    ],
    "columns": [
        {
            "name": "users",
            "friendly_name": "Users",
            "type": TYPE_STRING,
        }
    ]
}
```

using Python as a data source, this error occurs:

```
worker_1    | [2018-02-20 12:26:02,362][PID:1][INFO][MainProcess] Received task: redash.tasks.execute_query[920e705e-e063-4dfe-86cb-bfe2f8f6f9c2]
worker_1    | [2018-02-20 12:26:02,364][PID:1026][INFO][Worker-1018] task_name=redash.tasks.execute_query taks_id=920e705e-e063-4dfe-86cb-bfe2f8f6f9c2 task=execute_query state=load_ds ds_id=2
worker_1    | [2018-02-20 12:26:02,370][PID:1][INFO][MainProcess] Task redash.tasks.record_event[98d0b8c7-eebb-4e22-8a19-aa8279022552] succeeded in 0.0138372574002s: None
worker_1    | [2018-02-20 12:26:02,371][PID:1026][INFO][Worker-1018] task_name=redash.tasks.execute_query taks_id=920e705e-e063-4dfe-86cb-bfe2f8f6f9c2 task=execute_query state=executing_query query_hash=8f29f155f6870aaa162e10488198cde3 type=python ds_id=2  task_id=920e705e-e063-4dfe-86cb-bfe2f8f6f9c2 queue=queries query_id=9 username=*******
worker_1    | [2018-02-20 12:26:02,375][PID:1][ERROR][MainProcess] Task redash.tasks.execute_query[920e705e-e063-4dfe-86cb-bfe2f8f6f9c2] raised unexpected: AttributeError("'NoneType' object has no attribute 'annotate_query'",)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in call
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in protected_call
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 522, in execute_query
worker_1    |     scheduled_query).run()
worker_1    |   File "/app/redash/tasks/queries.py", line 444, in run
worker_1    |     annotated_query = self._annotate_query(query_runner)
worker_1    |   File "/app/redash/tasks/queries.py", line 485, in _annotate_query
worker_1    |     if query_runner.annotate_query():
worker_1    | AttributeError: 'NoneType' object has no attribute 'annotate_query'
worker_1    | [2018-02-20 12:26:03,327][PID:1][INFO][MainProcess] Received task: redash.tasks.record_event[2dd40d11-529d-4913-8999-1219e08926a8]
worker_1    | [2018-02-20 12:26:03,335][PID:1][INFO][MainProcess] Task redash.tasks.record_event[2dd40d11-529d-4913-8999-1219e08926a8] succeeded in 0.00630740635097s: None
```

As suggested in similar opened issues, we already restarted all the processes (we even restarted the whole machine), and we installed all the dependencies we needed (out of precaution). This doesn't look like fixing the problem.

### Steps to Reproduce

Python was installed adding `redash.query_runner.python` to the `REDASH_ADDITIONAL_QUERY_RUNNERS` environmental variable.

It is correctly being shown as a selectable data source. No `Modules to import prior to running the script` are specified. The user trying to perform the request has admin rights.

**Comment by arikfr** [comment]
Did you apply the configuration update to the worker container too? Did you restart it?

**Comment by giansegato** [comment]
Doing so:

```
echo $REDASH_ADDITIONAL_QUERY_RUNNERS 
```

yields 

```
redash.query_runner.python
```

so it looks like so. We also restarted docker and the machine several times...

**Comment by giansegato** [comment]
We repeated the whole process from scratch, and it magically started working. Thanks a lot and sorry for the duplicated issue. 
Closed.

**Comment by RichardLitt** [comment]
Glad it worked out, @giansegato! No worries.
