### ISSUE TITLE
Beta Image code for Dockerhub

### ISSUE THREAD

**Issue by myoung34** [getredash/redash#2364]
### Issue Summary

Trying to test v4 beta images (from v3) in dockerhub result in errors.
Cant find code to diagnose upgrade from v3 to v4

There are redash images from as recent as 2 days ago, however the `v4.0.0-beta` branch is outdated, and the release page is outdated as well

### Steps to Reproduce

`bin upgrade fails`: 

```
root@b8191f03ed19:/app# bin/upgrade --channel beta                                                                
Starting Redash upgrade:                                                                                   
Found version: 4.0.0-beta                                                                                  
Current version: current                                                                                             
Traceback (most recent call last):                                                                                          
  File "bin/upgrade", line 242, in <module>                                                      
    deploy_release(args.channel)                                                                                        
  File "bin/upgrade", line 220, in deploy_release                                                                               
    verify_minimum_version()                                                                              
  File "bin/upgrade", line 190, in verify_minimum_version                           
    if semver.compare(current_version(), '0.12.0') < 0:                                                              
  File "/usr/local/lib/python2.7/dist-packages/semver.py", line 54, in compare                                              
    v1, v2 = parse(ver1), parse(ver2)                                                                     
  File "/usr/local/lib/python2.7/dist-packages/semver.py", line 21, in parse                       
    raise ValueError('%s is not valid SemVer string' % version)                                                                                                                
ValueError: current is not valid SemVer string      
```

Generating a migration and running it fails:

```
root@b8191f03ed19:/app# gosu redash python manage.py db migrate
[2018-03-02 18:02:11,616][PID:1077][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2018-03-02 18:02:11,639][PID:1077][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[2018-03-02 18:02:13,221][PID:1077][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2018-03-02 18:02:13,222][PID:1077][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2018-03-02 18:02:13,242][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'groups_id_seq' as owned by integer column 'groups(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,285][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'query_snippets_id_seq' as owned by integer column 'query_snippets(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,327][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'data_source_groups_id_seq' as owned by integer column 'data_source_groups(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,369][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'dashboards_id_seq' as owned by integer column 'dashboards(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,393][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'widgets_id_seq' as owned by integer column 'widgets(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,489][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'api_keys_id_seq' as owned by integer column 'api_keys(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,511][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'notification_destinations_id_seq' as owned by integer column 'notification_destinations(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,534][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'alert_subscriptions_id_seq' as owned by integer column 'alert_subscriptions(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,575][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'changes_id_seq' as owned by integer column 'changes(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,597][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'events_id_seq' as owned by integer column 'events(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,619][PID:1077][INFO][alembic.ddl.postgresql] Detected sequence named 'access_permissions_id_seq' as owned by integer column 'access_permissions(id)', assuming SERIAL and omitting
[2018-03-02 18:02:13,663][PID:1077][INFO][alembic.autogenerate.compare] Detected added column 'queries.search_vector'
[2018-03-02 18:02:13,670][PID:1077][INFO][alembic.autogenerate.compare] Detected added index 'ix_queries_search_vector' on '['search_vector']'
[2018-03-02 18:02:13,682][PID:1077][INFO][alembic.autogenerate.compare] Detected added column 'users.profile_image_url'
[2018-03-02 18:02:13,700][PID:1077][INFO][alembic.autogenerate.compare] Detected removed column 'widgets.type'
[2018-03-02 18:02:13,700][PID:1077][INFO][alembic.autogenerate.compare] Detected removed column 'widgets.query_id'
  Generating /app/migrations/versions/879aee43fba6_.py ... done
```

```
root@b8191f03ed19:/app# gosu redash python manage.py db upgrade
[2018-03-02 18:02:18,139][PID:1113][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2018-03-02 18:02:18,162][PID:1113][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
[2018-03-02 18:02:19,811][PID:1113][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2018-03-02 18:02:19,812][PID:1113][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2018-03-02 18:02:19,839][PID:1113][INFO][alembic.runtime.migration] Running upgrade 969126bd800f -> 879aee43fba6, empty message
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_migrate/cli.py", line 132, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python2.7/dist-packages/flask_migrate/__init__.py", line 239, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/879aee43fba6_.py", line 21, in upgrade
    op.add_column('queries', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
NameError: global name 'sqlalchemy_utils' is not defined
```

### Technical details:

* 4.0.0-beta.b3765 installed via docker, upgrading from `:latest`

**Comment by arikfr** [comment]
We now provide "stable" labels for releases: `4.0.0-rc.1` is the latest beta release.

**Comment by arikfr** [comment]
Oops, I followed up on the title but not the content :flushed: 

Your issue is that you try to apply the upgrade script to a Docker image. It's not designed to work this way. `bin/upgrade` is only for instances created with the cloud images (for AWS/GCE). Docker deployments just need to update the Docker image reference and apply migrations (if needed).

**Comment by evralston** [comment]
For anyone else who gets here trying to upgrade a docker install – the step "apply migrations" described above is something like:

1. `docker exec -it CONTAINER_NAME bash`
2. `bin/run ./manage.py db upgrade`
3. probably restart your server and worker containers
