### ISSUE TITLE
LDAP errors if no email is set

### ISSUE THREAD

**Issue by myoung34** [getredash/redash#2365]
### Issue Summary

Redash v3 with LDAP will error if `mail` key is set and ad user does not have an email.

### Steps to Reproduce

1. Set up LDAP plugin and configure
2. Ensure no email on AD user
3. Login

```

2018-03-02 20:33:28,614] ERROR in app: Exception on /ldap/login [POST]
Traceback (most recent call last):
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
  File "/app/redash/authentication/ldap_auth.py", line 39, in login
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    response = self.full_dispatch_request()
    reraise(exc_type, exc_value, tb) 
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.handle_user_exception(e)
[2018-03-02 20:33:28,622][PID:192][INFO][metrics] method=POST path=/ldap/login endpoint=ldap_auth_login status=500 content_type=? content_length=-1 duration=562.71 query_count=0 query_duration=0.00
  File "/app/redash/authentication/ldap_auth.py", line 39, in login
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    response = self.full_dispatch_request()
Traceback (most recent call last):
[2018-03-02 20:33:28,622][PID:192][INFO][werkzeug] 127.0.0.1 - - [02/Mar/2018 20:33:28] "POST /ldap/login HTTP/1.0" 500 -
IndexError: list index out of range
    return self.values[item]
  File "/usr/local/lib/python2.7/dist-packages/ldap3/abstract/attribute.py", line 83, in __getitem__
    create_and_login_user(current_org, user[settings.LDAP_DISPLAY_NAME_KEY][0], user[settings.LDAP_EMAIL_KEY][0])
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
[2018-03-02 20:33:28,614][PID:192][ERROR][redash] Exception on /ldap/login [POST]
IndexError: list index out of range
  File "/usr/local/lib/python2.7/dist-packages/ldap3/abstract/attribute.py", line 83, in __getitem__
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    reraise(exc_type, exc_value, tb) 
    return original_handler(e)
    return self.values[item]
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    rv = self.handle_user_exception(e)
    create_and_login_user(current_org, user[settings.LDAP_DISPLAY_NAME_KEY][0], user[settings.LDAP_EMAIL_KEY][0]) 
```

Expectation: gracefully handle users with no email, such as displaying `n/a`, nothing, etc.
Id like to use email, but Id rather not audit every user with access to redash to ensure it's set.

### Technical details:

* v3.0.0 with ldap monkey patch from #2235 
* Browser/OS: n/a
* How did you install Redash: docker with custom patch to fix 404 route

**Comment by arikfr** [comment]
Email is a mandatory property of a user object. If you don't pass an email property, the same user will be created over and over again, as this is the way we [lookup external users in the local database](https://github.com/getredash/redash/blob/master/redash/authentication/google_oauth.py#L63).

While we don't enforce it to be an actual email address I do see it happen moving forward as we start implementing more features that use the email address of the user.

I'm closing the issue but you're welcome to continue the discussion.
