### ISSUE TITLE
redis ConnectionError on docker

### ISSUE THREAD

**Issue by koooge** [getredash/redash#2368]
### Issue Summary
```
Status: Downloaded newer image for redash/redash:4.0.0-rc.1.b3785
[2018-03-05 01:35:21,730][PID:1][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2018-03-05 01:35:21,760][PID:1][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/app/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/app/redash/__init__.py", line 76, in <module>
    reset_new_version_status()
  File "/app/redash/version_check.py", line 34, in reset_new_version_status
    latest_version = get_latest_version()
  File "/app/ redash/version_check.py", line 40, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```
A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce
docker-compose.yml
```
version: '2'

services:
  server:
    image: redash/redash:4.0.0-rc.1.b3785
    depends_on:
      - postgres
      - redis
    ports:
      - "45000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    command: server
    restart: always
```

```
$ docker-compose run --rm server create_db
```

### Technical details:
* Redash Version: 4.0.0-rc.1.b3785
* Browser/OS:
* How did you install Redash: git clone

I suppose REDASH_REDIS_URL or REDIS_URL has problems

**Comment by levimoore1992** [comment]
Seems like even with down votes you still closed it?

**Comment by susodapop** [comment]
> Seems like even with down votes you still closed it?

Probably not. The issue was closed and commented to on the same day. Nobody at Redash has looked at this since (GH doesn’t notify about reactions). Do you have anything to contribute to the conversation?

**Comment by GoingMyWay** [comment]
Please install `redis-server` by `sudo apt-get install redis-server`. And run `redis-sever` in background.

**Comment by duongkstn** [comment]
yeah, as @GoingMyWay  said, it actually worked

**Comment by paulocr** [comment]
For anyone running into this problem, my solution was to expose port 6379 in the redis service:

```
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"
```

And then mapping the REDIS_URL env variable to "REDASH_REDIS_URL=redis://host.docker.internal:6379/0"
I believe host.docker.internal is exclusive to MacOS and that Linux users could just use localhost.
