### ISSUE TITLE
docker services setup is failing with operand type error

### ISSUE THREAD

**Issue by arivua** [getredash/redash#2563]
### Issue Summary

docker-compose up is failing with operand-type error 
OS: MacOS Sierra v 10.12.6

### Steps to Reproduce

As per docker developer guide (https://redash.io/help/open-source/dev-guide/docker), tried running docker-compose up, but it failed with operand type error.

```
Step 1/8 : FROM redash/base:latest
 ---> 9d04584f371a
Step 2/8 : COPY requirements.txt requirements_dev.txt requirements_all_ds.txt ./
 ---> Using cache
 ---> b30449125f6a
Step 3/8 : RUN pip install -r requirements.txt -r requirements_dev.txt -r requirements_all_ds.txt
 ---> Running in 2d89d8ac9a9d
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 442, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 400, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 545, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 648, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 757, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
ERROR: Service 'server' failed to build: The command '/bin/sh -c pip install -r requirements.txt -r requirements_dev.txt -r requirements_all_ds.txt' returned a non-zero code: 2
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: latest version https://github.com/getredash/redash.git v4.0.1
* Browser/OS: MacOS
* How did you install Redash: docker-compose up
* Node version: 8.10.0 
* npm version: 5.6.0

**Comment by jezdez** [comment]
So this is a pretty annoying issue in how Debian patched pip and its dependencies, see https://github.com/pypa/pip/issues/3943#issuecomment-245306197 and https://github.com/pypa/pip/issues/4779#issuecomment-335945617.

The actual cause for the exception is a failed network connection to PyPI, but there is an inconsistency in Debian's patch to urllib3 that is shipped with pip leads to this misleading error instead of showing a nicer error message. I see that  https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1743886 hasn't been fixed yet, so I think we should reinstall pip using PyPA's installation methods again.

Do you concur @arikfr?

**Comment by arikfr** [comment]
@jezdez sounds good to me. We need to update pip anyway (currently it uses pip 8.0 I think).

The `redash:base` image where we install pip is defined in a [separate repo](https://github.com/getredash/docker/blob/master/base/Dockerfile), but I was thinking of moving it into this repo in a `docker` folder.

**Comment by arikfr** [comment]
We switched to Debian based images long ago.
