### ISSUE TITLE
queries.tag field doesn't exist causing error

### ISSUE THREAD

**Issue by alison985** [getredash/redash#2703]
I pulled the latest getredash/redash:master to my fork. When running `docker-compose up` I get this error:

```
postgres_1  | ERROR:  column queries.tags does not exist at character 840
postgres_1  | STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
postgres_1  | 	FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
postgres_1  | 	WHERE queries.schedule IS NOT NULL ORDER BY queries.id
worker_1    | [2018-07-30 02:57:09,719][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_queries[1b351e55-9f6a-40a2-aba6-155494cef7a3] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column queries.tags does not exist\nLINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...\n                                                             ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 275, in refresh_queries
worker_1    |     for query in models.Query.outdated_queries():
worker_1    |   File "/app/redash/models.py", line 992, in outdated_queries
worker_1    |     for query in queries:
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2797, in __iter__
worker_1    |     return self._execute_and_instances(context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2820, in _execute_and_instances
worker_1    |     result = conn.execute(querycontext.statement, self._params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
worker_1    |     return meth(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
worker_1    |     return connection._execute_clauseelement(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
worker_1    |     compiled_sql, distilled_params
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
worker_1    |     exc_info
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
worker_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
worker_1    |     cursor.execute(statement, parameters)
worker_1    | ProgrammingError: (psycopg2.ProgrammingError) column queries.tags does not exist
worker_1    | LINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...
worker_1    |                                                              ^
```

I have run `docker-compose build` to rebuilding the container, `npm install` cause the package file was touched in the latest changes, `pip install -r requirements.txt` on the local virtualenv just to be sure, and run the test suite (they all pass) but this error still occurs. It seems like it's missing a migration but I can't figure out what command to run in order to run the latest migrations. The migration command is also not listed on this page: https://redash.io/help/open-source/dev-guide/docker 

What is the command to run migrations against the docker container? And is there anything else I should do or think about to resolve this error message?

I'm on Mac OSX 10.13.3 using docker containers.

**Comment by arikfr** [comment]
You need to apply migrations. You can use something like:

```
docker-compose run --rm server manage db upgrade
```

to do it.
