### ISSUE TITLE
upgrade from v4.0.1 to v5.0.1 failed:  column queries.tags does not exist ..

### ISSUE THREAD

**Issue by bltpanda** [getredash/redash#2914]
I pulled the latest redash/redash (default latest) to my fork. When running 
```
docker-compose run --rm server manage db upgrade
docker-compose -f docker-compose.production.yml up 
```

I get this error:
```
worker_1    | [2018-10-09 13:27:56,036][PID:35][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
worker_1    | [2018-10-09 13:27:56,041][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[a489f094-acfb-43fc-9d2e-760ed22636d8]
worker_1    | [2018-10-09 13:27:56,044][PID:16][INFO][Worker-5] task_name=redash.tasks.refresh_queries task_id=a489f094-acfb-43fc-9d2e-760ed22636d8 Refreshing queries...
postgres_1  | ERROR:  column queries.tags does not exist at character 840
postgres_1  | STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
postgres_1  | 	FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
postgres_1  | 	WHERE queries.schedule IS NOT NULL ORDER BY queries.id
worker_1    | [2018-10-09 13:27:56,061][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_queries[a489f094-acfb-43fc-9d2e-760ed22636d8] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column queries.tags does not exist\nLINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...\n                                                             ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 275, in refresh_queries
worker_1    |     for query in models.Query.outdated_queries():
worker_1    |   File "/app/redash/models.py", line 1010, in outdated_queries
worker_1    |     for query in queries:
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
worker_1    |     return self._execute_and_instances(context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
worker_1    |     result = conn.execute(querycontext.statement, self._params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
worker_1    |     return meth(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
worker_1    |     return connection._execute_clauseelement(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
worker_1    |     compiled_sql, distilled_params
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker_1    |     exc_info
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker_1    |     cursor.execute(statement, parameters)
worker_1    | ProgrammingError: (psycopg2.ProgrammingError) column queries.tags does not exist
worker_1    | LINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...
worker_1    |                                                              ^
worker_1    |  [SQL: 'SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at \nFROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id \nWHERE queries.schedule IS NOT NULL ORDER BY queries.id'] (Background on this error at: http://sqlalche.me/e/f405)
worker_1    | [2018-10-09 13:28:26,062][PID:35][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
worker_1    | [2018-10-09 13:28:26,067][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[4f8d5053-728f-4b5e-894c-9fa7aaae73de]
worker_1    | [2018-10-09 13:28:26,071][PID:14][INFO][Worker-3] task_name=redash.tasks.refresh_queries task_id=4f8d5053-728f-4b5e-894c-9fa7aaae73de Refreshing queries...
postgres_1  | ERROR:  column queries.tags does not exist at character 840
postgres_1  | STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
postgres_1  | 	FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
postgres_1  | 	WHERE queries.schedule IS NOT NULL ORDER BY queries.id
worker_1    | [2018-10-09 13:28:26,086][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_queries[4f8d5053-728f-4b5e-894c-9fa7aaae73de] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column queries.tags does not exist\nLINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...\n                                                             ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 275, in refresh_queries
worker_1    |     for query in models.Query.outdated_queries():
worker_1    |   File "/app/redash/models.py", line 1010, in outdated_queries
worker_1    |     for query in queries:
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
worker_1    |     return self._execute_and_instances(context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
worker_1    |     result = conn.execute(querycontext.statement, self._params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
worker_1    |     return meth(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
worker_1    |     return connection._execute_clauseelement(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
worker_1    |     compiled_sql, distilled_params
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
worker_1    |     exc_info
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
worker_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
worker_1    |     cursor.execute(statement, parameters)
worker_1    | ProgrammingError: (psycopg2.ProgrammingError) column queries.tags does not exist
worker_1    | LINE 1: ..., queries.search_vector AS queries_search_vector, queries.ta...
worker_1    |                                                              ^
worker_1    |  [SQL: 'SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at \nFROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id \nWHERE queries.schedule IS NOT NULL ORDER BY queries.id'] (Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by arikfr** [comment]
You ran the db upgrade command with a different Docker Compose configuration (you didn't pass the `-f` flag), which probably resulted in usage of a different database container.

Also in the future, for support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.

**Comment by bltpanda** [comment]
@arikfr I clean the container and run

```
docker-compose -f docker-compose.production.yml run --rm server manage db upgrade
docker-compose -f docker-compose.production.yml up 
```

And then succeed.

Thanks.
