### ISSUE TITLE
[saml] Signature missing for assertion

### ISSUE THREAD

**Issue by rockxsj** [getredash/redash#2977]
### Issue Summary
I want to config redash use keycloak as SAML backend, now I can redirect to keycloak login page and can login success, but when keycloak redirect back to redash, I got error message below：
```
[2018-10-17 11:49:22,787][PID:21][INFO][saml2.response] status: <?xml version='1.0' encoding='UTF-8'?>
<ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
[2018-10-17 11:49:22,788][PID:21][ERROR][saml2.client_base] XML parse error: Signature missing for assertion
[2018-10-17 11:49:22,788][PID:21][ERROR][saml_auth] Failed to parse SAML response
Traceback (most recent call last):
  File "/app/redash/authentication/saml_auth.py", line 73, in idp_initiated
    entity.BINDING_HTTP_POST)
  File "/usr/local/lib/python2.7/dist-packages/saml2/client_base.py", line 702, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saml2/entity.py", line 1170, in _parse_response
    response = response.verify(keys)
  File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 1018, in verify
    if self.parse_assertion(keys):
  File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 930, in parse_assertion
    if not self._assertion(assertion, False):
  File "/usr/local/lib/python2.7/dist-packages/saml2/response.py", line 781, in _assertion
    raise SignatureError("Signature missing for assertion")
SignatureError: Signature missing for assertion
```

My SAML config is something look like this:
SAML Metadata URL
> http://xxx.xxx.xxx.xxx/auth/realms/somerelm/protocol/saml/descriptor

SAML Entity ID
> redash

SAML NameID Format
> urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
### Steps to Reproduce

1. first install latest redash from docker compose
2. config like the config above

### Technical details:

* Redash Version:5.0.0+b4754
* Browser/OS:chrome
* How did you install Redash:docker compose

**Comment by rockxsj** [comment]
I want to contribute some documents for integration keycloak, what should I do?

**Comment by arikfr** [comment]
@rockxsj documentation is always welcomed! The sources of the documentation are in github.com/getredash/website.

**Comment by thiagodiogo** [comment]
Hi, @rockxsj can you share your documentation to integrate to Keycloak, please? 
Thank you so much

**Comment by rockxsj** [comment]
@thiagodiogo Of course!

FIrst, you should make sure keep your SAML enabled, and fill with these values:

SAML Metadata URL
http://your.domain.com/auth/realms/${realmid}/protocol/saml/descriptor

SAML Entity ID
redash

SAML NameID Format
urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress

Second, add a client named redash in keycloak with below configure:
![image](https://user-images.githubusercontent.com/3021207/47399702-6b36e680-d76c-11e8-97ac-08b2334de951.png)
![image](https://user-images.githubusercontent.com/3021207/47399732-81dd3d80-d76c-11e8-94b4-7ae2caeca56c.png)
![image](https://user-images.githubusercontent.com/3021207/47399738-89044b80-d76c-11e8-8680-563934d2ed61.png)
![image](https://user-images.githubusercontent.com/3021207/47399742-8dc8ff80-d76c-11e8-8c43-ff784d5950be.png)
![image](https://user-images.githubusercontent.com/3021207/47399745-93bee080-d76c-11e8-8bf2-d5e141261942.png)


That's all!

**Comment by rockxsj** [comment]
> @rockxsj documentation is always welcomed! The sources of the documentation are in github.com/getredash/website.

Thank's, but the documents project build failed :(   I will make a retry later

**Comment by thiagodiogo** [comment]
Thank you so much @rockxsj ! 
You saved the day here 👍

**Comment by ananthkamath** [comment]
@rockxsj thank you for the above solution

**Comment by iamtodor** [comment]
@arikfr I've submitted PR with this documentation improvement https://github.com/getredash/website/pull/567
and I restyle the doc that was specified by Restyled.io bot
Could you please take a look?
Thanks in advance

**Comment by aksth** [comment]
@rockxsj does this also work as of now?

**Comment by iamtodor** [comment]
@aksth check my blog post with all the details how to configure it: https://iamtodor.medium.com/how-to-configure-saml-login-with-keycloak-on-self-hosted-redash-b41a04e27f

**Comment by aksth** [comment]
@iamtodor Thanks. I had followed just like in that post too, but I'm still getting the same error.
After clicking "SAML Login", the page is directed to "http://localhost:8089/saml/login?next=%2F" and then "It seems like the page you're looking for cannot be found." page, same as above.
Also, in your blog post, if you had shown how to configure SAML Client on the Keycloak, that would have been great.

**Comment by ognjen-it** [comment]
Just to add that I needed to change mappers X500 Surname and X500 GivenName SAML Attribute Name to be the same just like Friendly Name (FirstName and LastName).

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
