### ISSUE TITLE
ImportError: cannot import name close_open_fds

### ISSUE THREAD

**Issue by muk-ai** [getredash/redash#3287]
### Issue Summary

when I upgrade to version `6.0.0`, an error occurs and it got corrupted.
Can anyone help me?

### Steps to Reproduce

```
cd /opt/redash/current
sudo bin/upgrade
```

The output is below.

```
ubuntu@redash:/opt/redash/current$ sudo bin/upgrade
Starting Redash upgrade:
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Found version: 6.0.0
Current version: 5.0.2+b5485
***IMPORTANT: make sure to clear out the Celery queue before upgrading.***

* Before doing an upgrade, please make sure you have a backup.
* If you have any issues, please refer to the troubleshooting section in the upgrade guide:
  https://redash.io/help/open-source/admin-guide/how-to-upgrade
* If the upgrade guide doesn't help, you can ask for help on the forum (https://discuss.redash.io).

Full CHANGELOG for this release: https://github.com/getredash/redash/blob/master/CHANGELOG.md
Continue with upgrade? (y/n): y
Downloading release tarball...
Unpacking to: redash.6.0.0.b8536...
Changing ownership to redash...
Linking .env file...
Installing new Python packages (if needed)...
Running migrations (if needed)...
Failed running: sudo -u redash bin/run ./manage.py db upgrade
Exit status: 1
Output:
Traceback (most recent call last):
  File "/opt/redash/redash.6.0.0.b8536/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/opt/redash/redash.6.0.0.b8536/redash/cli/__init__.py", line 8, in <module>
    from redash.cli import users, groups, database, data_sources, organization
  File "/opt/redash/redash.6.0.0.b8536/redash/cli/users.py", line 11, in <module>
    from redash.handlers.users import invite_user
  File "/opt/redash/redash.6.0.0.b8536/redash/handlers/__init__.py", line 4, in <module>
    from redash.handlers.api import api
  File "/opt/redash/redash.6.0.0.b8536/redash/handlers/api.py", line 6, in <module>
    from redash.handlers.base import org_scoped_rule
  File "/opt/redash/redash.6.0.0.b8536/redash/handlers/base.py", line 9, in <module>
    from redash.authentication import current_org
  File "/opt/redash/redash.6.0.0.b8536/redash/authentication/__init__.py", line 13, in <module>
    from redash.tasks import record_event
  File "/opt/redash/redash.6.0.0.b8536/redash/tasks/__init__.py", line 1, in <module>
    from .general import record_event, version_check, send_mail
  File "/opt/redash/redash.6.0.0.b8536/redash/tasks/general.py", line 3, in <module>
    from celery.utils.log import get_task_logger
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/__init__.py", line 16, in <module>
    from .log import LOG_LEVELS     # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/log.py", line 20, in <module>
    from .term import colored
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/term.py", line 13, in <module>
    from celery.platforms import isatty
  File "/usr/local/lib/python2.7/dist-packages/celery/platforms.py", line 21, in <module>
    from billiard.compat import close_open_fds, get_fdmax
ImportError: cannot import name close_open_fds

ubuntu@redash:/opt/redash/current$
```

### Technical details:

- Current version: 5.0.2+b5485
- Upgrade target version: 6.0.0
- OS: Ubuntu 14.04
- Python: 2.7.6
- How did you install Redash: legacy (not Docker)

**Comment by muk-ai** [comment]
This was a problem in my enviroment. (some packages are broken)
I'm sorry for confusing you.

**Comment by arikfr** [comment]
Thank you for the follow up. In the future please use [the forum](discuss.redash.io) for similar questions. :-)

**Comment by RafaAguilar** [comment]
@muk-ai  could you please share what was missing in your environment?, I have exactly the same issue.
