### ISSUE TITLE
redis error on querying druid datasource

### ISSUE THREAD

**Issue by hey-jude** [getredash/redash#3435]
### Issue Summary

redis error on querying druid datasource.

1. Browser message : "Error running query: unknown error occurred. Please try again later."

2. celery log
```
[2019-02-14 18:43:40,647][PID:22747][ERROR][ForkPoolWorker-3] Task redash.tasks.execute_query[45e7c8c1-a9ca-4cfb-a914-5c0092775a77] raised unexpected: RedisError('ZADD requires an equal number of values and scores',)
Traceback (most recent call last):
  File "/app/puser/.pyenv/versions/2.7.15/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/puser/redash/6.0.0+b13561/redash/worker.py", line 68, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/app/puser/.pyenv/versions/2.7.15/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/puser/redash/6.0.0+b13561/redash/tasks/queries.py", line 548, in execute_query
    scheduled_query).run()
  File "/app/puser/redash/6.0.0+b13561/redash/tasks/queries.py", line 460, in run
    self.tracker.update(started_at=time.time(), state='started')
  File "/app/puser/redash/6.0.0+b13561/redash/tasks/queries.py", line 71, in update
    self.save()
  File "/app/puser/redash/6.0.0+b13561/redash/tasks/queries.py", line 62, in save
    connection.zadd(self._get_list(), {key_name: time.time()})
  File "/app/puser/.pyenv/versions/2.7.15/lib/python2.7/site-packages/redis/client.py", line 1691, in zadd
    raise RedisError("ZADD requires an equal number of "
RedisError: ZADD requires an equal number of values and scores
```

### Steps to Reproduce

1. register druid data source
2. query some sqls.

### Technical details:

* Redash Version: 6.0.0
* Browser/OS: Chrome / Macos High Sierra
* How did you install Redash: on-premise

**Comment by kravets-levko** [comment]
@rauchy Can you take a look please?

**Comment by arikfr** [comment]
Based on the log it looks like you have the wrong version of redis-py installed. Make sure you have the same version as in `requirements.txt`.

**Comment by hey-jude** [comment]
@arikfr Yes, you're right. My version is 2.x.
After upgrade redis-py, error has gone. Thx!
