### ISSUE TITLE
Invalid literal for int() with base 10: '2400000001394133410-0'

### ISSUE THREAD

**Issue by jits1988** [getredash/redash#3615]
Environment:
Docker Image: 7.0.0.b17489
MacOS 10.14.3
Datasource: Apache Drill
S3 Alternative: Minio

Query: SELECT * FROM `minio`.`root`.`file.csv`

Error running query: invalid literal for int() with base 10: '2400000001394133410-0'

This query works on Apache Drill directly.

Error log:
adhoc_worker_1      | [2019-03-21 08:25:27,773][PID:107][WARNING][ForkPoolWorker-1] Unexpected error while running query:
adhoc_worker_1      | Traceback (most recent call last):
adhoc_worker_1      |   File "/app/redash/tasks/queries.py", line 314, in run
adhoc_worker_1      |     data, error = query_runner.run_query(annotated_query, self.user)
adhoc_worker_1      |   File "/app/redash/query_runner/drill.py", line 98, in run_query
adhoc_worker_1      |     results = parse_response(response.json())
adhoc_worker_1      |   File "/app/redash/query_runner/drill.py", line 57, in parse_response
adhoc_worker_1      |     row[key] = convert_type(value, types[key])
adhoc_worker_1      |   File "/app/redash/query_runner/drill.py", line 23, in convert_type
adhoc_worker_1      |     return int(string_value)
adhoc_worker_1      | ValueError: invalid literal for int() with base 10: '2400000001394133410-0'
adhoc_worker_1      | [2019-03-21 08:25:27,774][PID:107][INFO][ForkPoolWorker-1] task_name=redash.tasks.execute_query task_id=8802a944-a279-4c9c-ace1-80bdee06f832 task=execute_query query_hash=0c6f96c7abd228f2d9371e8ec4b3ca02 data_length=None error=[invalid literal for int() with base 10: '2400000001394133410-0']
adhoc_worker_1      | [2019-03-21 08:25:27,792][PID:107][ERROR][ForkPoolWorker-1] Task redash.tasks.execute_query[8802a944-a279-4c9c-ace1-80bdee06f832] raised unexpected: QueryExecutionError(u"invalid literal for int() with base 10: '2400000001394133410-0'",)
adhoc_worker_1      | Traceback (most recent call last):
adhoc_worker_1      |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
adhoc_worker_1      |     R = retval = fun(*args, **kwargs)
adhoc_worker_1      |   File "/app/redash/worker.py", line 64, in __call__
adhoc_worker_1      |     return TaskBase.__call__(self, *args, **kwargs)
adhoc_worker_1      |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
adhoc_worker_1      |     return self.run(*args, **kwargs)
adhoc_worker_1      |   File "/app/redash/tasks/queries.py", line 390, in execute_query
adhoc_worker_1      |     scheduled_query).run()
adhoc_worker_1      |   File "/app/redash/tasks/queries.py", line 333, in run
adhoc_worker_1      |     raise result
adhoc_worker_1      | QueryExecutionError: invalid literal for int() with base 10: '2400000001394133410-0'

**Comment by arikfr** [comment]
The value it quotes `2400000001394133410-0` indeed does not seem as a valid integer value. Is it supposed to be an integer or the query runner miscategorized it?

**Comment by wol4aravio** [comment]
Seems that query runner miscategorized it. I have the same issue for csv file with phone numbers. Some of the phones are given without any additional signs, e.g. '+', '(', '-', and etc., and some - not.

So, there are a mix of values:
- 89991231212
- +7 (999) 123-12-12
- +7 (999) 1231212

Apache Drill cli processes query correctly

**Comment by mattiashem** [comment]
Hi Im not 100 that it affect this error but will write anyway and steal this ticket for doc.

I started redash from helm in a kubernetes cluster and got this error in my logs. And got a 500 from the redash web.
It turns out something was wrong with redis. I used a external redis. So i switch back to the redis in the helm chart.

And now redash works fine.

See the config in my helm values.


```
redis:
    enabled: true
    cluster.enabled: true

#externalRedis: redis://redis:6379/redash
```
