### ISSUE TITLE
On latest redash code, seeing ProgrammingError: (psycopg2.ProgrammingError) column data_sources.options does not exist

### ISSUE THREAD

**Issue by phlash-zero** [getredash/redash#3623]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
Forked redash and built docker image;
note, create_db and user is setup. still see this error 
[2019-03-22 05:01:34,294][PID:1][ERROR][MainProcess] Task redash.tasks.execute_query[96f23ead-81bf-47e9-980d-184eed8c2684] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column data_sources.options does not exist\nLINE 1: ...ces_name, data_sources.type AS data_sources_type, data_sourc...\n                                                             ^\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/redash/worker.py", line 71, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/redash/tasks/queries.py", line 528, in execute_query
    scheduled_query).run()
  File "/app/redash/tasks/queries.py", line 420, in __init__
    self.data_source = self._load_data_source()
  File "/app/redash/tasks/queries.py", line 515, in _load_data_source
    return models.DataSource.query.get(self.data_source_id)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 882, in get
    ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 952, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 247, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2884, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2854, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2925, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2948, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column data_sources.options does not exist
LINE 1: ...ces_name, data_sources.type AS data_sources_type, data_sourc...
                                                             ^
 [SQL: 'SELECT data_sources.id AS data_sources_id, data_sources.org_id AS data_sources_org_id, data_sources.name AS data_sources_name, data_sources.type AS data_sources_type, data_sources.options AS data_sources_options, data_sources.queue_name AS data_sources_queue_name, data_sources.scheduled_queue_name AS data_sources_scheduled_queue_name, data_sources.created_at AS data_sources_created_at \nFROM data_sources \nWHERE data_sources.id = %(param_1)s'] [parameters: {'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 7.0.0.beta-dev
* Browser/OS:
* How did you install Redash:
forked, built image, setup user and datasource.

**Comment by arikfr** [comment]
It looks like your code version is not matching the schema version. You need to make sure you’re using the correct Docker image for all services and that they were restarted. 

For support questions please use the forum: discuss.redash.io. If you still need help with this, please include your Docker compose configuration file and “docker ps” command output.
