### ISSUE TITLE
ImportError: No module named sentry_sdk

### ISSUE THREAD

**Issue by kxiaoba** [getredash/redash#3643]
follow https://redash.io/help/open-source/dev-guide/docker documents.

docker-compose run --rm server create_db

Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 228, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python2.7/dist-packages/flask/cli.py", line 201, in load_app
    rv = self.create_app(self)
  File "/app/redash/cli/__init__.py", line 13, in create
    app = current_app or create_app()
  File "/app/redash/__init__.py", line 106, in create_app
    from redash.utils import sentry
  File "/app/redash/utils/sentry.py", line 1, in <module>
    import sentry_sdk
ImportError: No module named sentry_sdk

**Comment by arikfr** [comment]
Hi!

It looks like you need to rebuild the Docker images (`docker-compose rebuild`).

In the future, for support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.

**Comment by arikfr** [comment]
@gabrieldutra why reopen?
