### ISSUE TITLE
Error on all queries after update redash from v6 to v7

### ISSUE THREAD

**Issue by lab79** [getredash/redash#3690]
```
Error running query: execute_query() takes at most 6 arguments (7 given)
```
log
```
[2019-04-09 12:28:23,523][PID:559][ERROR][ForkPoolWorker-466] Task redash.tasks.execute_query[2b7573fe-8b9b-457f-ad27-3d4c3940a154] raised unexpected: TypeError('execute_query() takes at most 6 arguments (7 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/redash/worker.py", line 64, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
TypeError: execute_query() takes at most 6 arguments (7 given)
```

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. click any query
2. refresh query

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 7
* Browser/OS: any
* How did you install Redash: docker

**Comment by lab79** [comment]
gone after switching to the latest version of docker image
