### ISSUE TITLE
Cannot Connect To Athean DB After Upgrading From V4 To V7

### ISSUE THREAD

**Issue by ilanmoovit** [getredash/redash#3979]
### Issue Summary

Hi,

After upgrading Redash (stand-alone) from V4 to V7 via upgrade script, I have an issue with Athena DB connector.

Redash is running on nginx.

### Steps to Reproduce

1. sudo upgrade
2. sudo service nginx restart
3. Test Athena connection
4. sudo pip install pyathena (latest version)
5. updating requirements_all_ds.txt from git
6. sudo pip install -Iv snowflake-connector-python==1.6.10
7. restating nginx again

this is the error message: 

[2019-07-15 09:13:11,670][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Produced At: 20190715071240Z
[2019-07-15 09:13:11,713][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.connectionpool] "POST / HTTP/1.1" 200 471
[2019-07-15 09:13:11,719][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Certificate is attached in Basic OCSP Response: Certs:

[2019-07-15 09:13:11,721][PID:20972][WARNING][snowflake.connector.ocsp_pyopenssl] Failed to get OCSP response: Attempted "__eq__" operation on ASN.1 schema object. Retrying...1/3 .
[2019-07-15 09:13:11,721][PID:20972][INFO][snowflake.connector.ocsp_pyopenssl] getting OCSP response from remote
[2019-07-15 09:13:11,726][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.util.retry] Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None)
[2019-07-15 09:13:11,726][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.util.retry] Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None)
[2019-07-15 09:13:11,732][PID:20972][INFO][botocore.vendored.requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): 13.224.68.150
[2019-07-15 09:13:11,769][PID:20972][INFO][snowflake.connector.ocsp_pyopenssl] ok
[2019-07-15 09:13:11,770][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Tolerable Validity range for OCSP response: +1296(s)
[2019-07-15 09:13:11,776][PID:20972][INFO][snowflake.connector.ocsp_pyopenssl] ok
[2019-07-15 09:13:11,777][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Tolerable Validity range for OCSP response: +6084(s)
[2019-07-15 09:13:11,780][PID:20972][INFO][snowflake.connector.ocsp_pyopenssl] ok
[2019-07-15 09:13:11,781][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Tolerable Validity range for OCSP response: +6084(s)
[2019-07-15 09:13:11,825][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.connectionpool] "POST / HTTP/1.1" 200 471
[2019-07-15 09:13:11,828][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Certificate is attached in Basic OCSP Response: Certs:

[2019-07-15 09:13:11,828][PID:20972][WARNING][snowflake.connector.ocsp_pyopenssl] Failed to get OCSP response: Attempted "__eq__" operation on ASN.1 schema object. Retrying...2/3 .
[2019-07-15 09:13:11,828][PID:20972][INFO][snowflake.connector.ocsp_pyopenssl] getting OCSP response from remote
[2019-07-15 09:13:11,830][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.util.retry] Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None)
[2019-07-15 09:13:11,830][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.util.retry] Converted retries value: 5 -> Retry(total=5, connect=None, read=None, redirect=None)
[2019-07-15 09:13:11,831][PID:20972][INFO][botocore.vendored.requests.packages.urllib3.connectionpool] Starting new HTTP connection (1): 13.224.68.131
[2019-07-15 09:13:11,963][PID:20972][DEBUG][botocore.vendored.requests.packages.urllib3.connectionpool] "POST / HTTP/1.1" 200 471
[2019-07-15 09:13:11,966][PID:20972][DEBUG][snowflake.connector.ocsp_pyopenssl] Certificate is attached in Basic OCSP Response: Certs:

[2019-07-15 09:13:11,966][PID:20972][WARNING][snowflake.connector.ocsp_pyopenssl] Failed to get OCSP response: Attempted "__eq__" operation on ASN.1 schema object. Retrying...3/3 .
[2019-07-15 09:13:11,976][PID:20972][DEBUG][botocore.endpoint] Exception received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 204, in _get_response
    if handler_response is None:
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/ssl_wrap_socket.py", line 750, in ssl_wrap_socket_with_ocsp
  File "/usr/local/lib/python2.7/dist-packages/snowflake/connector/ocsp_pyopenssl.py", line 1097, in validate
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
PyAsn1Error: Attempted "__eq__" operation on ASN.1 schema object

* Redash Version: 7.0.0+b17535 (15c815fb)
* Browser/OS: chrome/windows 10
* How did you install Redash: with upgrade script

**Comment by arikfr** [comment]
You need to update all the Python packages -- including the ones in `requirements.txt`. In general, I would recommend looking into the option of switching to our Docker deployment, as they will "shield" you from such issues.

Anyway, this is a setup issue and not a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.
