### ISSUE TITLE
Traceback: Failed refreshing schema for JSON data source

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#4198]
### Issue Summary

When running Redash [master branch](https://github.com/getredash/redash/commit/cb144598816e40ddb133e046772da01ce53a41e8) locally on my dev laptop, an unexpected error shows on the Celery console:

```
[2019-09-30 20:08:30,369][PID:5480][WARNING][ForkPoolWorker-3] task_name=redash.tasks.refresh_schema task_id=2e188df7-7abb-4f4e-ac78-b28681bf7865 Failed refreshing schema for the data source: Some JSON
Traceback (most recent call last):
  File "/home/jc/git_repos/redash/redash/redash/tasks/queries.py", line 261, in refresh_schema
    ds.get_schema(refresh=True)
  File "/home/jc/git_repos/redash/redash/redash/models/__init__.py", line 155, in get_schema
    schema = sorted(query_runner.get_schema(get_stats=refresh), key=lambda t: t['name'])
  File "/home/jc/git_repos/redash/redash/redash/query_runner/__init__.py", line 120, in get_schema
    raise NotSupported()
NotSupported
```

The data source it's complaining about ("Some JSON") is literally just a JSON data source with the name defined and nothing else.  

### Steps to Reproduce

1. Install Redash using the [non-Docker setup instructions](https://redash.io/help/open-source/dev-guide/setup)
2. Start Redash as per instructions on the same page
3. Create a JSON data source with the name "Some JSON", with no username nor password

With this done, the traceback will appear from then on a few minutes after Celery is started.

### Technical details:

* Redash Version: git commit cb144598816e40ddb133e046772da01ce53a41e8 (9.0-dev?)
* Browser/OS: Firefox 60.8.0ESR on OpenSUSE Leap 15.x, though it's probably not relevant as is a backend error message.
* How did you install Redash: Using the [non-Docker setup instructions](https://redash.io/help/open-source/dev-guide/setup)

**Comment by nvcnvn** [comment]
```
