### ISSUE TITLE
Getting 500 error while trying to setup redash using docker image redash/redash:7.0.0.b18042

### ISSUE THREAD

**Issue by asharabu** [getredash/redash#4209]
Hi,

I have tried to setup redash using docker image redash/redash:7.0.0.b18042 but getting below error,

![image](https://user-images.githubusercontent.com/42669995/66101720-72e24a80-e5cd-11e9-9ed7-ddd7093297ea.png)

---

getting below error on docker logs,

---

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_limiter/extension.py", line 442, in __inner
    return obj(*a, **k)
  File "/app/redash/handlers/authentication.py", line 143, in login
    if current_org == None and not settings.MULTI_ORG:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 365, in <lambda>
    __eq__ = lambda x, o: x._get_current_object() == o
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/app/redash/authentication/org_resolving.py", line 18, in _get_current_org
    g.org = Organization.get_by_slug(slug)
  File "/app/redash/models/organizations.py", line 33, in get_by_slug
    return cls.query.filter(cls.slug == slug).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) relation "organizations" does not exist
LINE 2: FROM organizations
             ^
 [SQL: 'SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings \nFROM organizations \nWHERE organizations.slug = %(slug_1)s \n LIMIT %(param_1)s'] [parameters: {'slug_1': 'default', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
[2019-10-03 04:48:43,456][PID:9][ERROR][redash] Exception on /login [GET]

----

Please note that As per the document I have used redis, postgres sql as another containers and given below ennviorment for redash container,

-----

    "environment":
    - "PYTHONUNBUFFERED=0"
    - "REDASH_LOG_LEVEL=INFO"
    - "REDASH_REDIS_URL=redis://postgres:6379/0"
    - "REDASH_DATABASE_URL=postgresql://postgres@postgres/postgres"
    - "REDASH_RATELIMIT_ENABLED=false"
----

Please advice is there anything need to append to work redash using redash docker image.

**Comment by asharabu** [comment]
> 👋 @asharabu, we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use [our forum](https://discuss.redash.io) to get help.

---

It seems its a bug.

**Comment by ranbena** [comment]
It could be but usually it’s a misunderstanding or user specific environment related. Recreate this in the forum and we’ll gladly help. If this turns out to be a bug we’ll open an issue for it.

**Comment by ashar-abu** [comment]
Hi,

I am unable to post anything on newly created account https://discuss.redash.io shoing on hold.

My username is ashar.ma
