### ISSUE TITLE
bigquery connection test failed: '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by newlifehejian** [getredash/redash#4363]
I installed the V8 redash on a Centos 7 server. when I tried to create data source with bigquery.
I always got "connection test failed:'<' not supported between instances of 'int' and 'str'", 
I totally followed the instruction of create service account and generate the key file.

please help to check what happened.
on docker logs of server, there are something maybe related:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth

**Comment by newlifehejian** [comment]
isn't it a bug?

**Comment by arikfr** [comment]
It's an automated bot that closes issues tagged as support question.

Also, from the details in your issue it doesn't look like a bug but a setup issue: the v8 codebase is Python 2 only. The master branch is Python 3, but isn't fully tested yet. Actually, the same issue still exists there, but there is an open PR to fix it.
