### ISSUE TITLE
When no outdated queries exists in admin page, the page crashed

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#4767]
### Issue Summary

When no outdated queries exists in admin page, the page crashed

### Steps to Reproduce

1. Click the outdated queries link in the admin page.
![image](https://user-images.githubusercontent.com/8188177/78112941-86ae2280-7431-11ea-9e99-300299b58ec4.png)

2. If there is no outdated queries, the page crashed.
![image](https://user-images.githubusercontent.com/8188177/78112755-42228700-7431-11ea-8959-ca9532dcc370.png)

### Technical details:

* Redash Version: V9
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Hi @myonlylonely! Do you see any errors in browser console?

**Comment by myonlylonely** [comment]
> Hi @myonlylonely! Do you see any errors in browser console?

```
xhr.js:172 GET http://xxx.xxx.xxx.xxx/api/admin/queries/outdated 500 (INTERNAL SERVER ERROR)
(anonymous) @ xhr.js:172
e.exports @ xhr.js:11
e.exports @ dispatchRequest.js:57
Promise.then (async)
l.request @ Axios.js:53
l.<computed> @ Axios.js:68
(anonymous) @ bind.js:9
doRequest @ OutdatedQueries.jsx:156
value @ ItemsFetcher.js:23
value @ ItemsFetcher.js:55
(anonymous) @ ItemsSource.js:46
Promise.then (async)
value @ ItemsSource.js:44
(anonymous) @ ItemsSource.js:137
value @ ItemsList.jsx:92
Ba @ react-dom.production.min.js:216
Wa @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ps @ react-dom.production.min.js:250
Ts @ react-dom.production.min.js:249
As @ react-dom.production.min.js:248
Cs @ react-dom.production.min.js:245
Ja @ react-dom.production.min.js:243
li @ react-dom.production.min.js:157
(anonymous) @ Router.jsx:78
Promise.then (async)
r @ Router.jsx:76
(anonymous) @ Router.jsx:94
(anonymous) @ location.js:22
r @ history.js:155
(anonymous) @ history.js:173
notifyListeners @ history.js:172
E @ history.js:288
(anonymous) @ history.js:369
confirmTransitionTo @ history.js:145
push @ history.js:350
update @ location.js:70
(anonymous) @ navigateTo.js:16
setTimeout (async)
et @ navigateTo.js:9
K_ @ handleNavigationIntent.js:28
ErrorMessage.jsx:37 Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:59)
```

**Comment by kravets-levko** [comment]
Thank you! It helped to understand that problem is on backend :sweat_smile: Do you have an access to backend logs? If yes - there should be an error (and stacktrace) from handler of `/api/admin/queries/outdated` endpoint. It would be really great if you can send us that stacktrace.

If you have no access to backend logs - please open `http://xxx.xxx.xxx.xxx/api/admin/queries/outdated` URL in new tab and send us what you'll see there.

Thank you a lot!

**Comment by myonlylonely** [comment]
> Thank you! It helped to understand that problem is on backend 😅 Do you have an access to backend logs? If yes - there should be an error (and stacktrace) from handler of `/api/admin/queries/outdated` endpoint. It would be really great if you can send us that stacktrace.
> 
> If you have no access to backend logs - please open `http://xxx.xxx.xxx.xxx/api/admin/queries/outdated` URL in new tab and send us what you'll see there.
> 
> Thank you a lot!

I do have access to backend logs. Do you mean container log? Which Docker container should I look into?

**Comment by kravets-levko** [comment]
Yes, I mean container log. You should look into `server` container.

**Comment by myonlylonely** [comment]
> Yes, I mean container log. You should look into `server` container.

```
[2020-04-01 08:40:47,705][PID:8][ERROR][redash.app] Exception on /api/admin/queries/outdated [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/redash/handlers/admin.py", line 39, in outdated_queries
    "updated_at": manager_status["last_refresh_at"],
KeyError: 'last_refresh_at'
[2020-04-01 08:40:47,706][PID:8][INFO][metrics] method=GET path=/api/admin/queries/outdated endpoint=redash_outdated_queries status=500 content_type=text/html content_length=290 duration=3.65 query_count=3 query_duration=3.08
[2020-04-01 08:40:47,707][PID:8][INFO][metrics] method=GET path=/api/admin/queries/outdated endpoint=redash_outdated_queries status=500 content_type=? content_length=-1 duration=4.64 query_count=3 query_duration=3.08
[2020-04-01 08:40:48,689][PID:9][INFO][metrics] method=POST path=/api/events endpoint=events status=200 content_type=application/json content_length=4 duration=1.17 query_count=2 query_duration=2.15
```

**Comment by kravets-levko** [comment]
@rauchy Can you take a look please? Thank you!

**Comment by myonlylonely** [comment]
> @rauchy Can you take a look please? Thank you!

Could this issue cause issue https://github.com/getredash/redash/issues/4764 ?

**Comment by lihan** [comment]
@myonlylonely @kravets-levko Had the same problem,  it's because **RQ worker** was not started. Same cause to https://github.com/getredash/redash/issues/4764

**Comment by myonlylonely** [comment]
> @myonlylonely @kravets-levko Had the same problem, it's because **RQ worker** was not started. Same cause to #4764

I use Docker. I can see both 'redash_scheduler_1' and 'redash_scheduled_worker_' containers are running.
 So I guess that I should modify the docker-compose.yml accordingly? Any suggestions?

**Comment by myonlylonely** [comment]
I managed to make it work. https://github.com/getredash/redash/issues/4764#issuecomment-608231602

**Comment by shapirus** [comment]
I am experiencing the same problem after an update from 9.0.0-beta to current master (dcdff66e6260517e954785bb34da47e565402f1a).

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/redash/handlers/admin.py", line 39, in outdated_queries
    "updated_at": manager_status["last_refresh_at"],
KeyError: 'last_refresh_at'
```

Both the scheduler and worker processes are running.

I have two workers, one has `QUEUES=scheduled_queries,schemas,celery`, another: `QUEUES=queries`.

**Comment by shapirus** [comment]
...it got resolved after some time. The scheduler, however having been started, wasn't working for a while, apparently. Once it began its job, the issue went away.
