### ISSUE TITLE
An UnicodeEncodeError occurs if 'groups list'(cli command) contains UTF-8 names.

### ISSUE THREAD

**Issue by baxs-ishiguro** [getredash/redash#4798]
### Issue Summary

When "manage.py groups list (cli command)" is executed, it will be an UnicodeEncodeError if 'names' contains the character of UTF-8.

### Steps to Reproduce

1.  `docker-compose exec server bash`
2. `./bin/run ./manage.py groups list`

```
Name: XXXXXX
Type: regular
Organization: default
Permissions: [edit_dashboard,execute_query,view_query,list_dashboards]
Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/app/redash/cli/groups.py", line 103, in list
    print("Users: {}".format(", ".join(user_names)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

### Additional

groups.py
```
        print("Users: {}".format(", ".join(user_names)))
```

If this code change to below, it works fine.

```
        user_names = [m.name for m in members]
        for user_name in user_names:
            print("Users: {}".format(user_name.encode('utf-8')))
```

### Technical details:

* Redash Version: 8.0.0+b32245
* OS: AmazonLinux2 (Docker version 18.09.9-ce)
* How did you install Redash: docker image: redash/redash:8.0.0.b32245

**Comment by arikfr** [comment]
Thank you for reporting this. This should be resolved in latest version as we moved to Python 3.

**Comment by baxs-ishiguro** [comment]
OK. Thank you!
