### ISSUE TITLE
Unable to build, :bug: in Dockerfile 

### ISSUE THREAD

**Issue by zachliu** [getredash/redash#4901]
### Issue Summary

Unable to do `docker-compose build`. There are two errors:
* During `apt-get install`: 
```
E: The method driver /usr/lib/apt/methods/https could not be found.
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/dists/buster/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
* During `pip install`
```
Step 23/30 : RUN if [ "x$skip_dev_deps" = "x" ] ; then pip install -r requirements.txt -r requirements_dev.txt; else pip install -r requirements.txt; fi
 ---> Running in 4d81d3ee18d0
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 259, in run
    with self._build_session(options) as session:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 76, in _build_session
    if options.cache_dir else None
  File "/usr/local/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
ERROR: Service 'server' failed to build: The command '/bin/sh -c if [ "x$skip_dev_deps" = "x" ] ; then pip install -r requirements.txt -r requirements_dev.txt; else pip install -r requirements.txt; fi' returned a non-zero code: 2
Makefile:4: recipe for target 'compose_build' failed
make: *** [compose_build] Error 1
```

### Steps to Reproduce

1. Clone the latest master (`a2217cc`)
2. `$ make compose_build`

### Technical details:

* Redash Version: `a2217cc`
* Browser/OS: Mint 19.3 tricia
* How did you install Redash: N/A

### Solution:
1. Need `apt-transport-https ca-certificates` in the `apt-get install` list
2. At this line [here](https://github.com/getredash/redash/blob/a2217cc4ecfa5cd916c934c19a93848284cf984b/Dockerfile#L70), in order to disable pip cache, use `ENV PIP_NO_CACHE_DIR=off` not `ENV PIP_NO_CACHE_DIR=1`. See https://github.com/pypa/pip/issues/2897

**Comment by zachliu** [comment]
i wonder if someone actually did a `make compose_build` after updating the `Dockerfile` :facepalm:
