### ISSUE TITLE
error in running docker image.

### ISSUE THREAD

**Issue by aamir-gmail** [getredash/redash#5034]
docker run -p 5000:5000  redash:1

[2020-07-07 03:17:45 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-07-07 03:17:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2020-07-07 03:17:45 +0000] [1] [INFO] Using worker: sync
[2020-07-07 03:17:45 +0000] [8] [INFO] Booting worker with pid: 8
[2020-07-07 03:17:45 +0000] [9] [INFO] Booting worker with pid: 9
[2020-07-07 03:17:45 +0000] [10] [INFO] Booting worker with pid: 10
[2020-07-07 03:17:45 +0000] [11] [INFO] Booting worker with pid: 11
[2020-07-07 03:18:04,813][PID:11][ERROR][redash.app] Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1944, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
    func()
  File "/app/redash/version_check.py", line 96, in reset_new_version_status
    latest_version = get_latest_version()
  File "/app/redash/version_check.py", line 102, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
[2020-07-07 03:18:05,133][PID:10][ERROR][redash.app] Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1944, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1992, in try_trigger_before_first_request_functions
    func()
  File "/app/redash/version_check.py", line 96, in reset_new_version_status
    latest_version = get_latest_version()
  File "/app/redash/version_check.py", line 102, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

**Comment by FutureSenzhong** [comment]
redis addr is error

**Comment by gabrieldutra** [comment]
It seems you're running Docker directly, and due to that some resources (like Redis) are not available, you can refer to [this](https://redash.io/help/open-source/setup#docker). The Setup Script uses docker-compose, which includes all services needed to run Redash. If you have further questions I suggest you to use the [forum](https://discuss.redash.io) as we use GitHub mostly for bug tracking and the forum has more activity from the community.

Thanks!
