### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by langchao209** [getredash/redash#5131]
> redash-client@9.0.0-beta build /opt/redash
> npm run clean && npm run build:viz && NODE_ENV=production webpack

> redash-client@9.0.0-beta clean /opt/redash
> rm -rf ./client/dist/

> redash-client@9.0.0-beta build:viz /opt/redash
> (cd viz-lib && npm run build:babel)

> @redash/viz@0.1.1 build:babel /opt/redash/viz-lib
> babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored

{ Error: Cannot find module 'babel-plugin-module-resolver' from '/opt/redash/viz-lib'
    at Function.resolveSync [as sync] (/opt/redash/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/opt/redash/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/opt/redash/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/opt/redash/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/opt/redash/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/opt/redash/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/opt/redash/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/opt/redash/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/opt/redash/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by gabrieldutra** [comment]
Check if `npm run postinstall` (or `npm install`) before helps. Currently there are some issues and after installing any different package it's necessary to run `npm run postinstall` again 😕.

If after that the problem persists, you can create a post in the [forum](https://discuss.redash.io) as we try to keep GH issues for bugs 🙂.
