### ISSUE TITLE
when create datasourc get error message -TypeError: unhashable type: 'DataSource'

### ISSUE THREAD

**Issue by jackyu3061** [getredash/redash#5157]
### Issue Summary

[2020-09-09 14:42:34,027] ERROR in app: Exception on /api/data_sources [POST]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/python3/lib/python3.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/redash/redash-8.0.0/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/redash/redash-8.0.0/redash/permissions.py", line 67, in decorated
    return fn(*args, **kwargs)
  File "/opt/redash/redash-8.0.0/redash/handlers/data_sources.py", line 133, in post
    options=config)
  File "/opt/redash/redash-8.0.0/redash/models/__init__.py", line 117, in create_with_group
    data_source = cls(*args, **kwargs)
  File "<string>", line 4, in __init__
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 747, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in set
    value, old, initiator)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/ext/mutable.py", line 497, in set
    value._parents[target.obj()] = key
  File "/usr/local/python3/lib/python3.7/weakref.py", line 409, in __setitem__
    self.data[ref(key, self._remove)] = value
TypeError: unhashable type: 'DataSource'

### Steps to Reproduce
When Create a New Data Source (such as mysql,hive,eg..), get the mesaage"TypeError: unhashable type: 'DataSource'" in log;
### Technical details:
os : centos
python: 3.7.4
redash :v8.0.0.0
Developer Installation,not docker

**Comment by 1420963371** [comment]
**I have the same problem,but I don't know how to solve it.**

os : windwos 10
python: 3.9.8
redash :v8.0.0.0
Developer Installation,not docker

File "/usr/local/python3/lib/python3.7/weakref.py", line 409, in setitem
self.data[ref(key, self._remove)] = value
TypeError: unhashable type: 'DataSource'

**Comment by guidopetri** [comment]
@jackyu3061 @1420963371 , could you provide more detailed information on how you set up redash? Is this still an issue with the latest `preview` image on dockerhub?
