### ISSUE TITLE
Internal Error on Query 

### ISSUE THREAD

**Issue by phupt26** [getredash/redash#5162]
###  In Summary

My dashboard sometimes gets an error such as "Internal Server Error". I checked that because of my query didn't run properly because it seemed to get an existing job from redis . I check the log of redash-server, it said:

redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    | [2020-09-10 13:22:32,935][PID:10][INFO][root] [e2ad152be111aa4f1af46b486ab845ed] Found existing job: afcd0b79-79a6-4659-ac37-6f7bcb2ee67d
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    | [2020-09-10 13:22:32,936] ERROR in app: Exception on /api/queries/2/results [POST]
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    | Traceback (most recent call last):
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     rv = self.dispatch_request()
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self.view_functions[rule.endpoint](**req.view_args)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     resp = resource(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return func(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self.dispatch_request(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/handlers/base.py", line 31, in dispatch_request
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return super(BaseResource, self).dispatch_request(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     resp = meth(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/permissions.py", line 67, in decorated
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return fn(*args, **kwargs)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/handlers/query_results.py", line 197, in post
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return run_query(query.parameterized, parameter_values, query.data_source, query_id, max_age)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/handlers/query_results.py", line 68, in run_query
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     "Query ID": query_id
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/tasks/queries.py", line 117, in enqueue_query
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     if job.ready():
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/app/redash/tasks/queries.py", line 93, in ready
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self._async_result.ready()
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 313, in ready
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self.state in self.backend.READY_STATES
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 473, in state
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self._get_task_meta()['status']
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 412, in _get_task_meta
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self._maybe_set_cache(self.backend.get_task_meta(self.id))
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 386, in get_task_meta
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     meta = self._get_task_meta_for(task_id)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 730, in _get_task_meta_for
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self.decode_result(meta)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 305, in decode_result
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     return self.meta_from_decoded(self.decode(payload))
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 301, in meta_from_decoded
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     meta['result'] = self.exception_to_python(meta['result'])
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |   File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 281, in exception_to_python
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    |     exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
redash_server.1.2hwzhqu1i1jr@zoop-infra-server-04    | TypeError: __init__() takes at least 4 arguments (2 given)

So when i cleared the redis data , it worked normally.
Currently i set the schedules for my query in every 5 minutes . It ran well until i had gotten that issue.

Anyone can help me ?
### Steps to Reproduce

**1. I setup via this link https://github.com/getredash/setup . But i ran all of them in Docker Swarm with the docker-compose.yml**
version: "3.8"
networks:
  da: { external: true }

volumes:
  redashmongo:
  postgredata:

configs:
  syncDB:
    file: ./scripts/syncDB.sh
  mongo:
    file: ./scripts/mongo.sh
  mongoConvert:
    file: ./scripts/mongoConvert-DA.sh

x-redash-service: &redash-service
  image: redash/redash:8.0.2.b37747
  networks:
    - da
  depends_on:
    - postgres
    - redis-redash
  env_file: ./env
  restart: always
  deploy:
    placement:
      constraints:
        - node.labels.infra-4 == true

services:
  server:
    <<: *redash-service
    command: 
      - server
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2  

  redis-redash:
    image: redis:5.0-alpine
    networks:
      - da
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.infra-4 == true

  postgres:
    image: postgres:9.6-alpine
    networks:
      - da
    env_file: ./env
    volumes:
      - postgredata:/var/lib/postgresql/data
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.infra-1 == true

  mongoda:
    image: mongo
    volumes:
      - redashmongo:/data/db
      - "/etc/localtime:/etc/localtime:ro"
    configs:
      - source: syncDB
        target: /data/syncDB.sh
        mode: 0755
      - source: mongo
        target: /data/mongo.sh
        mode: 0755
      - source: mongoConvert
        target: /data/mongoConvert-DA.sh
        mode: 0755
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.labels.infra-1 == true]
    networks:
      - da

**2.  The datasource is mongodb which i import my data in hour.**

**3. This is my first query**
{
    "collection" : "reporting"
}

**4. This is my second query and i draw my dashboard from here**
select * from query_1 where reportdate=(select max(reportdate) from query_1);

### Technical details:

* Redash Version: redash/redash:8.0.2.b37747
* Browser/OS: Ubuntu 18.04.5 LTS
* How did you install Redash: Docker Swarm Stack with docker-compose.yml above

**Comment by phupt26** [comment]
Linked to this [link](https://discuss.redash.io/t/internal-server-error-operationalerror-server-closed-the-connection-unexpectedly-on-sql-select-from-organizations/5613) to fix this issue
