### ISSUE TITLE
Redash V9 beta version workers are crashing due to TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by pallavisharma0508** [getredash/redash#5183]
### Issue Summary
Hi , I am using Self Hosted Redash V9 Beta version 
Worker is existing due to 

Error: monitor_work_horse() takes 2 positional arguments but 3 were given | TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given
-- | --
**Below is the log:** 
2020-09-18T15:52:15.157-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 549, in work
-- | --
  | 2020-09-18T15:52:15.157-07:00 | self.execute_job(job, queue)
  | 2020-09-18T15:52:15.157-07:00 | File "/opt/amazon/lib/python3.7/site-packages/redash/tasks/worker.py", line 54, in execute_job
  | 2020-09-18T15:52:15.157-07:00 | super().execute_job(job, queue)
  | 2020-09-18T15:52:15.157-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 774, in execute_job
  | 2020-09-18T15:52:15.157-07:00 | self.monitor_work_horse(job, queue)
  | 2020-09-18T15:52:15.157-07:00 | TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given
  | 2020-09-18T15:52:15.161-07:00 | [2020-09-18 22:52:15,161][PID:999][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Refreshing queries...
  | 2020-09-18T15:52:15.224-07:00 | [2020-09-18 22:52:15,224][PID:999][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Done refreshing queries: {'outdated_queries_count': 0, 'last_refresh_at': 1600469535.2234628, 'query_ids': '[]'}
  | 2020-09-18T15:52:15.227-07:00 | [2020-09-18 22:52:15,227][PID:999][INFO][rq.worker] periodic: Job OK (372a63e24ac68e3028079685c6c1e8e1a38b9420)
  | 2020-09-18T15:52:15.228-07:00 | [2020-09-18 22:52:15,227][PID:999][INFO][rq.worker] Result is kept for 600 seconds
  | 2020-09-18T15:52:15.437-07:00 | 2020-09-18 22:52:15,437 INFO exited: worker-3 (exit status 0; expected)
  | 2020-09-18T15:52:15.437-07:00 | 2020-09-18 22:52:15,437 INFO reaped unknown pid 999
  | 2020-09-18T15:52:16.441-07:00 | 2020-09-18 22:52:16,440 INFO spawned: 'worker-3' with pid 1000
  | 2020-09-18T15:52:17.442-07:00 | 2020-09-18 22:52:17,442 INFO success: worker-3 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  | 2020-09-18T15:52:18.416-07:00 | [2020-09-18 22:52:18,416][PID:1000][INFO][rq.worker] Worker rq:worker:792f478c94c4418ab3c02ddd6de17f4e: started, version 1.5.1
  | 2020-09-18T15:52:18.417-07:00 | [2020-09-18 22:52:18,417][PID:1000][INFO][rq.worker] *** Listening on scheduled_queries, queries, periodic, emails, default, schemas...
  | 2020-09-18T15:52:45.170-07:00 | [2020-09-18 22:52:45,170][PID:963][INFO][rq.worker] periodic: 372a63e24ac68e3028079685c6c1e8e1a38b9420
  | 2020-09-18T15:52:45.175-07:00 | [2020-09-18 22:52:45,174][PID:975][INFO][rq.worker] periodic: c33b2b69cac2aa765fa2d2eb42301a0fc1ae774c
  | 2020-09-18T15:52:45.178-07:00 | [2020-09-18 22:52:45,176][PID:963][ERROR][rq.worker] Worker rq:worker:542fbd8363134a51b8fba9b38689c6ae: found an unhandled exception, quitting...
  | 2020-09-18T15:52:45.178-07:00 | Traceback (most recent call last):
  | 2020-09-18T15:52:45.178-07:00Copy  File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 549, in work | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 549, in work
  | 2020-09-18T15:52:45.178-07:00 | self.execute_job(job, queue)
  | 2020-09-18T15:52:45.178-07:00 | File "/opt/amazon/lib/python3.7/site-packages/redash/tasks/worker.py", line 54, in execute_job
  | 2020-09-18T15:52:45.178-07:00 | super().execute_job(job, queue)
  | 2020-09-18T15:52:45.178-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 774, in execute_job
  | 2020-09-18T15:52:45.178-07:00 | self.monitor_work_horse(job, queue)
  | 2020-09-18T15:52:45.178-07:00CopyTypeError: monitor_work_horse() takes 2 positional arguments but 3 were given | TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given
  | 2020-09-18T15:52:45.182-07:00Copy[2020-09-18 22:52:45,180][PID:975][ERROR][rq.worker] Worker rq:worker:eb381724bf6e4212a709366d30d1e0ec: found an unhandled exception, quitting... | [2020-09-18 22:52:45,180][PID:975][ERROR][rq.worker] Worker rq:worker:eb381724bf6e4212a709366d30d1e0ec: found an unhandled exception, quitting...
  | 2020-09-18T15:52:45.182-07:00 | Traceback (most recent call last):
  | 2020-09-18T15:52:45.182-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 549, in work
  | 2020-09-18T15:52:45.182-07:00 | self.execute_job(job, queue)
  | 2020-09-18T15:52:45.182-07:00 | File "/opt/amazon/lib/python3.7/site-packages/redash/tasks/worker.py", line 54, in execute_job
  | 2020-09-18T15:52:45.182-07:00 | super().execute_job(job, queue)
  | 2020-09-18T15:52:45.182-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 774, in execute_job
  | 2020-09-18T15:52:45.182-07:00 | self.monitor_work_horse(job, queue)
  | 2020-09-18T15:52:45.182-07:00CopyTypeError: monitor_work_horse() takes 2 positional arguments but 3 were given | TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given
  | 2020-09-18T15:52:45.183-07:00Copy[2020-09-18 22:52:45,183][PID:1010][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Refreshing queries... | [2020-09-18 22:52:45,183][PID:1010][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Refreshing queries...
  | 2020-09-18T15:52:45.209-07:00 | [2020-09-18 22:52:45,208][PID:1011][INFO][rq.worker] periodic: Job OK (c33b2b69cac2aa765fa2d2eb42301a0fc1ae774c)
  | 2020-09-18T15:52:45.210-07:00 | [2020-09-18 22:52:45,209][PID:1011][INFO][rq.worker] Result is kept for 120 seconds
  | 2020-09-18T15:52:45.283-07:00Copy[2020-09-18 22:52:45,282][PID:1010][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Done refreshing queries: {'outdated_queries_count': 0, 'last_refresh_at': 1600469565.281791, 'query_ids': '[]'} | [2020-09-18 22:52:45,282][PID:1010][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Done refreshing queries: {'outdated_queries_count': 0, 'last_refresh_at': 1600469565.281791, 'query_ids': '[]'}
  | 2020-09-18T15:52:45.286-07:00 | [2020-09-18 22:52:45,286][PID:1010][INFO][rq.worker] periodic: Job OK (372a63e24ac68e3028079685c6c1e8e1a38b9420)
  | 2020-09-18T15:52:45.287-07:00 | [2020-09-18 22:52:45,286][PID:1010][INFO][rq.worker] Result is kept for 600 seconds
  | 2020-09-18T15:52:45.534-07:00 | 2020-09-18 22:52:45,534 INFO exited: worker-2 (exit status 0; expected)
  | 2020-09-18T15:52:45.534-07:00 | 2020-09-18 22:52:45,534 INFO reaped unknown pid 1010
  | 2020-09-18T15:52:45.534-07:00 | 2020-09-18 22:52:45,534 INFO exited: worker-1 (exit status 0; expected)
  | 2020-09-18T15:52:45.534-07:00 | 2020-09-18 22:52:45,534 INFO reaped unknown pid 1011
  | 2020-09-18T15:52:45.536-07:00 | 2020-09-18 22:52:45,536 INFO spawned: 'worker-1' with pid 1012
  | 2020-09-18T15:52:45.539-07:00 | 2020-09-18 22:52:45,538 INFO spawned: 'worker-2' with pid 1013
  | 2020-09-18T15:52:46.541-07:00 | 2020-09-18 22:52:46,540 INFO success: worker-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  | 2020-09-18T15:52:46.541-07:00 | 2020-09-18 22:52:46,541 INFO success: worker-2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  | 2020-09-18T15:52:47.563-07:00 | [2020-09-18 22:52:47,563][PID:1012][INFO][rq.worker] Worker rq:worker:b3de284ced4e4915a9ab2e5c8bfb966b: started, version 1.5.1
  | 2020-09-18T15:52:47.564-07:00 | [2020-09-18 22:52:47,564][PID:1012][INFO][rq.worker] *** Listening on scheduled_queries, queries, periodic, emails, default, schemas...
  | 2020-09-18T15:52:47.572-07:00 | [2020-09-18 22:52:47,572][PID:1013][INFO][rq.worker] Worker rq:worker:23e33ea68fa240d99f31dccb0c0626a5: started, version 1.5.1
  | 2020-09-18T15:52:47.573-07:00 | [2020-09-18 22:52:47,573][PID:1013][INFO][rq.worker] *** Listening on scheduled_queries, queries, periodic, emails, default, schemas...
  | 2020-09-18T15:53:01.593-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] Received TICK_60 event from supervisor
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] Performing `RQ Worker Healthcheck` check for process name worker-0
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] `RQ Worker Healthcheck` check succeeded for process worker-0
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] Performing `RQ Worker Healthcheck` check for process name worker-1
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] `RQ Worker Healthcheck` check succeeded for process worker-1
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] Performing `RQ Worker Healthcheck` check for process name worker-2
  | 2020-09-18T15:53:01.596-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] `RQ Worker Healthcheck` check succeeded for process worker-2
  | 2020-09-18T15:53:01.597-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] Performing `RQ Worker Healthcheck` check for process name worker-3
  | 2020-09-18T15:53:01.597-07:00 | 2020/09/18 22:53:01 [worker_healthcheck] `RQ Worker Healthcheck` check succeeded for process worker-3
  | 2020-09-18T15:53:01.597-07:00 | RESULT 2
  | 2020-09-18T15:53:01.597-07:00 | OKREADY
  | 2020-09-18T15:53:15.192-07:00 | [2020-09-18 22:53:15,192][PID:985][INFO][rq.worker] periodic: 372a63e24ac68e3028079685c6c1e8e1a38b9420
  | 2020-09-18T15:53:15.199-07:00 | [2020-09-18 22:53:15,197][PID:985][ERROR][rq.worker] Worker rq:worker:af5363ed88294a1a9147efdea611190e: found an unhandled exception, quitting...
  | 2020-09-18T15:53:15.199-07:00 | Traceback (most recent call last):
  | 2020-09-18T15:53:15.199-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 549, in work
  | 2020-09-18T15:53:15.199-07:00 | self.execute_job(job, queue)
  | 2020-09-18T15:53:15.199-07:00 | File "/opt/amazon/lib/python3.7/site-packages/redash/tasks/worker.py", line 54, in execute_job
  | 2020-09-18T15:53:15.199-07:00 | super().execute_job(job, queue)
  | 2020-09-18T15:53:15.199-07:00 | File "/opt/amazon/lib/python3.7/site-packages/rq/worker.py", line 774, in execute_job
  | 2020-09-18T15:53:15.199-07:00 | self.monitor_work_horse(job, queue)
  | 2020-09-18T15:53:15.199-07:00 | TypeError: monitor_work_horse() takes 2 positional arguments but 3 were given
  | 2020-09-18T15:53:15.203-07:00 | [2020-09-18 22:53:15,203][PID:1036][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Refreshing queries...
  | 2020-09-18T15:53:15.291-07:00 | [2020-09-18 22:53:15,290][PID:1036][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_queries job.id=372a63e24ac68e3028079685c6c1e8e1a38b9420 Done refreshing queries: {'outdated_queries_count': 0, 'last_refresh_at': 1600469595.2895775, 'query_ids': '[]'}
  | 2020-09-18T15:53:15.293-07:00 | [2020-09-18 22:53:15,293][PID:1036][INFO][rq.worker] periodic: Job OK (372a63e24ac68e3028079685c6c1e8e1a38b9420)
  | 2020-09-18T15:53:15.294-07:00 | [2020-09-18 22:53:15,293][PID:1036][INFO][rq.worker] Result is kept for 600 seconds
  | 2020-09-18T15:53:15.487-07:00 | 2020-09-18 22:53:15,487 INFO exited: worker-0 (exit status 0; expected)
  | 2020-09-18T15:53:15.487-07:00 | 2020-09-18 22:53:15,487 INFO reaped unknown pid 1036
  | 2020-09-18T15:53:16.490-07:00 | 2020-09-18 22:53:16,490 INFO spawned: 'worker-0' with pid 1037
  | 2020-09-18T15:53:17.492-07:00 | 2020-09-18 22:53:17,492 INFO success: worker-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  | 2020-09-18T15:53:18.468-07:00Copy[2020-09-18 22:53:18,468][PID:1037][INFO][rq.worker] Worker rq:worker:5e437eca927b402fbe87dcf70ae57f47: started, version 1.5.1 | [2020-09-18 22:53:18,468][PID:1037][INFO][rq.worker] Worker rq:worker:5e437eca927b402fbe87dcf70ae57f47: started, version 1.5.1
  | 2020-09-18T15:53:18.469-07:00Copy[2020-09-18 22:53:18,469][PID:1037][INFO][rq.worker] *** Listening on scheduled_queries, queries, periodic, emails, default, schemas... | [2020-09-18 22:53:18,469][PID:1037][INFO][rq.worker] *** Listening on scheduled_queries, queries, periodic, emails, default, schemas...

### Steps to Reproduce
Not sure 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
Workers are crashing because of this.

### Technical details:

* Redash Version:  V9 Beta 
* Browser/OS:
* How did you install Redash: Self Hosted on ECS and Fargate

**Comment by tim5go** [comment]
@pallavisharma0508 
The error occurs because you're using the wrong version `rq`.
You should be using version `1.1` not the latest one.

<img width="1390" alt="Screenshot 2020-09-19 at 6 03 08 PM" src="https://user-images.githubusercontent.com/12296820/93664577-9afae000-faa2-11ea-8e23-f553616e0ff6.png">

I do a code diff between the latest version of `rq` and version `1.1`

Clearly, `rq` introduced a new argument in their function **monitor_work_horse** which breaks `Redash`
