### ISSUE TITLE
Running npn install { Error: Cannot find module 'babel-plugin-module-resolver' from '/root/redash/viz-lib'

### ISSUE THREAD

**Issue by priteshbhole** [getredash/redash#5269]
HI running npm install gives { Error: Cannot find module 'babel-plugin-module-resolver' from '/root/redash/viz-lib'
following is the log
```
{ Error: Cannot find module 'babel-plugin-module-resolver' from '/root/redash/viz-lib'
    at Function.module.exports [as sync] (/root/redash/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/root/redash/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/root/redash/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/root/redash/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/root/redash/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/root/redash/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/root/redash/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/root/redash/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/root/redash/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @redash/viz@0.1.1 build:babel: `babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @redash/viz@0.1.1 build:babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T11_08_44_847Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@9.0.0-beta build:viz: `(cd viz-lib && npm run build:babel)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build:viz script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T11_08_44_861Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@9.0.0-beta build: `npm run clean && npm run build:viz && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T11_08_44_879Z-debug.log```

**Comment by kravets-levko** [comment]
Hi! Which npm version do you use? If you're using npm@7 - try to roll back to npm@6

**Comment by priteshbhole** [comment]
HI 
So I was running with v10.21.0 that gave the above error downgrading to 6.14.4 give below 

```npm ERR! Linux 4.18.0-193.14.2.el8_2.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.14.4/bin/node" "/root/.nvm/versions/node/v6.14.4/bin/npm" "install"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/redash-ldap/npm-debug.log```

**Comment by priteshbhole** [comment]
This is the package.json in case needed

```{
  "name": "redash-client",
  "version": "9.0.0-beta",
  "description": "The frontend part of Redash.",
  "main": "index.js",
  "scripts": {
    "start": "npm-run-all --parallel watch:viz webpack-dev-server",
    "bundle": "bin/bundle-extensions",
    "clean": "rm -rf ./client/dist/",
    "build:viz": "(cd viz-lib && npm run build:babel)",
    "build": "npm run clean && npm run build:viz && NODE_ENV=production webpack",
    "build:old-node-version": "npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack",
    "watch:app": "webpack --watch --progress --colors -d",
    "watch:viz": "(cd viz-lib && npm run watch:babel)",
    "watch": "npm-run-all --parallel watch:*",
    "webpack-dev-server": "webpack-dev-server",
    "analyze": "npm run clean && BUNDLE_ANALYZER=on webpack",
    "analyze:build": "npm run clean && NODE_ENV=production BUNDLE_ANALYZER=on webpack",
    "lint": "npm run lint:base -- --ext .js --ext .jsx --ext .ts --ext .tsx ./client",
    "lint:fix": "npm run lint:base  -- --fix --ext .js --ext .jsx --ext .ts --ext .tsx ./client",
    "lint:base": "eslint --config ./client/.eslintrc.js --ignore-path ./client/.eslintignore",
    "lint:ci": "npm run lint -- --max-warnings 0 --format junit --output-file /tmp/test-results/eslint/results.xml",
    "prettier": "prettier --write 'client/app/**/*.{js,jsx,ts,tsx}' 'client/cypress/**/*.{js,jsx,ts,tsx}'",
    "type-check": "tsc --noEmit --project client/tsconfig.json",
    "type-check:watch": "npm run type-check -- --watch",
    "jest": "TZ=Africa/Khartoum jest",
    "test": "run-s type-check jest",
    "test:watch": "jest --watch",
    "cypress": "node client/cypress/cypress.js",
    "postinstall": "(cd viz-lib && npm ci && npm run build:babel)"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/getredash/redash.git"
  },
  "engines": {
    "node": "^12.0.0",
    "npm": "^6.0.0"
  },
  "author": "Redash Contributors",
  "license": "BSD-2-Clause",
  "bugs": {
    "url": "https://github.com/getredash/redash/issues"
  },
  "homepage": "https://redash.io/",
  "dependencies": {
    "@ant-design/icons": "^4.2.1",
    "@redash/viz": "file:viz-lib",
    "ace-builds": "^1.4.12",
    "antd": "^4.4.3",
    "axios": "^0.19.0",
    "axios-auth-refresh": "^3.0.0",
    "bootstrap": "^3.3.7",
    "classnames": "^2.2.6",
    "d3": "^3.5.17",
    "debug": "^3.1.0",
    "dompurify": "^2.0.7",
    "font-awesome": "^4.7.0",
    "history": "^4.10.1",
    "hoist-non-react-statics": "^3.3.0",
    "markdown": "0.5.0",
    "material-design-iconic-font": "^2.2.0",
    "moment": "^2.19.3",
    "mousetrap": "^1.6.1",
    "mustache": "^2.3.0",
    "numeral": "^2.0.6",
    "path-to-regexp": "^3.1.0",
    "prop-types": "^15.6.1",
    "query-string": "^6.9.0",
    "react": "^16.13.1",
    "react-ace": "^9.1.1",
    "react-dom": "^16.13.1",
    "react-grid-layout": "^0.18.2",
    "react-resizable": "^1.10.1",
    "react-virtualized": "^9.21.2",
    "sql-formatter": "git+https://github.com/getredash/sql-formatter.git",
    "universal-router": "^8.3.0",
    "use-debounce": "^3.1.0",
    "use-media": "^1.4.0"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.4",
    "@babel/core": "^7.10.4",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-transform-object-assign": "^7.2.0",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.10.4",
    "@cypress/code-coverage": "^3.8.1",
    "@percy/agent": "0.24.3",
    "@percy/cypress": "^2.3.2",
    "@types/classnames": "^2.2.10",
    "@types/hoist-non-react-statics": "^3.3.1",
    "@types/lodash": "^4.14.157",
    "@types/prop-types": "^15.7.3",
    "@types/react": "^16.9.41",
    "@types/react-dom": "^16.9.8",
    "@types/sql-formatter": "^2.3.0",
    "@typescript-eslint/eslint-plugin": "^2.10.0",
    "@typescript-eslint/parser": "^2.10.0",
    "atob": "^2.1.2",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.1.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-istanbul": "^6.0.0",
    "babel-plugin-transform-builtin-extend": "^1.1.2",
    "copy-webpack-plugin": "^4.5.3",
    "css-loader": "^0.28.7",
    "cypress": "^5.3.0",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "enzyme-to-json": "^3.3.5",
    "eslint": "^6.7.2",
    "eslint-config-prettier": "^6.7.0",
    "eslint-config-react-app": "^5.1.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-chai-friendly": "^0.5.0",
    "eslint-plugin-compat": "^3.3.0",
    "eslint-plugin-cypress": "^2.0.1",
    "eslint-plugin-flowtype": "^3.13.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jest": "^22.2.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-no-only-tests": "^2.4.0",
    "eslint-plugin-react": "^7.17.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "file-loader": "^2.0.0",
    "html-webpack-plugin": "^3.2.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^24.1.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "less-plugin-autoprefix": "^1.5.1",
    "lodash": "^4.17.20",
    "mini-css-extract-plugin": "^0.4.4",
    "mockdate": "^2.0.2",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.19.1",
    "raw-loader": "^0.5.1",
    "react-test-renderer": "^16.5.2",
    "request": "^2.88.0",
    "request-cookies": "^1.1.0",
    "typescript": "^3.9.6",
    "url-loader": "^1.1.2",
    "webpack": "^4.20.2",
    "webpack-build-notifier": "^0.1.30",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.9",
    "webpack-manifest-plugin": "^2.0.4"
  },
  "optionalDependencies": {
    "fsevents": "^1.2.9"
  },
  "jest": {
    "rootDir": "./client",
    "setupFiles": [
      "./app/__tests__/enzyme_setup.js",
      "./app/__tests__/mocks.js"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "moduleNameMapper": {
      "^@/(.*)": "<rootDir>/app/$1",
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "testPathIgnorePatterns": [
      "<rootDir>/app/__tests__/"
    ]
  },
  "nyc": {
    "include": [
      "client/app/**",
      "viz-lib/**"
    ]
  },
  "//": "browserslist set to 'Async functions' compatibility",
  "browserslist": [
    "Edge >= 15",
    "Firefox >= 52",
    "Chrome >= 55",
    "Safari >= 10.1",
    "iOS >= 10.3",
    "Opera >= 42",
    "op_mob >= 46",
    "android >= 67",
    "and_chr >= 71",
    "and_ff >= 64",
    "and_uc >= 11.8",
    "samsung >= 6.2"
  ]
}
```

**Comment by kravets-levko** [comment]
Try also node@12 + npm@6 (as suggested in package.json) - I personally use this combination (node@12.16.3, npm@6.14.8) and it works fine. Also, try to ask on our [forum](https://discuss.redash.io/)

**Comment by priteshbhole** [comment]
using the same version as you have I still get the same 

```  │ │   └── crypto-random-string@1.0.0 
  │ ├── import-lazy@2.1.0 
  │ ├─┬ is-ci@1.2.1 
  │ │ └── ci-info@1.6.0 
  │ ├─┬ is-installed-globally@0.1.0 
  │ │ ├── global-dirs@0.1.1 
  │ │ └── is-path-inside@1.0.1 
  │ ├── is-npm@1.0.0 
  │ ├─┬ latest-version@3.1.0 
  │ │ └─┬ package-json@4.0.1 
  │ │   ├─┬ got@6.7.1 
  │ │   │ ├─┬ create-error-class@3.0.2 
  │ │   │ │ └── capture-stack-trace@1.0.0 
  │ │   │ ├── duplexer3@0.1.4 
  │ │   │ ├── get-stream@3.0.0 
  │ │   │ ├── is-redirect@1.0.0 
  │ │   │ ├── is-retry-allowed@1.2.0 
  │ │   │ ├── lowercase-keys@1.0.1 
  │ │   │ ├── timed-out@4.0.1 
  │ │   │ ├── unzip-response@2.0.1 
  │ │   │ └─┬ url-parse-lax@1.0.0 
  │ │   │   └── prepend-http@1.0.4 
  │ │   ├─┬ registry-auth-token@3.4.0 
  │ │   │ └─┬ rc@1.2.8 
  │ │   │   ├── deep-extend@0.6.0 
  │ │   │   ├── minimist@1.2.5 
  │ │   │   └── strip-json-comments@2.0.1 
  │ │   └── registry-url@3.1.0 
  │ ├── semver-diff@2.1.0 
  │ └── xdg-basedir@3.0.0 
  ├── uuid@3.3.3 
  ├─┬ validate-npm-package-license@3.0.4 
  │ ├─┬ spdx-correct@3.0.0 
  │ │ └── spdx-license-ids@3.0.5 
  │ └─┬ spdx-expression-parse@3.0.0 
  │   └── spdx-exceptions@2.1.0 
  ├─┬ validate-npm-package-name@3.0.0 
  │ └── builtins@1.0.3 
  ├─┬ which@1.3.1 
  │ └── isexe@2.0.0 
  ├─┬ worker-farm@1.7.0 
  │ └─┬ errno@0.1.7 
  │   └── prr@1.0.1 
  └── write-file-atomic@2.4.3 

[root@rupredashprototype redash-ldap]# node --version
v6.14.4
[root@rupredashprototype redash-ldap]# npm --version
6.14.8
[root@rupredashprototype redash-ldap]# npm install -g npm^C
[root@rupredashprototype redash-ldap]# ^C
[root@rupredashprototype redash-ldap]# ^C
[root@rupredashprototype redash-ldap]# nvm install 12.16.0
Downloading and installing node v12.16.0...
Downloading https://nodejs.org/dist/v12.16.0/node-v12.16.0-linux-x64.tar.xz...
##################################################################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v12.16.0 (npm v6.13.4)
[root@rupredashprototype redash-ldap]# clear

[root@rupredashprototype redash-ldap]# npm install
npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
npm WARN deprecated sortablejs@1.12.0: Object.assign was not transformed during the build of sortablejs, so it won't work in browsers where this does not exist (for example IE11). Please downgrade your version to 1.10.2 to keep supporting <=IE11 or upgrade to >2.0 where IE will no longer be supported.

> core-js-pure@3.4.7 postinstall /root/redash-ldap/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> cypress@5.3.0 postinstall /root/redash-ldap/node_modules/cypress
> node index.js --exec install


Cypress 5.3.0 is installed in /root/.cache/Cypress/5.3.0

npm WARN lifecycle redash-client@9.0.0-beta~postinstall: cannot run in wd redash-client@9.0.0-beta (cd viz-lib && npm ci && npm run build:babel) (wd=/root/redash-ldap)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN axios-auth-refresh@3.0.0 requires a peer of axios@~0.18.0 || ~0.19.1 || ~0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 717 packages from 206 contributors, removed 499 packages, updated 651 packages, moved 3 packages and audited 2949 packages in 145.564s

44 packages are looking for funding
  run `npm fund` for details

found 5425 vulnerabilities (4048 low, 24 moderate, 1352 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[root@rupredashprototype redash-ldap]# npm run build

> redash-client@9.0.0-beta build /root/redash-ldap
> npm run clean && npm run build:viz && NODE_ENV=production webpack


> redash-client@9.0.0-beta clean /root/redash-ldap
> rm -rf ./client/dist/


> redash-client@9.0.0-beta build:viz /root/redash-ldap
> (cd viz-lib && npm run build:babel)


> @redash/viz@0.1.1 build:babel /root/redash-ldap/viz-lib
> babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored

Error: Cannot find module 'babel-plugin-module-resolver' from '/root/redash-ldap/viz-lib'
    at Function.module.exports [as sync] (/root/redash-ldap/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/root/redash-ldap/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/root/redash-ldap/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/root/redash-ldap/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/root/redash-ldap/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /root/redash-ldap/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/root/redash-ldap/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/root/redash-ldap/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at plugins (/root/redash-ldap/node_modules/@babel/core/lib/config/config-descriptors.js:40:19) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @redash/viz@0.1.1 build:babel: `babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @redash/viz@0.1.1 build:babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T18_02_54_357Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@9.0.0-beta build:viz: `(cd viz-lib && npm run build:babel)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build:viz script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T18_02_54_370Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@9.0.0-beta build: `npm run clean && npm run build:viz && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T18_02_54_381Z-debug.log
 -- # node --version
v12.16.0
-- # npm --version
6.13.4
```

**Comment by kravets-levko** [comment]
Very interesting 🤔  Could you try `npm ci` instead?

**Comment by priteshbhole** [comment]
HI Running npm ci gives below

```[root@#########] npm ci
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install /root/redash-ldap/node_modules/fsevents
> node install


> core-js-pure@3.4.7 postinstall /root/redash-ldap/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> cypress@5.3.0 postinstall /root/redash-ldap/node_modules/cypress
> node index.js --exec install

/root/redash-ldap/node_modules/cypress/node_modules/execa/index.js:18
	const env = extendEnv ? {...process.env, ...envOption} : envOption;
	                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/redash-ldap/node_modules/cypress/lib/util.js:57:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@5.3.0 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress@5.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-15T09_51_43_051Z-debug.log```

**Comment by komangsidhiartha** [comment]
Hi @priteshbhole 

I just install 

`npm i --save-dev babel-plugin-module-resolver`

to make this work, 

whatever the reason, as long as I can build the code 😄 

I hope there are no problem in the builded code later 😆

**Comment by susodapop** [comment]
Closing this now as we haven't had any negative reports in the V10 beta. Feel free to reopen if the issue persists after the V10 release.

**Comment by andreujuanc** [comment]
@susodapop I just got this issue.
Only affects the iOS build. The android one builds just fine. 
Can't build with node v12, 14, nor 16.

Again, it builds perfectly for android. This is more certainly an environment (agent) issue.
