### ISSUE TITLE
SAML Login ERROR  on redash/redash:9.0.0-beta.b42121

### ISSUE THREAD

**Issue by goooBelieve** [getredash/redash#5313]
hi there  ，
     updated from  redash/redash:8.0.0.b32245 to redash/redash:9.0.0-beta.b42121

     everything is fine except the SAML login
     
     here is the error:
      
    [2020-12-11 10:45:44,998][PID:11][ERROR][saml_auth] Failed to parse SAML response
Traceback (most recent call last):
  File "/app/redash/authentication/saml_auth.py", line 74, in idp_initiated
    request.form["SAMLResponse"], entity.BINDING_HTTP_POST
  File "/usr/local/lib/python3.7/site-packages/saml2/client_base.py", line 714, in parse_authn_request_response
    binding, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/saml2/entity.py", line 1202, in _parse_response
    response = response.verify(keys)
  File "/usr/local/lib/python3.7/site-packages/saml2/response.py", line 1052, in verify
    if self.parse_assertion(keys):
  File "/usr/local/lib/python3.7/site-packages/saml2/response.py", line 938, in parse_assertion
    if not self._assertion(assertion, False):
  File "/usr/local/lib/python3.7/site-packages/saml2/response.py", line 818, in _assertion
    if not self.condition_ok():
  File "/usr/local/lib/python3.7/site-packages/saml2/response.py", line 604, in condition_ok
    conditions.not_on_or_after, self.timeslack)
  File "/usr/local/lib/python3.7/site-packages/saml2/validate.py", line 97, in validate_on_or_after
    "not_on_or_after=%s" % (now_str, slack, not_on_or_after))
saml2.validate.ResponseLifetimeExceed: Can't use response, too old (now=2020-12-11T10:45:44Z + slack=0 > not_on_or_after=2020-12-11T10:40:58.916Z

**Comment by jphillipobrien** [comment]
Did you ever get an answer here @goooBelieve ?

**Comment by goooBelieve** [comment]
> Did you ever get an answer here @goooBelieve ?

nope

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
