### ISSUE TITLE
Redash upgrade from v7 to v8.0.0 fails on db upgrade

### ISSUE THREAD

**Issue by czen** [getredash/redash#5376]
### Issue Summary

 * I am running self-hosted Redash v7 using development setup with docker-compose. The repo was at commit 6f290ddfa1b431430027bb1e170860255b387d58 when all containers were created and this setup ran with no problems until  now.
 * I am trying to upgrade from v7 dev setup  to production setup v8.0.0. 
 
To do that I have backed up the postgres database with pg_dump.
New Redash v8.0.0 was installed  with the provided setup script, but the line 

```
# sudo docker-compose run --rm server create_db
```
was commented out.

After successfull installation postgres db was restored with pg_restore into new container (which had no tables created yet).
Following upgrade guide at https://redash.io/help/open-source/admin-guide/how-to-upgrade
command `manage db upgrade`  returned no errors:

```
docker-compose run --rm server manage db upgrade
Starting redash_redis_1 ... done
Starting redash_postgres_1 ... done
[2021-01-29 20:28:42,350][PID:1][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2021-01-29 20:28:42,351][PID:1][INFO][alembic.runtime.migration] Will assume transactional DDL.
```

but in user interface no data sources are available (spinner just spins) and server container throws errors when trying to perform queries (in dashboard errors are shown instead of query results):

```

[2021-01-29 20:41:27,129][PID:17][INFO][metrics] method=GET path=/api/data_sources endpoint=data_sources status=500 content_type=application/json content_length=36 duration=13.56 query_count=5 query_duration=8.45
[2021-01-29 20:41:27,141][PID:11][INFO][metrics] method=GET path=/api/data_sources/types endpoint=data_source_types status=200 content_type=application/json content_length=21277 duration=5.34 query_count=3 query_duration=4.59
[2021-01-29 20:41:51,115][PID:11][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=200 content_type=application/json content_length=100 duration=54.11 query_count=7 query_duration=20.81
[2021-01-29 20:41:51,403][PID:11][INFO][metrics] method=GET path=/api/dashboards/favorites endpoint=dashboard_favorites status=200 content_type=application/json content_length=9983 duration=130.55 query_count=17 query_duration=49.21
[2021-01-29 20:41:51,525][PID:17][INFO][metrics] method=GET path=/api/queries/favorites endpoint=query_favorites status=200 content_type=application/json content_length=12226 duration=231.98 query_count=5 query_duration=20.99
[2021-01-29 20:41:52,275][PID:13][INFO][metrics] method=POST path=/api/events endpoint=events status=200 content_type=application/json content_length=4 duration=3.73 query_count=2 query_duration=3.64
[2021-01-29 20:41:59,713][PID:17][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=200 content_type=application/json content_length=100 duration=46.86 query_count=7 query_duration=16.17
[2021-01-29 20:41:59,885] ERROR in app: Exception on /api/data_sources [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 67, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/data_sources.py", line 95, in get
    for ds in data_sources:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 511, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 611, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1226, in process
    return process_value(impl_processor(value), dialect)
  File "/app/redash/models/types.py", line 28, in process_result_value
    return ConfigurationContainer.from_json(super(EncryptedConfiguration, self).process_result_value(value, dialect))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 409, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 216, in decrypt
    decrypted = self.fernet.decrypt(value)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 75, in decrypt
    return self._decrypt_data(data, timestamp, ttl)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 119, in _decrypt_data
    self._verify_signature(data)
  File "/usr/local/lib/python2.7/site-packages/cryptography/fernet.py", line 108, in _verify_signature
    raise InvalidToken


InvalidToken
```

What token? 🤕 

### Steps to Reproduce

1. Have Redash 7.0 postgres db
2. Try to restore it into fresh v8.0 instance and upgrade.

### Technical details:

* Redash Version: v7 dev master at 6f290ddfa1b431430027bb1e170860255b387d58, v8.0.0 from setup script, `redash/redash:8.0.0.b32245`
* Browser/OS: Ubuntu 18.04
* How did you install Redash: old v7.0 instance with docker-compose in development environment, new v8.0 using setup script.

**Comment by czen** [comment]
Never mind, found https://discuss.redash.io/t/invalidtoken-error-after-migrating-to-new-rds-backend/4185 and REDASH_COOKIE_SECRET.

After changing REDASH_COOKIE_SECRET to the value from old installation it's data sources became available, but unexpected errror would occur when trying to use them.
Adding REDASH_COOKIE_SECRET="old key value" to environment sections of all services in docker-compose.yml did help, now everythinng seems to work.

However, having more detailed and robust upgrade documentation would've saved me a day of figuring this out.  📜
