### ISSUE TITLE
Database migration fails due to get_status call which references missing database column 

### ISSUE THREAD

**Issue by jhult** [getredash/redash#5381]
### Issue Summary

When trying to run Redash, I get this error:
```
[2021-01-29 18:46:19,548][PID:11][ERROR][redash.app] Exception on /api/organization/status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...
                                                             ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/redash/handlers/organization.py", line 22, in organization_status
    models.Dashboard.org == current_org, models.Dashboard.is_archived == False
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3605, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3330, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3300, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3269, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...
```

This is because it needs [this database migration](https://github.com/getredash/redash/blob/master/migrations/versions/0ec979123ba4_.py). However, the database migrations/upgrade fails because [`cli/__init__.py`](https://github.com/getredash/redash/blob/master/redash/cli/__init__.py) first runs [`redash.monitor.get_status`](https://github.com/getredash/redash/blob/master/redash/monitor.py#L52) which tries to query the `dashboards` table. This query fails because it includes the missing column (`options`). Unfortunately, I didn't save the full stack trace when this occurred.

### Steps to Reproduce

1. Install and use a version of Redash prior to [this commit](https://github.com/getredash/redash/commit/84c2abed59bace2f2b9d1e31d512a60ba8c8ac47) (which was merged as part of #5267)
2. Run an upgrade: `/app/manage.py db upgrade`.
3. Notice the following exception which references the new database column: `sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...`

### Technical details:

* Redash Version: `master` git branch
* Browser/OS: Brave/macOS
* How did you install Redash: https://github.com/getredash/contrib-helm-chart (configured to use `master` git branch)

**Comment by jhult** [comment]
FYI, I got around this by commenting out [this print statement](https://github.com/getredash/redash/blob/master/redash/cli/__init__.py#L49).

However, ultimately, we need to ensure that any queries run before a database migration don't try to use anything in the migration.

**Comment by jhult** [comment]
Hopefully most users don't bump into this. Users will bump into it though if there is a database migration which adds a column and that database table is used as part of the [get_status](https://github.com/getredash/redash/blob/master/redash/monitor.py#L52) call.
