### ISSUE TITLE
redash 8.0 redash-server container exit  1 

### ISSUE THREAD

**Issue by Hanfee** [getredash/redash#5387]
Traceback (most recent call last):
  File "/app/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/app/redash/__init__.py", line 11, in <module>
    from flask_migrate import Migrate
  File "/usr/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 5, in <module>
    from alembic import __version__ as __alembic_version__
  File "/usr/local/lib/python2.7/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/usr/local/lib/python2.7/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/usr/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 15, in <module>
    from .. import ddl
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql  # noqa
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/mssql.py", line 8, in <module>
    from .base import AddColumn
  File "/usr/local/lib/python2.7/site-packages/alembic/ddl/base.py", line 11, in <module>
    from ..util.sqla_compat import _columns_for_constraint  # noqa
  File "/usr/local/lib/python2.7/site-packages/alembic/util/__init__.py", line 32, in <module>
    raise CommandError("SQLAlchemy 1.3.0 or greater is required.")
alembic.util.exc.CommandError: SQLAlchemy 1.3.0 or greater is required.

**Comment by kravets-levko** [comment]
Considering error message, you have to upgrade SQLAlchemy to version 1.3.0 or greater. If it doesn't help - welcome to our forum https://discuss.redash.io/
