### ISSUE TITLE
`manage.py groups list` command fails to read multi-byte characters 

### ISSUE THREAD

**Issue by Udomomo** [getredash/redash#5423]
### Issue Summary
`manage.py groups list` command fails if we use multi-byte characters on user name

### Steps to Reproduce

1. Create user and group

```
# postgres container
$ select id, name from groups;
 id |       name       
----+------------------
  1 | admin
  2 | default
  3 | developer
  4 | customer_success
(4 rows)

$ select name, groups from users;
   name   | groups 
----------+--------
 田中二郎 | {3}
 山本三郎 | {4}
 Udomomo  | {1,2}
 山田一郎 | {3}
(4 rows)
```

2. Run manage.py
```
# server container
$ bin/run ./manage.py groups list
sed: can't read .env: No such file or directory
Id: 1
Name: admin
Type: builtin
Organization: default
Permissions: [admin,super_admin]
Users: Udomomo
--------------------
Id: 4
Name: customer_success
Type: regular
Organization: default
Permissions: [view_query,view_source,execute_query,schedule_query,list_dashboards,list_alerts,list_data_sources]
Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/app/redash/cli/groups.py", line 103, in list
    print("Users: {}".format(", ".join(user_names)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

- First group (`admin`) is shown properly, because user name is alphabet
- Next group (`customer_success`) raises error when showing user. User name is `山本三郎`.

### Technical details:

* Redash Version: 8.0.0+b32245
* Browser/OS: Ubuntu
* How did you install Redash: Use official AMI (ami-060741a96307668be)

**Comment by ariarijp** [comment]
Hi, @Udomomo

Thank you for your contribution!

FYI, I ran `bin/run ./manage.py groups list` on v10.0.0-beta.

It looks like it is working correctly.

```
redash@46afa06893b9:/app$ bin/run ./manage.py groups list
sed: can't read .env: No such file or directory
Id: 1
Name: admin
Type: builtin
Organization: default
Permissions: [admin,super_admin]
Users: admin
--------------------
Id: 2
Name: default
Type: builtin
Organization: default
Permissions: [create_dashboard,create_query,edit_dashboard,edit_query,view_query,view_source,execute_query,list_users,schedule_query,list_dashboards,list_alerts,list_data_sources]
Users: user1, user2, user3, admin, 山田一郎
```

I guess this issue solved with Python3.

Thanks,

**Comment by susodapop** [comment]
Thanks for confirming @ariarijp . I confirm this appears to be fixed in V10.
