### ISSUE TITLE
version redash/redash:8.0.0.b32245 saml doesn't work with Auth0

### ISSUE THREAD

**Issue by murphycrosby** [getredash/redash#5472]
### Issue Summary

Running AWS ami-0d915a031cabac0e0

### Steps to Reproduce

1. Follow this https://discuss.redash.io/t/auth0-integration/586
2. Try to login, get 302 of the redirect back to the application

`2021-04-14 13:59:58,569] ERROR in app: Exception on /saml/login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/redash/authentication/saml_auth.py", line 108, in sp_initiated
    saml_client = get_saml_client(current_org)
  File "/app/redash/authentication/saml_auth.py", line 57, in get_saml_client
    sp_config.load(saml_settings)
  File "/usr/local/lib/python2.7/site-packages/saml2/config.py", line 356, in load
    self.load_complex(cnf, metadata_construction=metadata_construction)
  File "/usr/local/lib/python2.7/site-packages/saml2/config.py", line 296, in load_complex
    self.load_metadata(cnf["metadata"]))
  File "/usr/local/lib/python2.7/site-packages/saml2/config.py", line 400, in load_metadata
    mds.imp(metadata_conf)
  File "/usr/local/lib/python2.7/site-packages/saml2/mdstore.py", line 922, in imp
    self.load(key, **val)
  File "/usr/local/lib/python2.7/site-packages/saml2/mdstore.py", line 910, in load
    _md.load()
  File "/usr/local/lib/python2.7/site-packages/saml2/mdstore.py", line 757, in load
    raise SourceNotFound(self.url)
SourceNotFound: https://<redacted auth0 tennant>/samlp/<redacted auth0 Client ID>`

### Technical details:

* Redash Version: 8.0.0.b32245
* Browser/OS: Chrome 89.0.4389.114 / MacOs Big Sur 11.2.3
* How did you install Redash: AWS ami-0d915a031cabac0e0

**Comment by murphycrosby** [comment]
Resolved the issue. Assume Auth0 has updated some things and therefore the documentation should be updated.

Auth0 Steps
1. Create "Regular Web Applications - Traditional web app using redirects."
2. Under add-ons, enable SAML2
3. In the SAML2 config use the following call back url: `https://[YOUR_REDASH_HOSTNAME]/saml/callback?org_slug=default`
4. In the SAML2 config use the following settings JSON, (the email address needed to be higher than nameidentifier)
`{
  "mappings": {
    "given_name": "FirstName",
    "family_name": "LastName"
  },
  "passthroughClaimsWithNoMapping": false,
  "includeAttributeNameFormat": true,
  "nameIdentifierFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
  "nameIdentifierProbes": [
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
  ]
}`

Redash Steps:
1. SAML Metadata URL: `https://[YOUR_TENANT_HOSTNAME]/samlp/metadata/[AUTH0 Client ID]`. When you hit this link it should download an XML file. If it doesn't, you've got something wrong.
2. SAML Entity ID: `urn:[YOUR_TENANT_HOSTNAME]` (I didn't need a connection name)
3. SAML NameID Format: EmailAddress

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
