### ISSUE TITLE
Exception after upgrade to v10

### ISSUE THREAD

**Issue by namepunk** [getredash/redash#5542]
* Redash Version: v9 to v10 (upgrade from v8 gives me same exceptions)
* Browser/OS: Chrome/debian10
* How did you install Redash: docker

after upgrade to redash v10 beta i have errors in console column dashboards.options does not exist
<details>

 [2021-07-21 10:33:38 +0000] [1] [INFO] Starting gunicorn 20.0.4,
[2021-07-21 10:33:38 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1),
[2021-07-21 10:33:38 +0000] [1] [INFO] Using worker: sync,
[2021-07-21 10:33:38 +0000] [8] [INFO] Booting worker with pid: 8,
[2021-07-21 10:33:38 +0000] [9] [INFO] Booting worker with pid: 9,
[2021-07-21 10:33:38 +0000] [10] [INFO] Booting worker with pid: 10,
[2021-07-21 10:33:38 +0000] [11] [INFO] Booting worker with pid: 11,
[2021-07-21 10:33:57,791][PID:8][INFO][metrics] method=GET path=/ endpoint=redash_index status=200 content_type=text/html; charset=utf-8 content_length=1502 duration=0.72 query_count=2 query_duration=4.17,
[2021-07-21 10:33:57,919][PID:8][INFO][metrics] method=GET path=/static/app.ab9450883b2429793467.css endpoint=static status=304 content_type=text/css; charset=utf-8 content_length=712761 duration=0.52 query_count=2 query_duration=14.73,
[2021-07-21 10:33:58,050][PID:9][INFO][metrics] method=GET path=/static/vendors~app.bf05e4151a496e0c15d6.css endpoint=static status=304 content_type=text/css; charset=utf-8 content_length=77565 duration=0.72 query_count=2 query_duration=6.37,
[2021-07-21 10:33:58,053][PID:11][INFO][metrics] method=GET path=/static/app.ab9450883b2429793467.js endpoint=static status=304 content_type=application/javascript; charset=utf-8 content_length=582335 duration=0.83 query_count=2 query_duration=6.94,
[2021-07-21 10:33:58,054][PID:10][INFO][metrics] method=GET path=/static/vendors~app.bf05e4151a496e0c15d6.js endpoint=static status=304 content_type=application/javascript; charset=utf-8 content_length=4048606 duration=0.71 query_count=2 query_duration=7.28,
[2021-07-21 10:33:58,634][PID:9][INFO][metrics] method=GET path=/api/session endpoint=redash_session status=200 content_type=application/json content_length=1684 duration=5.82 query_count=4 query_duration=8.19,
[2021-07-21 10:33:58,662][PID:11][ERROR][redash.app] Exception on /api/organization/status [GET],
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context,
    cursor, statement, parameters, context,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute,
    cursor.execute(statement, parameters),
psycopg2.errors.UndefinedColumn: column dashboards.options does not exist,
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...,
                                                             ^,
,
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app,
    response = self.full_dispatch_request(),
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request,
    rv = self.handle_user_exception(e),
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router,
    return original_handler(e),
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception,
    reraise(exc_type, exc_value, tb),
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise,
    raise value,
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view,
    return func(*args, **kwargs),
  File "/app/redash/handlers/organization.py", line 22, in organization_status,
    models.Dashboard.org == current_org, models.Dashboard.is_archived == False,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3605, in count,
    return self.from_self(col).scalar(),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3330, in scalar,
    ret = self.one(),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3300, in one,
    ret = self.one_or_none(),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3269, in one_or_none,
    ret = list(self),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__,
    return self._execute_and_instances(context),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances,
    result = conn.execute(querycontext.statement, self._params),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute,
    return meth(self, multiparams, params),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection,
    return connection._execute_clauseelement(self, multiparams, params),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement,
    distilled_params,,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context,
    e, statement, parameters, cursor, context,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception,
    util.raise_from_cause(sqlalchemy_exception, exc_info),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause,
    reraise(type(exception), exception, tb=exc_tb, cause=cause),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise,
    raise value.with_traceback(tb),
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context,
    cursor, statement, parameters, context,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute,
    cursor.execute(statement, parameters),
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.options does not exist,
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...,
                                                             ^,
,
[SQL: SELECT count(*) AS count_1 ,
FROM (SELECT dashboards.updated_at AS dashboards_updated_at, dashboards.created_at AS dashboards_created_at, dashboards.id AS dashboards_id, dashboards.version AS dashboards_version, dashboards.org_id AS dashboards_org_id, dashboards.slug AS dashboards_slug, dashboards.name AS dashboards_name, dashboards.user_id AS dashboards_user_id, dashboards.layout AS dashboards_layout, dashboards.dashboard_filters_enabled AS dashboards_dashboard_filters_enabled, dashboards.is_archived AS dashboards_is_archived, dashboards.is_draft AS dashboards_is_draft, dashboards.tags AS dashboards_tags, dashboards.options AS dashboards_options ,
FROM dashboards ,
WHERE %(param_1)s = dashboards.org_id AND dashboards.is_archived = false) AS anon_1],
[parameters: {'param_1': 1}],
(Background on this error at: http://sqlalche.me/e/f405),
[2021-07-21 10:33:58,666][PID:11][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=500 content_type=text/html content_length=290 duration=36.74 query_count=6 query_duration=15.95,
[2021-07-21 10:33:58,667][PID:11][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=500 content_type=? content_length=-1 duration=37.89 query_count=6 query_duration=15.95,

</details>

upgrade from v8 to v9 works fine, upgrade v8 to v10 or v9 to v10 does not work

**Comment by namepunk** [comment]
After i add column dashboards.options manually, exception has gone, but many dashboards does not work, maybe some other migrations also not implemented

**Comment by susodapop** [comment]
Hi there, it looks like you didn't actually run the migrations. You should never need to manually change the database. Instead you should run:

```
docker-compose run --rm server manage db upgrade
```

Try this.

**Comment by namepunk** [comment]
I understand that, but for some reason database version not correct maybe. after i run command i receive in log 

[2021-07-26 07:46:26,676][PID:1][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2021-07-26 07:46:26,676][PID:1][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2021-07-26 07:46:26,693][PID:1][INFO][alembic.runtime.migration] Running upgrade  -> 65fc9ede4746, Add is_draft status to queries and dashboards
Can't run this migration as you already have is_draft columns, please run:
./manage.py db stamp 65fc9ede4746 # you might need to alter the command to match your environment.

I never add manually changes to this database, this is backup of my production redash 8.0

**Comment by susodapop** [comment]
> I think these migrations are a little broken.

I think we would have seen a lot more feedback about this if that were the case. More likely it's something specific to your instance / environment.

From your initial  post it seems like you're trying this from multiple versions of Redash. For example, you mention that v8 to v9 fails. And that v9 to v10 fails with the same exceptions. How could you have tried to run the v9 to v10 migration if you never had a working v9 instance? 

Now it seem like you might be trying to run the v8 to v9 migrations on your v9 instance.

Probably best at this point to start from scratch. Verify that you're using the correct database backup (i.e. make sure the application runs in your browser and check which version it is).

**Comment by susodapop** [comment]
Closing this for now. Feel free to reopen if you continue seeing issues with V10.

**Comment by paoloxide** [comment]
> Hi there, it looks like you didn't actually run the migrations. You should never need to manually change the database. Instead you should run:
> 
> ```
> docker-compose run --rm server manage db upgrade
> ```
> 
> Try this.
> 
> Duplicate of #5531

Hi, I was able to successfully upgrade redash in Kubernetes from v8 -> v10, I also encountered the error here about dashboard.options missing,  how do I run the migrations/upgrade of db in a kubernetes setup?
