### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "organizations" does not exist

### ISSUE THREAD

**Issue by frafra** [getredash/redash#5591]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "organizations" does not exist
LINE 2: FROM organizations 
             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 442, in __inner
    return obj(*a, **k)
  File "/app/redash/handlers/authentication.py", line 190, in login
    if current_org == None and not settings.MULTI_ORG:
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 370, in <lambda>
    __eq__ = lambda x, o: x._get_current_object() == o
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/app/redash/authentication/org_resolving.py", line 18, in _get_current_org
    g.org = Organization.get_by_slug(slug)
  File "/app/redash/models/organizations.py", line 31, in get_by_slug
    return cls.query.filter(cls.slug == slug).first()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3240, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "organizations" does not exist
LINE 2: FROM organizations 
             ^

[SQL: SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings 
FROM organizations 
WHERE organizations.slug = %(slug_1)s 
 LIMIT %(param_1)s]
[parameters: {'slug_1': 'default', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
```

### Technical details:

* Redash Version: e9bcc3c
* How did you install Redash: docker-compose up --build (+ some dep fixes, otherwise it would not start)

**Comment by susodapop** [comment]
Looks like you didn't create the database:

```docker-compose run --rm server create_db```

**Comment by frafra** [comment]
I would suggest initializing the database automatically, as a `docker-compose up` should be able to start the whole system, without further interaction. An "init" container could be created, or the creation of the database could be added to the entrypoint.

**Comment by susodapop** [comment]
There's some discussion on this subject in #5506. A single command is desirable -- for now it's easiest to make the instructions more discoverable.

**Comment by HarshPrajapati2309** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
>     cursor, statement, parameters, context
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.UndefinedTable: relation "organizations" does not exist
> LINE 2: FROM organizations 
>              ^
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/local/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
>     return self.app(environ, start_response)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
>     response = self.handle_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
>     return original_handler(e)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
>     return original_handler(e)
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 442, in __inner
>     return obj(*a, **k)
>   File "/app/redash/handlers/authentication.py", line 190, in login
>     if current_org == None and not settings.MULTI_ORG:
>   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 370, in <lambda>
>     __eq__ = lambda x, o: x._get_current_object() == o
>   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 307, in _get_current_object
>     return self.__local()
>   File "/app/redash/authentication/org_resolving.py", line 18, in _get_current_org
>     g.org = Organization.get_by_slug(slug)
>   File "/app/redash/models/organizations.py", line 31, in get_by_slug
>     return cls.query.filter(cls.slug == slug).first()
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3240, in first
>     ret = list(self[0:1])
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
>     return list(res)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
>     return self._execute_and_instances(context)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
>     return meth(self, multiparams, params)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
>     distilled_params,
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
>     e, statement, parameters, cursor, context
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
>     util.raise_from_cause(sqlalchemy_exception, exc_info)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
>     cursor, statement, parameters, context
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "organizations" does not exist
> LINE 2: FROM organizations 
>              ^
> 
> [SQL: SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings 
> FROM organizations 
> WHERE organizations.slug = %(slug_1)s 
>  LIMIT %(param_1)s]
> [parameters: {'slug_1': 'default', 'param_1': 1}]
> (Background on this error at: http://sqlalche.me/e/f405)
> ```
> 
> ### Technical details:
> * Redash Version: [e9bcc3c](https://github.com/getredash/redash/commit/e9bcc3c9243efbe1af922f918b5367fba9860172)
> * How did you install Redash: docker-compose up --build (+ some dep fixes, otherwise it would not start)

same issue i am facing , Is there any solution ? i am using windows docker desktop

**Comment by justinclift** [comment]
Yeah, you need to run that step that creates the database tables: https://github.com/getredash/redash/issues/5591#issuecomment-928050601

As a thought, the local development setup guide might be helpful too: https://github.com/getredash/redash/wiki/Local-development-setup
