### ISSUE TITLE
No module named 'ptpython'

### ISSUE THREAD

**Issue by armandleopold** [getredash/redash#5596]
### Issue Summary

Can't find module `ptpython` when running : `python manage.py shell`

```
redash@redash-deployement-scheduledworker-7c5dd495cd-jl6gg:/app$ python manage.py shell
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/redash/cli/__init__.py", line 82, in shell
    from ptpython import repl
ModuleNotFoundError: No module named 'ptpython'
```

### Steps to Reproduce

1. pull redash docker image 10-beta
2. run a commandline 
3. run `python manage.py shell`

### Technical details:

* Redash Version: 10-beta
* How did you install Redash: helm chart redash

**Comment by susodapop** [comment]
The helm-chart repo is a separate effort. AFAIK it has not been updated to support V10.
