### ISSUE TITLE
Error adding datasource Redshift

### ISSUE THREAD

**Issue by sp-ludovic-ivain** [getredash/redash#5647]
### Issue Summary

Get an internal error adding Redshift as a datasource.
Looking through the logs, we saw this error:

``` 
StatementError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (exceptions.UnicodeDecodeError) 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128) [SQL: u'INSERT INTO data_sources (org_id, name, type, encrypted_options, queue_name, scheduled_queue_name, created_at) VALUES (%(org_id)s, %(name)s, %(type)s, %(encrypted_options)s, %(queue_name)s, %(scheduled_queue_name)s, now()) RETURNING data_sources.id'] [parameters: [{'org_id': 1, 'type': u'redshift', 'name': u'name', 'encrypted_options': <redash.utils.configuration.ConfigurationContainer object at 0x7ff4ba31d410>}]]
```

### Steps to Reproduce

1. Creating datasource through https://redash.xxxxxxx.xx/data_sources/new
2. Selecting Redshift has datasource
3. Fill the fields: Name, Host, Port, User, Password, Database Name (nothung else)
4. Save

### Technical details:

* Redash Version: 8.0.2.b37747
* Browser/OS: OSX 11.6.1 / Chrome 95.0.4638.54
* How did you install Redash: official Helm chart

### Full Stacktrace:

```
ERROR in app: Exception on /api/data_sources [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 67, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/data_sources.py", line 133, in post
    options=config)
  File "/app/redash/models/__init__.py", line 120, in create_with_group
    group=data_source.org.default_group)
  File "/app/redash/models/organizations.py", line 41, in default_group
    return self.groups.filter(Group.name == 'default', Group.type == Group.BUILTIN_GROUP).first()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2994, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1444, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1434, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1132, in _execute_context
    None, None)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 685, in _init_compiled
    for key in compiled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 685, in <genexpr>
    for key in compiled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 1178, in process
    return impl_processor(process_param(value, dialect))
  File "/app/redash/models/types.py", line 25, in process_bind_param
    return super(EncryptedConfiguration, self).process_bind_param(value.to_json(), dialect)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 385, in process_bind_param
    self._update_key()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 380, in _update_key
    self.engine._update_key(key)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 48, in _update_key
    key = key.encode()
StatementError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (exceptions.UnicodeDecodeError) 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128) [SQL: u'INSERT INTO data_sources (org_id, name, type, encrypted_options, queue_name, scheduled_queue_name, created_at) VALUES (%(org_id)s, %(name)s, %(type)s, %(encrypted_options)s, %(queue_name)s, %(scheduled_queue_name)s, now()) RETURNING data_sources.id'] [parameters: [{'org_id': 1, 'type': u'redshift', 'name': u'name', 'encrypted_options': <redash.utils.configuration.ConfigurationContainer object at 0x7ff4ba31d410>}]]
```

**Comment by nathan-protempo** [comment]
Do any of the parameters for the data source (e.g. host name, password) contain Extended ASCII characters? That error is complaining about an ï character (hex 0xef) which it apparently can't translate. Looking at similar errors online indicates this is possibly an issue with the hosting OS rather than redash?

**Comment by sp-ludovic-ivain** [comment]
yes, i fixed it days ago, sorry to let this issue open...
The problem was related with the redash secret key that wasn't encoded the right way.
