### ISSUE TITLE
Unable to connect to azure flexible Postgres Instance from Re:Dash

### ISSUE THREAD

**Issue by deadbrainviv** [getredash/redash#5664]
I am writing this issue post as I am unable to find any logs pointing to the root cause of the error I am getting

When adding a Postgres data source in Re:Dash, I get this error when I click Test Connection

Connection Test Failed:
Unknown error occurred while performing connection test. Please try again later.

Kindly advice on how to troubleshoot or resolve.

PS: I am able to nc -zv <azuredbinstancehostname> <port> successfully from the re:dash host server

Awaiting some clarity on how I can troubleshoot the same 

Regards
Vivek

**Comment by susodapop** [comment]
What command do you run to get logs? It should be `docker-compose logs -f --tail 100 server`? You should see a stack trace indicating a more specific error.

**Comment by deadbrainviv** [comment]
I am unable to get the logs with the above command. Is there any way to check if it is running from docker. I can see folders on the OS and don't see any docker image running as well.

**Comment by flover97** [comment]
Hi, i have same problem with connection to postgresql.
my log traceback:
`server_1            | [2022-12-09 06:59:50,186] ERROR in app: Exception on /api/data_sources/3/test [POST]
server_1            | Traceback (most recent call last):
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
server_1            |     rv = self.dispatch_request()
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
server_1            |     return self.view_functions[rule.endpoint](**req.view_args)
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
server_1            |     resp = resource(*args, **kwargs)
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
server_1            |     return func(*args, **kwargs)
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
server_1            |     return self.dispatch_request(*args, **kwargs)
server_1            |   File "/app/redash/handlers/base.py", line 31, in dispatch_request
server_1            |     return super(BaseResource, self).dispatch_request(*args, **kwargs)
server_1            |   File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
server_1            |     resp = meth(*args, **kwargs)
server_1            |   File "/app/redash/permissions.py", line 67, in decorated
server_1            |     return fn(*args, **kwargs)
server_1            |   File "/app/redash/handlers/data_sources.py", line 216, in post
server_1            |     response = {"message": text_type(e), "ok": False}
server_1            | UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
`
