### ISSUE TITLE
Error running query: Error writing file '/tmp/MYW9Q8ah' (Errcode: 28 "No space left on device")

### ISSUE THREAD

**Issue by ngbusca** [getredash/redash#5668]
### Issue Summary

I receive the following error:

```
 Error running query: Error writing file '/tmp/MYW9Q8ah' (Errcode: 28 "No space left on device")
```

on *some* of my queries. 

Around the same time when this error appeared, I've also started getting a `Schema refresh failed.`

I've checked the available disk space by manually logging to each container and running `df -h`, no container has a disk full.

Here's the trace from `docker-compose logs`:

```
adhoc_worker_1 | [2021-12-07 09:46:20,955][PID:67][ERROR][ForkPoolWorker-5] Task redash.tasks.execute_query[851b72c2-c4d4-40f3-bb4a-f9031c826fce] raised unexpected: QueryExecutionError('Error writing file \'/tmp/MY0V3Veg\' (Errcode: 28 "No space left on device")',)
adhoc_worker_1 | Traceback (most recent call last):
adhoc_worker_1 | File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
adhoc_worker_1 | R = retval = fun(*args, **kwargs)
adhoc_worker_1 | File "/app/redash/worker.py", line 84, in __call__
adhoc_worker_1 | return TaskBase.__call__(self, *args, **kwargs)
adhoc_worker_1 | File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
adhoc_worker_1 | return self.run(*args, **kwargs)
adhoc_worker_1 | File "/app/redash/tasks/queries.py", line 436, in execute_query
adhoc_worker_1 | scheduled_query).run()
adhoc_worker_1 | File "/app/redash/tasks/queries.py", line 382, in run
adhoc_worker_1 | raise result
adhoc_worker_1 | QueryExecutionError: Error writing file '/tmp/MY0V3Veg' (Errcode: 28 "No space left on device")
``` 

### Technical details:

* Redash Version: 8.0.0+b32245 (a16f551e)
* Browser/OS: Firefox 94.0.2 (64-bit)/Mac
* How did you install Redash:
Redash runs on a linux vm and was installed via docker (following instructions from https://github.com/getredash/setup)

**Comment by ngbusca** [comment]
I'm closing since the issue was on the mysql server, not the redash server
