### ISSUE TITLE
Getting "psycopg2.errors.UndefinedColumn: column dashboards.options does not exist" while installing and running redash on to K8S cluster using Helm

### ISSUE THREAD

**Issue by sankalp7654** [getredash/redash#5683]
### Issue Summary

I have installed Redash on the EKS cluster using the helm chart https://github.com/getredash/contrib-helm-chart . For some reason, the login page is working but the main landing page post login is not working. When I checked the logs of the redash pod I can see the below error saying some column in the dashboards table is not existing.

```
2022-01-12 19:10:35,901][PID:71][DEBUG][metrics] table=groups query=select duration=4.52
[2022-01-12 19:10:35,901][PID:59][DEBUG][metrics] table=alerts query=select duration=3.48
[2022-01-12 19:10:35,902][PID:71][INFO][metrics] method=GET path=/api/session endpoint=redash_session status=200 content_type=application/json content_length=1490 duration=16.76 query_count=4 query_duration=17.05
[2022-01-12 19:10:35,926][PID:59][DEBUG][metrics] table=data_sources query=select duration=5.68
[2022-01-12 19:10:35,961][PID:59][DEBUG][metrics] table=queries query=select duration=9.87
[2022-01-12 19:10:35,977][PID:59][ERROR][redash.app] Exception on /api/organization/status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/redash/handlers/organization.py", line 22, in organization_status
    models.Dashboard.org == current_org, models.Dashboard.is_archived == False
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3605, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3330, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3300, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3269, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...
                                                             ^

[SQL: SELECT count(*) AS count_1
FROM (SELECT dashboards.updated_at AS dashboards_updated_at, dashboards.created_at AS dashboards_created_at, dashboards.id AS dashboards_id, dashboards.version AS dashboards_version, dashboards.org_id AS dashboards_org_id, dashboards.slug AS dashboards_slug, dashboards.name AS dashboards_name, dashboards.user_idAS dashboards_user_id, dashboards.layout AS dashboards_layout, dashboards.dashboard_filters_enabled AS dashboards_dashboard_filters_enabled, dashboards.is_archived AS dashboards_is_archived, dashboards.is_draft AS dashboards_is_draft, dashboards.tags AS dashboards_tags, dashboards.options AS dashboards_options
FROM dashboards
WHERE %(param_1)s = dashboards.org_id AND dashboards.is_archived = false) AS anon_1]
[parameters: {'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
[2022-01-12 19:10:35,987][PID:59][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=500 content_type=text/html content_length=290 duration=104.71 query_count=6 query_duration=30.43
[2022-01-12 19:10:35,989][PID:59][INFO][metrics] method=GET path=/api/organization/status endpoint=redash_organization_status status=500 content_type=? content_length=-1 duration=107.12 query_count=6 query_duration=30.43
[2022-01-12 19:10:37,023][PID:65][DEBUG][metrics] table=organizations query=select duration=2.08
[2022-01-12 19:10:37,024][PID:65][DEBUG][root] Current organization: Deloitte (1) (slug: default)
[2022-01-12 19:10:37,028][PID:65][DEBUG][metrics] table=users query=select duration=2.45
```

### Steps to Reproduce

1. Get an EKS Cluster, Redis and RDS Instance running in the AWS
2. Get a bastion which can access the cluster
3. Install the Helm client inside the bastion
4. Git clone the above repository
5. Change the values.yaml file, provide the required values such as cookie secret, etc 
6. Use the `helm install -f values.yaml redash  redash/redash -n redash` to install the redash on the cluster
7. Feel free to change the Service type from ClusterIP to NodePort in order to access the redash login page through the bastion
8. Addiionally, in order to access the NodePort service through your local mahine, feel free to use Tunneling to connect with the Service from localhost through bastion

### Technical details:

* Redash Image Version: redash/redash:10.0.0.b50363
* Browser/OS: Sidekick, Chrome
* How did you install Redash: Mentioned under Steps to reproduce

**Comment by furlanrb** [comment]
Hi @sankalp7654 . I'm getting the same error on a cluster k8s, when I was using redash 8 and tried to up it to v10. Did you find out this error solution?

**Comment by ThomasBarach** [comment]
Hello, same issue here.

**Comment by ThomasBarach** [comment]
Hello, I figured this out.
