### ISSUE TITLE
SSL error in Helm redash while adding Elasticsearch as DataSource

### ISSUE THREAD

**Issue by revathyr13** [getredash/redash#5713]
Hello Team,

We have deployed redash version  redash-2.3.1 using helm in our infrastructure. But now we are facing connectivity errors while adding Elasticsearch as Data source. 
Following is the error details

[2022-03-03 06:05:03,816][PID:15][ERROR][redash.query_runner.elasticsearch] HTTPSConnectionPool(host='******.com', port=443): Max retries exceeded with url: /_cluster/health (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "/app/redash/query_runner/elasticsearch.py", line 281, in test_connection
    r = requests.get("{0}/_cluster/health".format(self.server_url), auth=self.auth)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='******.com', port=443): Max retries exceeded with url: /_cluster/health (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

We have rebuild the redash image by adding the intermediate CA of the Elasticsearch URL to /etc/ssl/certs/ca-certificates.crt as well as in /usr/local/share/ca-certificates and tried redeploying it. Now we are able to connect to the Elasticsearch URL from the pods via Curl. 
without any errors. 
root@redash-dev-696cc8fdff-55n72:/etc/ssl/certs# curl -I ******.com
HTTP/2 401
date: Thu, 03 Mar 2022 06:05:47 GMT
content-type: application/json; charset=UTF-8
content-length: 459
www-authenticate: Bearer realm="security"
www-authenticate: ApiKey
www-authenticate: Basic realm="security" charset="UTF-8"
strict-transport-security: max-age=15724800; includeSubDomains

However, still  we cannot add the same URL as Datasource. Getting same SSL verify error while adding the Datasource. It seems like the issue is with the python script elasticsearch.py.  Is there any option to verify the added cert in to this script ?  I have also noticed you have added Skip SSL option in https://github.com/getredash/redash/pull/4416 But still its not merged to master branch, hence we would like to know what options we have to fix the SSL issue.

Thank you

**Comment by susodapop** [comment]
Thanks for opening this issue. Can you have a look at the new elastic search query runner implementation [here](https://github.com/getredash/redash/pull/5701)? We're planning to merge this shortly and to deprecate the existing query runner as it is painfully broken and has been for some time.
