### ISSUE TITLE
Docker-compose up fails

### ISSUE THREAD

**Issue by xepozz** [getredash/redash#5740]
### Issue Summary

Installation python deps fails because of vendor's site is is unavailable.
I can't open the link `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz`

Could you advise is it only mine problem?

<details>
<summary>docker-compose up -d</summary>

```
[+] Building 82.0s (29/66)                                                                                                                                                           
 => [redash_worker internal] load build definition from Dockerfile                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                                             0.0s
 => [redash_scheduler internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 32B                                                                                                                                             0.0s
 => [redash_server internal] load build definition from Dockerfile                                                                                                              0.0s
 => => transferring dockerfile: 32B                                                                                                                                             0.0s
 => [redash_worker internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 35B                                                                                                                                                0.0s
 => [redash_scheduler internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 35B                                                                                                                                                0.0s
 => [redash_server internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 35B                                                                                                                                                0.0s
 => [redash_scheduler internal] load metadata for docker.io/library/python:3.7-slim-buster                                                                                      1.7s
 => [redash_server internal] load metadata for docker.io/library/node:14.17                                                                                                     1.7s
 => [redash_scheduler internal] load build context                                                                                                                              0.1s
 => => transferring context: 88.73kB                                                                                                                                            0.1s
 => [redash_worker stage-1  1/15] FROM docker.io/library/python:3.7-slim-buster@sha256:1c99a3b0f4c8168b2210e74911cbcf028a6a44ddad50d0eed5a5eced28173295                         0.0s
 => [redash_worker frontend-builder  1/10] FROM docker.io/library/node:14.17@sha256:40aa86fa97c6cb85af15ecdd67798f7578c5c20e8d16f99d5b4f8f14196a0568                            0.0s
 => [redash_worker internal] load build context                                                                                                                                 0.1s
 => => transferring context: 88.73kB                                                                                                                                            0.1s
 => [redash_server internal] load build context                                                                                                                                 0.1s
 => => transferring context: 88.73kB                                                                                                                                            0.1s
 => CACHED [redash_scheduler stage-1  2/15] RUN useradd --create-home redash                                                                                                    0.0s
 => CACHED [redash_scheduler stage-1  3/15] RUN apt-get update &&   apt-get install -y     curl     gnupg     build-essential     pwgen     libffi-dev     sudo     git-core    0.0s
 => CACHED [redash_scheduler stage-1  4/15] RUN wget --quiet https://databricks.com/wp-content/uploads/2.6.10.1010-2/SimbaSparkODBC-2.6.10.1010-2-Debian-64bit.zip -O /tmp/sim  0.0s
 => CACHED [redash_scheduler stage-1  5/15] WORKDIR /app                                                                                                                        0.0s
 => CACHED [redash_scheduler stage-1  6/15] RUN pip install pip==20.2.4;                                                                                                        0.0s
 => CACHED [redash_scheduler stage-1  7/15] COPY requirements_all_ds.txt ./                                                                                                     0.0s
 => CACHED [redash_scheduler frontend-builder  2/10] RUN npm install --global --force yarn@1.22.10                                                                              0.0s
 => CACHED [redash_scheduler frontend-builder  3/10] RUN useradd -m -d /frontend redash                                                                                         0.0s
 => CACHED [redash_scheduler frontend-builder  4/10] WORKDIR /frontend                                                                                                          0.0s
 => CACHED [redash_scheduler frontend-builder  5/10] COPY --chown=redash package.json yarn.lock .yarnrc /frontend/                                                              0.0s
 => CACHED [redash_scheduler frontend-builder  6/10] COPY --chown=redash viz-lib /frontend/viz-lib                                                                              0.0s
 => CACHED [redash_scheduler frontend-builder  7/10] RUN if [ "xtrue" = "x" ] ; then yarn --frozen-lockfile --network-concurrency 1; fi                                         0.0s
 => CACHED [redash_scheduler frontend-builder  8/10] COPY --chown=redash client /frontend/client                                                                                0.0s
 => CACHED [redash_scheduler frontend-builder  9/10] COPY --chown=redash webpack.config.js /frontend/                                                                           0.0s
 => CACHED [redash_scheduler frontend-builder 10/10] RUN if [ "xtrue" = "x" ] ; then yarn build; else mkdir -p /frontend/client/dist && touch /frontend/client/dist/multi_org.  0.0s
 => ERROR [redash_scheduler stage-1  8/15] RUN if [ "x$skip_ds_deps" = "x" ] ; then pip install -r requirements_all_ds.txt ; else echo "Skipping pip install -r requirements_  80.1s
------
 > [redash_scheduler stage-1  8/15] RUN if [ "x$skip_ds_deps" = "x" ] ; then pip install -r requirements_all_ds.txt ; else echo "Skipping pip install -r requirements_all_ds.txt" ; fi:
#0 2.832 Collecting google-api-python-client==1.7.11
#0 3.059   Downloading google-api-python-client-1.7.11.tar.gz (142 kB)
#0 7.231 Collecting protobuf==3.17.3
#0 7.281   Downloading protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
#0 7.850 Collecting gspread==3.1.0
#0 7.898   Downloading gspread-3.1.0-py3-none-any.whl (16 kB)
#0 8.069 Collecting impyla==0.16.0
#0 8.115   Downloading impyla-0.16.0.tar.gz (235 kB)
#0 9.859 Collecting influxdb==5.2.3
#0 9.905   Downloading influxdb-5.2.3-py2.py3-none-any.whl (73 kB)
#0 10.17 Collecting mysqlclient==1.3.14
#0 10.22   Downloading mysqlclient-1.3.14.tar.gz (91 kB)
#0 11.78 Collecting oauth2client==4.1.3
#0 11.82   Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
#0 11.97 Collecting pyhive==0.6.1
#0 12.01   Downloading PyHive-0.6.1.tar.gz (41 kB)
#0 17.68 Collecting pymongo[srv,tls]==3.9.0
#0 17.73   Downloading pymongo-3.9.0-cp37-cp37m-manylinux1_x86_64.whl (447 kB)
#0 18.08 Collecting vertica-python==0.9.5
#0 18.14   Downloading vertica_python-0.9.5-py2.py3-none-any.whl (137 kB)
#0 18.50 Collecting td-client==1.0.0
#0 18.55   Downloading td_client-1.0.0-py3-none-any.whl (78 kB)
#0 19.24 Collecting pymssql==2.1.4
#0 19.29   Downloading pymssql-2.1.4-cp37-cp37m-manylinux1_x86_64.whl (1.4 MB)
#0 19.84 Collecting dql==0.5.26
#0 19.89   Downloading dql-0.5.26-py2.py3-none-any.whl (53 kB)
#0 20.18 Collecting dynamo3==0.4.10
#0 20.23   Downloading dynamo3-0.4.10-py2.py3-none-any.whl (34 kB)
#0 24.51 Collecting boto3<1.11.0,>=1.10.0
#0 24.56   Downloading boto3-1.10.50-py2.py3-none-any.whl (128 kB)
#0 29.86 Collecting botocore<1.14.0,>=1.13
#0 29.91   Downloading botocore-1.13.50-py2.py3-none-any.whl (5.9 MB)
#0 31.30 Collecting sasl>=0.1.3
#0 31.36   Downloading sasl-0.3.1.tar.gz (44 kB)
#0 32.61 Collecting thrift>=0.8.0
#0 32.65   Downloading thrift-0.16.0.tar.gz (59 kB)
#0 34.00 Collecting thrift_sasl>=0.1.0
#0 34.05   Downloading thrift_sasl-0.4.3-py2.py3-none-any.whl (8.3 kB)
#0 34.40 Collecting cassandra-driver==3.21.0
#0 34.47   Downloading cassandra_driver-3.21.0-cp37-cp37m-manylinux1_x86_64.whl (4.2 MB)
#0 35.44 Collecting memsql==3.0.0
#0 35.49   Downloading memsql-3.0.0.tar.gz (22 kB)
#0 36.96 Collecting atsd_client==3.0.5
#0 37.00   Downloading atsd_client-3.0.5-py3-none-any.whl (32 kB)
#0 37.18 Collecting simple_salesforce==0.74.3
#0 37.23   Downloading simple_salesforce-0.74.3-py2.py3-none-any.whl (21 kB)
#0 37.82 Collecting PyAthena>=1.5.0
#0 37.88   Downloading PyAthena-2.5.2-py3-none-any.whl (40 kB)
#0 38.23 Collecting pymapd==0.19.0
#0 38.28   Downloading pymapd-0.19.0.tar.gz (6.4 MB)
#0 52.01 Collecting qds-sdk>=1.9.6
#0 52.06   Downloading qds_sdk-1.16.1.tar.gz (76 kB)
#0 53.52 Collecting ibm-db>=2.0.9
#0 53.57   Downloading ibm_db-3.1.1.tar.gz (1.1 MB)
#0 54.47   Installing build dependencies: started
#0 62.53   Installing build dependencies: finished with status 'done'
#0 62.54   Getting requirements to build wheel: started
#0 79.77   Getting requirements to build wheel: finished with status 'error'
#0 79.77   ERROR: Command errored out with exit status 1:
#0 79.77    command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2vm7cexf
#0 79.77        cwd: /tmp/pip-install-r5zcp4ui/ibm-db
#0 79.77   Complete output (30 lines):
#0 79.77   Detected 64-bit Python
#0 79.77   Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
#0 79.77   Traceback (most recent call last):
#0 79.77     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
#0 79.77       main()
#0 79.77     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
#0 79.77       json_out['return_val'] = hook(**hook_input['kwargs'])
#0 79.77     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
#0 79.77       return hook(config_settings)
#0 79.77     File "/tmp/pip-build-env-cdpi13p9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 178, in get_requires_for_build_wheel
#0 79.77       config_settings, requirements=['wheel'])
#0 79.77     File "/tmp/pip-build-env-cdpi13p9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
#0 79.77       self.run_setup()
#0 79.77     File "/tmp/pip-build-env-cdpi13p9/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
#0 79.77       exec(compile(code, __file__, 'exec'), locals())
#0 79.77     File "setup.py", line 241, in <module>
#0 79.77       file_stream = BytesIO(request.urlopen(url, context=context).read())
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
#0 79.77       return opener.open(url, data, timeout)
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
#0 79.77       response = meth(req, response)
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
#0 79.77       'http', request, response, code, msg, hdrs)
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
#0 79.77       return self._call_chain(*args)
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
#0 79.77       result = func(*args)
#0 79.77     File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
#0 79.77       raise HTTPError(req.full_url, code, msg, hdrs, fp)
#0 79.77   urllib.error.HTTPError: HTTP Error 403: Forbidden
#0 79.77   ----------------------------------------
#0 79.77 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2vm7cexf Check the logs for full command output.
------
failed to solve: executor failed running [/bin/sh -c if [ "x$skip_ds_deps" = "x" ] ; then pip install -r requirements_all_ds.txt ; else echo "Skipping pip install -r requirements_all_ds.txt" ; fi]: exit code: 1
```
</details>

### Steps to Reproduce

1. `git clone https://github.com/getredash/redash.git`
2. `cd redash`
3. `docker-compose up -d`

### Technical details:

* Redash Version: master
* Browser/OS: MacOS on M1 Pro
* How did you install Redash: via git

**Comment by toomore** [comment]
The same issue as me. Download the `ODBC` file from `https://databricks.com/wp-content/uploads/2.6.10.1010-2/SimbaSparkODBC-2.6.10.1010-2-Debian-64bit.zip` will return `406 Not Acceptable`.

## Technical details:
- Redash Version: master
- Browser/OS: MacOS 12.3.1 on Intel Core i7
- How did you install Redash: git clone from github

**Comment by imryche** [comment]
Try VPN :)

**Comment by ruslan-gennadievich** [comment]
Or leave fucking country :)

**Comment by susodapop** [comment]
I think long-term we need a solution for selectively installing dependencies on an as-needed basis for different query runners. As our list of supported databases grew these errors become more likely. The solution for the moment is to either comment-out the offending packages from `requirements_all_ds.txt` / `Dockerfile` or use `docker-compose build --build-arg skip_ds_deps=1` to skip them entirely.

**Comment by sunyaf** [comment]
> https://databricks.com/wp-content/uploads/2.6.10.1010-2/SimbaSparkODBC-2.6.10.1010-2-Debian-64bit.zip

hi,I met the same problem, how did you solve it

**Comment by vinodpandey** [comment]
@sunyaf you can comment out below lines from Dockerfile and rebuild

```
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install  -y --no-install-recommends msodbcsql17 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl "$databricks_odbc_driver_url" --output /tmp/simba_odbc.zip \
    && chmod 600 /tmp/simba_odbc.zip \
    && unzip /tmp/simba_odbc.zip -d /tmp/ \
    && dpkg -i /tmp/SimbaSparkODBC-*/*.deb \
    && printf "[Simba]\nDriver = /opt/simba/spark/lib/64/libsparkodbc_sb64.so" >> /etc/odbcinst.ini \
    && rm /tmp/simba_odbc.zip \
    && rm -rf /tmp/SimbaSparkODBC*; fi
```

**Comment by mstyne** [comment]
Changing
```
curl "$databricks_odbc_driver_url" --output /tmp/simba_odbc.zip
```
to
```
curl -L "$databricks_odbc_driver_url" --output /tmp/simba_odbc.zip
```
Will allow curl to follow the 301 redirect, and download the file. Good luck!

**Comment by susodapop** [comment]
Thanks @mstyne 

This change has now been merged to `master` in https://github.com/getredash/redash/pull/5814
