### ISSUE TITLE
Can't add new users to redash dashboard

### ISSUE THREAD

**Issue by mohamedelbahr** [getredash/redash#5762]
Suddenly i can't create new user on redash dashboard, i got below error on web container 
```
[2022-05-26 13:52:02,060][PID:22][ERROR][redash.app] Exception on /api/users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 442, in __inner
    return obj(*a, **k)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/redash/handlers/base.py", line 33, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/users.py", line 158, in post
    group_ids=[self.current_org.default_group.id],
AttributeError: 'NoneType' object has no attribute 'id'
```
I was using version 9 then upgraded to 10 hopefully that would get resolved but still the same 
Note: It was working before

- [Forum](https://disucss.redash.io)
- [Knowledge Base](https://redash.io/help)

**Comment by susodapop** [comment]
Did you recently change the names of the groups in your organization? The error seems like you may have renamed the `default` group to something else.
