### ISSUE TITLE
watchdog  OSError: Function not implemented 

### ISSUE THREAD

**Issue by sunyaf** [getredash/redash#5804]
when I  exec "docker-compose up -d" on macos M1
redash_scheduler and redash_work print error
Traceback (most recent call last):

  File "/usr/local/bin/watchmedo", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 573, in main

    parser.dispatch()

  File "/usr/local/lib/python3.7/site-packages/argh/helpers.py", line 55, in dispatch

    return dispatch(self, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch

    for line in lines:

  File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command

    for line in result:

  File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 231, in _call

    result = function(namespace_obj)

  File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 550, in auto_restart

    observe_with(observer, handler, args.directories, args.recursive)

  File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 119, in observe_with

    observer.start()

  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 255, in start

    emitter.start()

  File "/usr/local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 110, in start

    self.on_thread_start()

  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start

    self._inotify = InotifyBuffer(path, self.watch.is_recursive)

  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__

    self._inotify = Inotify(path, recursive)

  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 188, in __init__

    Inotify._raise_error()

  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 417, in _raise_error

    raise OSError(os.strerror(err))

OSError: Function not implemented

**Comment by susodapop** [comment]
What version of Redash? What operating system?

**Comment by sunyaf** [comment]
v10.1.0   Latest,
Can you help solve this problem? It seems very troublesome to install once now

my email is syf_5566@163.com

**Comment by sunyaf** [comment]
> 

v10.1.0 Latest,
Can you help solve this problem? It seems very troublesome to install once now

my email is [syf_5566@163.com](mailto:syf_5566@163.com)

**Comment by sunyaf** [comment]
> What version of Redash? What operating system?

watchdog==0.9.0

**Comment by sunyaf** [comment]
> What version of Redash? What operating system?

my operating system
Apple M1 Pro

**Comment by susodapop** [comment]
We're aware of issues building on Apple Silicon using the master branch. Try building using the fix-m1-build branch here: https://github.com/getredash/redash/tree/fix-m1-build

**Comment by susodapop** [comment]
Any news?

**Comment by JonathanSamelson** [comment]
Hi,
Using the branch `fix-m1-build`did not help in my case, but the instructions in this blog made it work:
https://stephanmeijer.com/Redash-M1-Mac/
