### ISSUE TITLE
redash start failed via docker-compose up

### ISSUE THREAD

**Issue by Zijianlalala** [getredash/redash#5844]
### Issue Summary

I run `docker-compose up -d`, the server failed to run. It seems like in server container it doesn't have the permission to exec /app/manage.py, and I dont know how to add permission to it.

The logs:
> server_1     | /app/bin/docker-entrypoint: 101: exec: /app/manage.py: Permission denied
worker_1     | Starting dev RQ worker...
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/bin/watchmedo", line 8, in <module>
worker_1     |     sys.exit(main())
worker_1     |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 573, in main
worker_1     |     parser.dispatch()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/argh/helpers.py", line 55, in dispatch
worker_1     |     return dispatch(self, *args, **kwargs)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
worker_1     |     for line in lines:
worker_1     |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
worker_1     |     for line in result:
worker_1     |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 231, in _call
worker_1     |     result = function(namespace_obj)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 548, in auto_restart
worker_1     |     handler.start()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/watchdog/tricks/__init__.py", line 147, in start
worker_1     |     self.process = subprocess.Popen(self.command, preexec_fn=os.setsid)
worker_1     |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
worker_1     |     restore_signals, start_new_session)
worker_1     |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
worker_1     |     raise child_exception_type(errno_num, err_msg, err_filename)
worker_1     | PermissionError: [Errno 13] Permission denied: './manage.py'
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/bin/watchmedo", line 8, in <module>
scheduler_1  |     sys.exit(main())
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 573, in main
scheduler_1  |     parser.dispatch()
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/argh/helpers.py", line 55, in dispatch
scheduler_1  |     return dispatch(self, *args, **kwargs)
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
scheduler_1  |     for line in lines:
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
scheduler_1  |     for line in result:
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 231, in _call
scheduler_1  |     result = function(namespace_obj)
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 548, in auto_restart
scheduler_1  |     handler.start()
scheduler_1  |   File "/usr/local/lib/python3.7/site-packages/watchdog/tricks/__init__.py", line 147, in start
scheduler_1  |     self.process = subprocess.Popen(self.command, preexec_fn=os.setsid)
scheduler_1  |   File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
scheduler_1  |     restore_signals, start_new_session)
scheduler_1  |   File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
scheduler_1  |     raise child_exception_type(errno_num, err_msg, err_filename)
scheduler_1  | PermissionError: [Errno 13] Permission denied: './manage.py'
redash-master_worker_1 exited with code 1
redash-master_scheduler_1 exited with code 1

### Steps to Reproduce

1. copy source code to linux
2. run docker-compose up -d

### Technical details:

* Redash Version: the Latest redash-master
* Browser/OS: Red Hat 4.8.5-36
* How did you install Redash: download the zip file from github

**Comment by Zijianlalala** [comment]
I change to run it on Win10, and it works.
