### ISSUE TITLE
Error when hovering on a line chart with many data points.

### ISSUE THREAD

**Issue by johncheng-crypto** [getredash/redash#5884]
### Issue Summary

When mouse hover a line chart with ~50k data point, the browser goes to the internal error page.
Here is the error message from the browser.
```
ErrorMessage.jsx:41 TypeError: Cannot read properties of null (reading 'textContent')
    at Z.text (d3.js:788:15)
    at t.convertToTspans (svg_text_utils.js:29:24)
    at Z.call (d3.js:975:14)
    at SVGGElement.<anonymous> (hover.js:1053:18)
    at d3.js:962:16
    at pe (d3.js:968:30)
    at Z.each (d3.js:961:12)
    at C (hover.js:942:17)
    at hover.js:662:23
    at hover.js:75:22
et @ ErrorMessage.jsx:41
qi @ react-dom.production.min.js:153
gs @ react-dom.production.min.js:261
ul @ react-dom.production.min.js:246
sl @ react-dom.production.min.js:246
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Wo @ react-dom.production.min.js:122
Go @ react-dom.production.min.js:123
Yo @ react-dom.production.min.js:122
qs @ react-dom.production.min.js:230
ma @ react-dom.production.min.js:163
e @ index.jsx:20
```

### Steps to Reproduce

1. Open a query with a line chart with lots of data points (in my case 50k)
2. Mouse hover for a few data points

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v10.1.0 
* Browser/OS: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
* How did you install Redash: Docker

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this
