### ISSUE TITLE
Cannot upgrade db from v8 to v10

### ISSUE THREAD

**Issue by paoloxide** [getredash/redash#5900]
### Issue Summary

I have a Redash v8 installed in our production and I recently cloned this and tried upgrading to v10.

The Redash v8 and v10 apps are in a Kubernetes setup. 

The database for v8 has also been cloned (created new db and restore the backup from v8) for the v10 app, however when I am trying to upgrade the database as described in this documentation: https://github.com/getredash/redash/releases/tag/v10.0.0, I encounter exceptions wherein certain columns in a relation are already existing.

`$ python /app/manage.py db upgrade
[2023-02-28 15:17:53,743][PID:189][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2023-02-28 15:17:53,744][PID:189][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2023-02-28 15:17:53,768][PID:189][INFO][alembic.runtime.migration] Running upgrade 65fc9ede4746 -> d1eae8b9893e, add Query.schedule_failures
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateColumn: column "schedule_failures" of relation "queries" already exist`

### Steps to Reproduce

1. `python manage.py db upgrade`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v8 and v10
* Browser/OS: Linux
* How did you install Redash: via Kubernetes setup

**Comment by lucasfcnunes** [comment]
Did you try with our latest release https://github.com/getredash/redash/releases/tag/v10.1.0 (docker hub image: redash/redash:10.1.0.b50633?)
