### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by hantmac** [getredash/redash#5927]
Just clone the redash and `docker-compose up` but got the following error:

```
Collecting pyhive==0.6.1
  Downloading PyHive-0.6.1.tar.gz (41 kB)
Collecting pymongo[srv,tls]==3.9.0
  Downloading pymongo-3.9.0.tar.gz (701 kB)
Collecting vertica-python==0.9.5
  Downloading vertica_python-0.9.5-py2.py3-none-any.whl (137 kB)
Collecting td-client==1.0.0
  Downloading td_client-1.0.0-py3-none-any.whl (78 kB)
Collecting pymssql==2.1.4
  Downloading pymssql-2.1.4.tar.gz (691 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-01i12b3q/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-01i12b3q/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l0sgeo3d
         cwd: /tmp/pip-install-01i12b3q/pymssql/
    Complete output (7 lines):
    /usr/local/lib/python3.7/site-packages/setuptools/dist.py:51: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-01i12b3q/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c if [ "x$skip_ds_deps" = "x" ] ; then pip install -r requirements_all_ds.txt ; else echo "Skipping pip install -r requirements_all_ds.txt" ; fi' returned a non-zero code: 1
ERROR: Service 'server' failed to build : Build failed

```

And I use M1 mac.

**Comment by lucasfcnunes** [comment]
I think bumping up pymssql version solves this.
- [pymssql/ChangeLog.rst](https://github.com/pymssql/pymssql/blob/master/ChangeLog.rst#version-215---2020-09-17---mikhail-terekhov:~:text=Use%20correct%20language%20level%20for%20building%20Cython%20extension.)
- https://github.com/getredash/redash/issues/5910#issuecomment-1474972312 (pymssql = "^2.2.7" builds)

**Comment by hantmac** [comment]
Thanks for your help!
