### ISSUE TITLE
Need to upgrade redis-py

### ISSUE THREAD

**Issue by noodles23** [getredash/redash#606]
Hey. When we run Redash on AWS it installs fine.

If you try to install on other cloud providers (DO + Vultr), the installation results in a login page where after logging in, it returns a "internal server error". 

It's seems to be the same type of error seen in a previous google group post
https://groups.google.com/forum/#!topic/redash-users/pVJDUYneuY0

Log is attached.

2015-10-11 08:19:44 [20649] [INFO] Starting gunicorn 18.0
2015-10-11 08:19:44 [20649] [INFO] Listening at: http://127.0.0.1:5000 (20649)
2015-10-11 08:19:44 [20649] [INFO] Using worker: sync
2015-10-11 08:19:44 [20672] [INFO] Booting worker with pid: 20672
2015-10-11 08:19:44 [20673] [INFO] Booting worker with pid: 20673
2015-10-11 08:19:44 [20674] [INFO] Booting worker with pid: 20674
2015-10-11 08:19:44 [20675] [INFO] Booting worker with pid: 20675
[2015-10-11 08:19:45,872][PID:20673][WARNING][redash.query_runner.hive_ds] Missing dependencies. Please install pyhive.
[2015-10-11 08:19:45,885][PID:20672][WARNING][redash.query_runner.hive_ds] Missing dependencies. Please install pyhive.
[2015-10-11 08:19:45,885][PID:20672][WARNING][redash.query_runner.hive_ds] You can use pip: pip install pyhive
[2015-10-11 08:19:45,886][PID:20673][WARNING][redash.query_runner.hive_ds] You can use pip: pip install pyhive
[2015-10-11 08:19:45,975][PID:20674][WARNING][redash.query_runner.hive_ds] Missing dependencies. Please install pyhive.
[2015-10-11 08:19:45,993][PID:20674][WARNING][redash.query_runner.hive_ds] You can use pip: pip install pyhive
[2015-10-11 08:19:46,035][PID:20675][WARNING][redash.query_runner.hive_ds] Missing dependencies. Please install pyhive.
[2015-10-11 08:19:46,044][PID:20675][WARNING][redash.query_runner.hive_ds] You can use pip: pip install pyhive
[2015-10-11 08:19:46,356][PID:20673][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
[2015-10-11 08:19:46,359][PID:20672][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
[2015-10-11 08:19:46,433][PID:20674][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
[2015-10-11 08:19:46,495][PID:20675][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
[2015-10-11 08:20:10,253][PID:20674][ERROR][redash.wsgi] Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 251, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/current/redash/controllers.py", line 90, in login
    login_user(user, remember=remember)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 687, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/opt/redash/current/redash/authentication.py", line 86, in log_user_logged_in
    record_event.delay(event)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 555, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 351, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 422, in __call__
    value = self.__value__ = self.__contract__()
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 756, in default_channel
    self.connection
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 429, in __init__
    self.Client = self._get_client()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 825, in _get_client
    'You have {0.__version__}'.format(redis))
VersionMismatch: Redis transport requires redis-py versions 2.10.0 or later. You have 2.7.5

**Comment by arikfr** [comment]
Did you have anything else installed on this server before? If you did, you might want to run `sudo pip install -U -r requirements.txt` (at `/opt/redash/current`) to make sure you have current versions of the required packages.

Also, if you have the output of the bootstrap script run it will be helpful.

**Comment by arikfr** [comment]
I just ran the bootstrap script on a new instance, and stumbled at the same issue. Looks like one of the underlying dependencies of Celery requires newer version of redis-py now.

I will update requirements.txt to reflect that, but you can fix this on your instance by running: `sudo pip install -U redis`.

Sorry for the trouble.
