### ISSUE TITLE
Redash Server error when attempting to use TO_TIMESTAMP in a query against a PostgreSQL DB

### ISSUE THREAD

**Issue by muks198** [getredash/redash#6204]
### Issue Summary

Timestamp data (from Unix Epoch) is stored in a Postgres DB in an integer column. Running the following command works inconsistently if at all:

```
SELECT another_column, TIMEZONE('UTC', TO_TIMESTAMP(updated_at)) FROM some_table
```

The following error is reported by Redash Server when executing the above,

```
[2023-07-20 12:23:55,439] ERROR in app: Exception on /api/queries/3/results [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 67, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/query_results.py", line 197, in post
    return run_query(query.parameterized, parameter_values, query.data_source, query_id, max_age)
  File "/app/redash/handlers/query_results.py", line 68, in run_query
    "Query ID": query_id
  File "/app/redash/tasks/queries.py", line 117, in enqueue_query
    if job.ready():
  File "/app/redash/tasks/queries.py", line 93, in ready
    return self._async_result.ready()
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 313, in ready
    return self.state in self.backend.READY_STATES
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 473, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 412, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 386, in get_task_meta
    meta = self._get_task_meta_for(task_id)
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 730, in _get_task_meta_for
    return self.decode_result(meta)
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 305, in decode_result
    return self.meta_from_decoded(self.decode(payload))
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 301, in meta_from_decoded
    meta['result'] = self.exception_to_python(meta['result'])
  File "/usr/local/lib/python2.7/site-packages/celery/backends/base.py", line 281, in exception_to_python
    exc = cls(*exc_msg if isinstance(exc_msg, tuple) else exc_msg)
TypeError: __init__() takes at least 4 arguments (2 given)
```

Note: The error reported to a user on the Redash dashboard amounts to "Internal Server Error".

A few things:
* Database is accessible
* Query functions as expected when using pgAdmin (with the same credentials)
* Query works as expected to return raw data when dropping TIMEZONE/TO_TIMSTAMP

Any help would be appreciated.

Cheers,
M.

### Steps to Reproduce

1. Create a Postgresql table with a column that stores an integer representing seconds since Unix epoch (python example to generate timestamps - i drop microseconds hence use of an integer column: datetime.now(tz=timezone.utc).timestamp())
2. Create a Redash query as above
3. Execute with / without using TIMEZONE/TO_TIMESTAMP

### Technical details:

* Redash Version: redash/redash:latest
* Browser/OS: Firefox/Windows
* How did you install Redash: Docker

**Comment by muks198** [comment]
It is using the latest tagged images available on Dockerhub that was published ~4yrs ago: https://hub.docker.com/r/redash/redash/tags

I followed these instructions: https://redash.io/help/open-source/setup

**Comment by konnectr** [comment]
You have installed a docker image in which python 2.7 was installed . Python 2.7 is outdated. We have restarted Redash under community management but have not released new versions yet . I think we need to close the issue, due to the fact that it is python 2.7 . you can use version 10+ in docker hub https://hub.docker.com/r/redash/redash/tags?page=1&name=10.1.0.b50633
