### ISSUE TITLE
Cannot login using SAML when User does not have LAST_NAME.

### ISSUE THREAD

**Issue by Zuhdan** [getredash/redash#6301]
i just put the error log.

[2023-07-27 09:24:43,287] ERROR in app: Exception on /saml/callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/redash/authentication/saml_auth.py", line 82, in idp_initiated
    name = "%s %s" % (authn_response.ava['FirstName'][0], authn_response.ava['LastName'][0])
KeyError: 'LastName'

**Comment by konnectr** [comment]
You are using a very old version. This can be seen in python 2.7, which is no longer supported either.

**Comment by Zuhdan** [comment]
> You are using a very old version. This can be seen in python 2.7, which is no longer supported either.

yes you are correct.
currently i'm using this image.

![image](https://github.com/getredash/redash/assets/6513361/ac8b6a1c-1b7f-41b8-a682-10085ded1464)

i will try to use latest image. thank you
