### ISSUE TITLE
Query Search is broken

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#6381]
### Issue Summary

After upgrading to Redash with Python 3.8, search cannot be used.

### Steps to Reproduce

1. Open `/queries` page
2. Try to search something
3. See "Internal Server Error"

### Technical details:

* Redash Version: 4a5c9c2 
* Browser/OS: Safari / Mac Os
* How did you install Redash: k8s

Here are the logs from webserver pod:

```
[2023-08-21 09:11:29,965][PID:1784][ERROR][redash.app] Exception on /api/queries [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: function tsq_parse(unknown, unknown) does not exist
LINE 6: ...up_id IN (2, 1, 8)) AND (queries.search_vector @@ tsq_parse(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/queries.py", line 148, in get
    response = paginate(
  File "/app/redash/handlers/base.py", line 81, in paginate
    count = query_set.count()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3803, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function tsq_parse(unknown, unknown) does not exist
LINE 6: ...up_id IN (2, 1, 8)) AND (queries.search_vector @@ tsq_parse(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT count(*) AS count_1
FROM (SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags
FROM queries LEFT OUTER JOIN users ON users.id = queries.user_id LEFT OUTER JOIN query_results ON query_results.id = queries.latest_query_data_id
WHERE queries.id IN (SELECT DISTINCT queries.id AS anon_2
FROM queries JOIN data_source_groups ON queries.data_source_id = data_source_groups.data_source_id
WHERE queries.is_archived IS false AND data_source_groups.group_id IN (%(group_id_1)s, %(group_id_2)s, %(group_id_3)s)) AND (queries.search_vector @@ tsq_parse(%(tsq_parse_1)s, %(tsq_parse_2)s)) ORDER BY ts_rank_cd(queries.search_vector, tsq_parse(%(tsq_parse_3)s)) DESC) AS anon_1]
[parameters: {'group_id_1': 2, 'group_id_2': 1, 'group_id_3': 8, 'tsq_parse_1': 'pg_catalog.simple', 'tsq_parse_2': 'qweq', 'tsq_parse_3': 'qweq'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-08-21 09:11:29,969][PID:1784][INFO][metrics] method=GET path=/api/queries endpoint=queries status=500 content_type=application/json content_length=36 duration=16.16 query_count=3 query_duration=4.49
```

**Comment by justinclift** [comment]
Thanks, that's pretty clearly a bug. :smile:

```
psycopg2.errors.UndefinedFunction: function tsq_parse(unknown, unknown) does not exist
```

I'm not seeing any mentions of `tsq_parse()` in our code base.

@gaecoli @wlach Is this something either of you would be interested in investigating? :smile:

**Comment by gaecoli** [comment]
> Thanks, that's pretty clearly a bug. 😄
> 
> ```
> psycopg2.errors.UndefinedFunction: function tsq_parse(unknown, unknown) does not exist
> ```
> 
> I'm not seeing any mentions of `tsq_parse()` in our code base.
> 
> @gaecoli @wlach Is this something either of you would be interested in investigating? 😄

OK, i will check it!

**Comment by justinclift** [comment]
Thanks @gaecoli. :smile:

**Comment by gaecoli** [comment]
> Thanks @gaecoli. 😄

I will try to fix it!

**Comment by Krikooo** [comment]
Hello there o/
Any news about a potential fix here ? :)

**Comment by justinclift** [comment]
Thanks @azundo that's AWESOME!

We had to upgrade SQLAlchemy-searchable (no real choice) in order to fix some important security issues (part of a chain of dependencies), and to get that working in short order we just "made it work" in a temporary way with a plan to look at it again properly later.

... which we've not gotten to yet. :innocent:

We should try turning that code into a proper migration (via PR), and test it out.  Sounds like a fairly good starting point anyway.

Actually, are you any good with creating PR's and similar?  If you want to throw that into a suitable PR that'd be welcome too.  If not, we can do it. :smile:

**Comment by azundo** [comment]
I haven't been able to test this - struggling to get a local dev environment set up fully on my Mac - but I think this branch should do it. If you can test it and make sure I've generated the migration right and it runs then I can submit a PR or feel free to just steal it and merge it.

https://github.com/azundo/redash/tree/fix-sqlalchemy-searchable-upgrade
