### ISSUE TITLE
Upgrade to requests 2.6.0 to support Ubuntu 15.10

### ISSUE THREAD

**Issue by Xangis** [getredash/redash#643]
I ran into some trouble running bootstrap.sh on a 64-bit Ubuntu 15.10 machine. This Python exception was thrown:

psql (PostgreSQL) 9.4.5
redis-cli 2.8.17 (git:34ba5439-dirty)
Traceback (most recent call last):
  File "/opt/redash/redash.0.7.1.b1015/manage.py", line 9, in <module>
    from redash import settings, models, __version__
  File "/opt/redash/redash.0.7.1.b1015/redash/__init__.py", line 8, in <module>
    from redash.query_runner import import_query_runners
  File "/opt/redash/redash.0.7.1.b1015/redash/query_runner/__init__.py", line 4, in <module>
    import jsonschema
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 18, in <module>
    from jsonschema.validators import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 70, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

I was able to get past this by upgrading to requests 2.6.0 as described in this StackOverflow issue:

http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

I don't know whether that is the best version of requests to use with redash, but updating it to 2.6.0 allowed me to get past that issue on latest Ubuntu and finish the bootstrap.sh process.

**Comment by arikfr** [comment]
If requests follow sem-ver, than there shouldn't be any backward incompatible changes between version 2.6 and 2.3 (the one in requirements.txt). Once I get the chance to properly test re:dash with requests 2.6.0 then I will update the requirements.

Thanks!

**Comment by asafyish** [comment]
The problem is not in requests, but in debian actually, they removed support for ssl from openssl, then urllib fails, then requests fails.

Upgrading to requests 2.6.0 solves the problem without any noticeable side effects.
