### ISSUE TITLE
Shared queries don't work

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#6496]
### Issue Summary

Embedded query shows an error.

### Steps to Reproduce

1. Create query
2. Click on `Emded elsewhere` -> `Public URL`
3. Open that URL 
4. See `Error: Internal Server Error`

```
[2023-10-03 10:24:37,182][PID:10][ERROR][redash.app] Exception on /api/queries/1696/results [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/query_results.py", line 270, in post
    return run_query(
  File "/app/redash/handlers/query_results.py", line 109, in run_query
    "Username": current_user.get_actual_user(),
AttributeError: 'ApiUser' object has no attribute 'get_actual_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 279, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/query_results.py", line 270, in post
    return run_query(
  File "/app/redash/handlers/query_results.py", line 109, in run_query
    "Username": current_user.get_actual_user(),
AttributeError: 'ApiUser' object has no attribute 'get_actual_user'
```

### Technical details:

* Redash Version: master branch
* How did you install Redash: helm

**Comment by deecay** [comment]
@denisov-vlad 
What is the condition of this happening? I'm at `b13772c4 2023-09-22` of master branch and this doesn't happen.

**Comment by denisov-vlad** [comment]
@deecay Yes, I forgot to mention that the query should include parameters. Without params it works well.
