### ISSUE TITLE
Sharing a dashboard externally lead the problem when you change view parameter

### ISSUE THREAD

**Issue by mindgame73** [getredash/redash#6501]
### Issue Summary

Ubuntu 22.04 / Centos 7 (docker environment)

Dashboard does not load, issue appear as 500 error in network tab  when you trying to change view parameter after you arrive to the page (first time cached version looks normally). 

### Steps to Reproduce

1. Create a dashboard
2. Share externally
3. Copy link 
4. Open up in a new tab
5. You will see it loaded normally
6. Open up network tab devtools
7. Try to change parameter which affect chart/table
8. Dashboard fail with errors on widgets
9. You will see we do call to api and they fail with 500 error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

```
AttributeError: 'ApiUser' object has no attribute 'get_actual_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 279, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/query_results.py", line 270, in post
    return run_query(
  File "/app/redash/handlers/query_results.py", line 109, in run_query
    "Username": current_user.get_actual_user(),
AttributeError: 'ApiUser' object has no attribute 'get_actual_user'
```

Issue appears in the file stored "/app/redash/handlers/query_results.py" : 

```
    if query_result:
        return {"query_result": serialize_query_result(query_result, current_user.is_api_user())}
    else:
        job = enqueue_query(
            query_text,
            data_source,
            current_user.id,
            current_user.is_api_user(),
            metadata={
                "Username": current_user.get_actual_user(),     <------------------ i print out this is <ApiKey: 12>
                "query_id": query_id,
            },
        )
        return serialize_job(job)
```

**Workaround:**

Seems dev externalize this method into users.py and invoke this method right here, but ApiKey doesn't have this method

Replace this code by: 
`"Username": repr(current_user) if current_user.is_api_user() else current_user.email,`

### Technical details:

* Redash Version: 23.09 dev
* Browser/OS: Centos 7 
* How did you install Redash: docker compose

**Comment by mindgame73** [comment]
and don't forget to restart server, issue is gone after
