### ISSUE TITLE
[Bug] Error wile running docker-compose up -d on services: server

### ISSUE THREAD

**Issue by YuriyGavrilov** [getredash/redash#6502]
### Issue Summary

services: server Exited (1)

with this log after first clean start:
`2023-10-07 01:05:50 Traceback (most recent call last):
2023-10-07 01:05:50   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 98, in __getattr__
2023-10-07 01:05:50     ls = self._empty_listeners[name]
2023-10-07 01:05:50 KeyError: 'instrument_class'
2023-10-07 01:05:50 
2023-10-07 01:05:50 During handling of the above exception, another exception occurred:
2023-10-07 01:05:50 
2023-10-07 01:05:50 Traceback (most recent call last):
2023-10-07 01:05:50   File "/app/manage.py", line 6, in <module>
2023-10-07 01:05:50     from redash.cli import manager
2023-10-07 01:05:50   File "/app/redash/__init__.py", line 53, in <module>
2023-10-07 01:05:50     import_query_runners(settings.QUERY_RUNNERS)
2023-10-07 01:05:50   File "/app/redash/query_runner/__init__.py", line 437, in import_query_runners
2023-10-07 01:05:50     __import__(runner_import)
2023-10-07 01:05:50   File "/app/redash/query_runner/query_results.py", line 7, in <module>
2023-10-07 01:05:50     from redash import models
2023-10-07 01:05:50   File "/app/redash/models/__init__.py", line 31, in <module>
2023-10-07 01:05:50     from redash.models.base import (
2023-10-07 01:05:50   File "/app/redash/models/base.py", line 39, in <module>
2023-10-07 01:05:50     make_searchable(db.metadata, options={"regconfig": "pg_catalog.simple"})
2023-10-07 01:05:50   File "/usr/local/lib/python3.7/site-packages/sqlalchemy_searchable/__init__.py", line 563, in make_searchable
2023-10-07 01:05:50     mapper, 'instrument_class', manager.process_mapper
2023-10-07 01:05:50   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/api.py", line 102, in listen
2023-10-07 01:05:50     _event_key(target, identifier, fn).listen(*args, **kw)
2023-10-07 01:05:50   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/registry.py", line 204, in listen
2023-10-07 01:05:50     dispatch_collection = getattr(target.dispatch, identifier)
2023-10-07 01:05:50   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/event/base.py", line 100, in __getattr__
2023-10-07 01:05:50     raise AttributeError(name)
2023-10-07 01:05:50 AttributeError: instrument_class
` 

### Steps to Reproduce

1. `git clone https://github.com/getredash/redash.git
cd redash/`
2. `touch .env`
3. `docker-compose up -d`

after that services: server Exited (1)

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: Safari
* How did you install Redash: used this link https://redash.io/help/open-source/dev-guide/docker

**Comment by guidopetri** [comment]
Hi! Are you trying to set up Redash for development purposes? If so, that documentation is out of date - the [wiki](https://github.com/getredash/redash/wiki/Local-development-setup) is our currently-working docs.

**Comment by justinclift** [comment]
Note that I've slightly adjusted the formatting of the initial post, to improve readability. :smile:
