### ISSUE TITLE
Enable TLS between Redash and Redis

### ISSUE THREAD

**Issue by ferduz** [getredash/redash#6565]
### **Summary**
Redis now supports TLS clients, so we should enable TLS by default.

### **Motivation**
Data transmitted between Redash components and Redis cache is potentially sensitive and therefore, the connection should be safely encrypted.

### **Proposal**
Enable TLS between Redis and Redash by default.

**Comment by guidopetri** [comment]
This sounds reasonable to me. We'll have to make sure that upgrading the Redis library version doesn't break anything, and also update the docker compose files.

I don't think we need to make this an option, but can be convinced otherwise (in case someone _really_ wants to not use TLS, for some reason).

**Comment by justinclift** [comment]
For connecting between Redash and Redis for internal use (eg as our data cache stuff), it's probably fine to just turn on TLS in our config and go with that.  We control both ends of that connection after all.

**Comment by ymitsos** [comment]
Seems that the solution of this problem was straight forward, by using the right URI (rediss:// instead of redis://) the Redis library utilizes a TLS connection.

**Comment by masayuki038** [comment]
Yes. Therefore, I think it is enable by default...

@ferduz Do these comments in this issue fit the points you want to discuss? If your point lies elsewhere, please let us know.

**Comment by ferduz** [comment]
@masayuki038 solution purposed by @ymitsos works but now I have problems with scheduler deployment:
`Starting RQ scheduler...
Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/redash/cli/rq.py", line 30, in scheduler
    schedule_periodic_jobs(jobs)
  File "/app/redash/tasks/schedule.py", line 106, in schedule_periodic_jobs
    set([job.id for job in rq_scheduler.get_jobs()])
  File "/app/redash/tasks/schedule.py", line 106, in <listcomp>
    set([job.id for job in rq_scheduler.get_jobs()])
  File "/usr/local/lib/python3.7/site-packages/rq_scheduler/scheduler.py", line 320, in get_jobs
    job_id = job_id.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'`

I found this other issue that can be related https://github.com/getredash/redash/issues/6424
will continue digging.

**Comment by masayuki038** [comment]
@ferduz Thanks for your report. It is very helpful.
I agree with you. It seems to be `decode_responses=True` issue...

**Comment by ferduz** [comment]
@masayuki038 this is what it works :
`externalRedis: "rediss://master.xxxxxx.xxxxx.region.cache.amazonaws.com:6379/0"`
thanks @ymitsos

**Comment by masayuki038** [comment]
@ferduz Thanks for your report! Good contribution.
