### ISSUE TITLE
DB migration failed (change type of json fields from varchar to json) in the latest Docker image

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#6706]
### Issue Summary

After upgrading to the latest Redash Docker image, the db migration process failed.
It might be related to the recent commit ec1c4d07deca7b9b8a49504a28f0a00a0feb59ab.

### Steps to Reproduce

1. Update to the latest Docker image.
2. run command `docker-compose run --rm server manage db upgrade`.
```
[2024-01-15 21:56:29,506][PID:3862][INFO][xmlschema] Resource 'XMLSchema.xsd' is already loaded
[2024-01-15 21:56:30,190][PID:3862][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2024-01-15 21:56:30,190][PID:3862][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2024-01-15 21:56:30,243][PID:3862][INFO][alembic.runtime.migration] Running upgrade 7ce5925f832b -> 7205816877ec, change type of json fields from varchar to json
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: result of USING clause for column "data" cannot be cast automatically to type jsonb
HINT:  You might need to add an explicit cast.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    manager()
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/venv/lib/python3.8/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/venv/lib/python3.8/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "migrations/env.py", line 85, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/redash/migrations/versions/7205816877ec_change_type_of_json_fields_from_varchar_.py", line 62, in upgrade
    op.alter_column('query_results', 'data',
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/venv/lib/python3.8/site-packages/alembic/operations/ops.py", line 1943, in alter_column
    return operations.invoke(alt)
  File "/venv/lib/python3.8/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
  File "/venv/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 53, in alter_column
    operations.impl.alter_column(
  File "/venv/lib/python3.8/site-packages/alembic/ddl/postgresql.py", line 174, in alter_column
    self._exec(
  File "/venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) result of USING clause for column "data" cannot be cast automatically to type jsonb
HINT:  You might need to add an explicit cast.

[SQL: ALTER TABLE query_results ALTER COLUMN data TYPE JSONB USING data::text]
(Background on this error at: http://sqlalche.me/e/13/f405)


```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: latest
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by justinclift** [comment]
In theory (!), this should be fixed a few hours ago with #6706.

If you update your Redash docker to the latest source code (or latest `preview` image), then it *should* work again now. :smile:

**Comment by myonlylonely** [comment]
> In theory (!), this should be fixed a few hours ago with #6706.
> 
> If you update your Redash docker to the latest source code (or latest `preview` image), then it _should_ work again now. 😄

@justinclift After pulling the latest image, another error:

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.ProgramLimitExceeded) total size of jsonb array elements exceeds the maximum of 268435455 bytes
```

**Comment by justinclift** [comment]
> 268435455 bytes

Um, isn't that about 1/4 of a Gigabyte?

That's pretty far past a "reasonable" amount of data to be storing in a result, let alone wanting to display on a web page.

Well, that's my first thought anyway. :wink:

What's the scenario where you're trying to make that happen?

**Comment by myonlylonely** [comment]
Querying a very large table, and export the table to a Excel file. That is a very common use case.

**Comment by myonlylonely** [comment]
256 MB is very small, it does not only limit the rows than can contain in the array, it also limit the size of a single row.
If I have a chat log table, I do not need a lot of rows to reach the limit, since a single row could contains long text.

**Comment by justinclift** [comment]
Interesting.  Hadn't thought of that.  That makes sense for some workflows I guess.

***BUT*** it sounds pretty dangerous (!) to me for a different reason.

Excel itself has a maximum number of rows and columns it can handle:

https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

So, modern Excel is `1,048,576 rows by 16,384 columns` (earlier Excel versions have lower limits).

It *sounds* to me like there's a process in place to get results out of Redash, import them into Excel, then "do stuff" in Excel (and potentially other software) after that.

If you're getting near those limits already, then you should probably figure out a new workflow to achieve your aims before you hit those limits.

In the meantime though, the maximum size of data can probably be changed by using different settings when the database is compiled.  I'll have to check, as it *might* be workable to do.  Will need to investigate and think it over.

**Comment by justinclift** [comment]
> May be we should not change all text fields to JSON?

Yeah, that could be the other direction to take as well.

**Comment by myonlylonely** [comment]
It does need to have so many rows, a table that contains a lot of columns could make the limit a lot easier to reach.

**Comment by justinclift** [comment]
Sure.  The number of columns isn't unlimited in Excel either.

I *think* we'll probably have to investigate rolling back the jsonb change, as compiling a new version of PostgreSQL with a raised block size is going to effect everyone in unpredictable ways.

**Comment by AndrewChubatiuk** [comment]
@myonlylonely could you please try #6713?

**Comment by myonlylonely** [comment]
@AndrewChubatiuk 
When I query results, I got a Internel server error:

```
[2024-01-17 10:49:54,442][PID:203][ERROR][redash.app] Exception on /api/query_results/6033183 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/query_results.py", line 314, in get
    query_result = get_object_or_404(models.QueryResult.get_by_id_and_org, query_result_id, self.current_org)
  File "/app/redash/handlers/base.py", line 72, in get_object_or_404
    rv = fn(*args, **kwargs)
  File "/app/redash/models/mixins.py", line 28, in get_by_id_and_org
    return query.one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 601, in _instance
    state.manager.dispatch.load(state, context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/mutable.py", line 462, in load
    val = cls.coerce(key, val)
  File "/app/redash/models/types.py", line 41, in coerce
    return Mutable.coerce(key, value)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/mutable.py", line 414, in coerce
    raise ValueError(msg % (key, type(value)))
ValueError: Attribute 'data' does not accept objects of type <class 'str'>
```

**Comment by myonlylonely** [comment]
@justinclift It seems the last commit in the pull request fix the issue.

**Comment by AndrewChubatiuk** [comment]
@myonlylonely please try the latest changes once again

**Comment by justinclift** [comment]
The fix for this has been merged, and should be in the `preview` image on Docker Hub now.

@myonlylonely Would you be ok to re-test with that, just to make super sure things are ok now? :smile:

**Comment by myonlylonely** [comment]
@justinclift 
Now the migration failed again.

```
[2024-01-18 05:19:01,412][PID:1][INFO][xmlschema] Resource 'XMLSchema.xsd' is already loaded
[2024-01-18 05:19:02,215][PID:1][INFO][alembic.runtime.migration] Context impl PostgresqlImpl.
[2024-01-18 05:19:02,215][PID:1][INFO][alembic.runtime.migration] Will assume transactional DDL.
[2024-01-18 05:19:02,234][PID:1][INFO][alembic.runtime.migration] Running upgrade 7ce5925f832b -> 7205816877ec, change type of json fields from varchar to json
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: default for column "options" cannot be cast automatically to type jsonb


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 9, in <module>
    manager()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "migrations/env.py", line 85, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/app/migrations/versions/7205816877ec_change_type_of_json_fields_from_varchar_.py", line 22, in upgrade
    op.alter_column('queries', 'options',
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/ops.py", line 1943, in alter_column
    return operations.invoke(alt)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 53, in alter_column
    operations.impl.alter_column(
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/postgresql.py", line 174, in alter_column
    self._exec(
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) default for column "options" cannot be cast automatically to type jsonb

[SQL: ALTER TABLE queries ALTER COLUMN options TYPE JSONB USING options::jsonb]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by AndrewChubatiuk** [comment]
@myonlylonely how did you apply migrations?

**Comment by myonlylonely** [comment]
@AndrewChubatiuk 

This output is generated by the migrations itself.

**Comment by AndrewChubatiuk** [comment]
and what is an output of \d+ queries in postgresql? cause before you you didn’t have such an issue and this migration occurs before one, which was for query_results data

**Comment by myonlylonely** [comment]
@AndrewChubatiuk 
I think it might related to the downgrade process.
I first run the downgrade, then the upgrade

**Comment by myonlylonely** [comment]
```
************************************
PostgreSQL data directory: /var/lib/postgresql/data
************************************
psql (15.3)
Type "help" for help.

postgres=# \d+
                                                    List of relations
 Schema |               Name               |   Type   |  Owner   | Persistence | Access method |    Size    | Description 
--------+----------------------------------+----------+----------+-------------+---------------+------------+-------------
 public | access_permissions               | table    | postgres | permanent   | heap          | 16 kB      | 
 public | access_permissions_id_seq        | sequence | postgres | permanent   |               | 8192 bytes | 
 public | alembic_version                  | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | alert_subscriptions              | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | alert_subscriptions_id_seq       | sequence | postgres | permanent   |               | 8192 bytes | 
 public | alerts                           | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | alerts_id_seq                    | sequence | postgres | permanent   |               | 8192 bytes | 
 public | api_keys                         | table    | postgres | permanent   | heap          | 16 kB      | 
 public | api_keys_id_seq                  | sequence | postgres | permanent   |               | 8192 bytes | 
 public | changes                          | table    | postgres | permanent   | heap          | 512 kB     | 
 public | changes_id_seq                   | sequence | postgres | permanent   |               | 8192 bytes | 
 public | dashboards                       | table    | postgres | permanent   | heap          | 16 kB      | 
 public | dashboards_id_seq                | sequence | postgres | permanent   |               | 8192 bytes | 
 public | data_source_groups               | table    | postgres | permanent   | heap          | 40 kB      | 
 public | data_source_groups_id_seq        | sequence | postgres | permanent   |               | 8192 bytes | 
 public | data_sources                     | table    | postgres | permanent   | heap          | 48 kB      | 
 public | data_sources_id_seq              | sequence | postgres | permanent   |               | 8192 bytes | 
 public | events                           | table    | postgres | permanent   | heap          | 715 MB     | 
 public | events_id_seq                    | sequence | postgres | permanent   |               | 8192 bytes | 
 public | favorites                        | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | favorites_id_seq                 | sequence | postgres | permanent   |               | 8192 bytes | 
 public | groups                           | table    | postgres | permanent   | heap          | 16 kB      | 
 public | groups_id_seq                    | sequence | postgres | permanent   |               | 8192 bytes | 
 public | notification_destinations        | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | notification_destinations_id_seq | sequence | postgres | permanent   |               | 8192 bytes | 
 public | organizations                    | table    | postgres | permanent   | heap          | 16 kB      | 
 public | organizations_id_seq             | sequence | postgres | permanent   |               | 8192 bytes | 
 public | queries                          | table    | postgres | permanent   | heap          | 456 kB     | 
 public | queries_id_seq                   | sequence | postgres | permanent   |               | 8192 bytes | 
 public | query_results                    | table    | postgres | permanent   | heap          | 1309 MB    | 
 public | query_results_id_seq             | sequence | postgres | permanent   |               | 8192 bytes | 
 public | query_snippets                   | table    | postgres | permanent   | heap          | 8192 bytes | 
 public | query_snippets_id_seq            | sequence | postgres | permanent   |               | 8192 bytes | 
 public | users                            | table    | postgres | permanent   | heap          | 64 kB      | 
 public | users_id_seq                     | sequence | postgres | permanent   |               | 8192 bytes | 
 public | visualizations                   | table    | postgres | permanent   | heap          | 144 kB     | 
 public | visualizations_id_seq            | sequence | postgres | permanent   |               | 8192 bytes | 
 public | widgets                          | table    | postgres | permanent   | heap          | 56 kB      | 
 public | widgets_id_seq                   | sequence | postgres | permanent   |               | 8192 bytes | 
(39 rows)
```

**Comment by myonlylonely** [comment]
```
postgres=# \d queries
                                            Table "public.queries"
        Column        |           Type           | Collation | Nullable |               Default               
----------------------+--------------------------+-----------+----------+-------------------------------------
 updated_at           | timestamp with time zone |           | not null | 
 created_at           | timestamp with time zone |           | not null | 
 id                   | integer                  |           | not null | nextval('queries_id_seq'::regclass)
 version              | integer                  |           | not null | 
 org_id               | integer                  |           | not null | 
 data_source_id       | integer                  |           |          | 
 latest_query_data_id | integer                  |           |          | 
 name                 | character varying(255)   |           | not null | 
 description          | character varying(4096)  |           |          | 
 query                | text                     |           | not null | 
 query_hash           | character varying(32)    |           | not null | 
 api_key              | character varying(40)    |           | not null | 
 user_id              | integer                  |           | not null | 
 last_modified_by_id  | integer                  |           |          | 
 is_archived          | boolean                  |           | not null | 
 is_draft             | boolean                  |           | not null | 
 schedule             | text                     |           |          | '{}'::text
 schedule_failures    | integer                  |           | not null | 
 options              | text                     |           |          | '{}'::text
 search_vector        | tsvector                 |           |          | 
 tags                 | character varying[]      |           |          | 
```

**Comment by myonlylonely** [comment]
It is because of the downgrade process.
I manually execute the SQL. Then it works!

```
ALTER TABLE queries ALTER COLUMN options DROP DEFAULT;
//other SQLs
```
