### ISSUE TITLE
Document how to use the Docker image

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#673]
* What runs on the container.
* supervisord.conf as a volume.
* The database bootstrap script.

**Comment by bobcolner** [comment]
+1

* simple 'docker run' examples

**Comment by arikfr** [comment]
@bobcolner if you have specific questions, feel free to ask (here or on the [Gitter channel](https://gitter.im/getredash/redash)). It will help shape the documentation.

**Comment by that0n3guy** [comment]
+1 

Also, the description on https://hub.docker.com/r/redash/redash/ says use the `stable` tag, but I don't think it exists.

**Comment by arikfr** [comment]
@that0n3guy oops, it meant to be `latest`. I will fix the description.

**Comment by fs-bussy-j-daniel** [comment]
How to run the container? Not a single info in the docs
a simple run is useless.
Write single run example takes 30s a best
```
$ docker run -P redash/redash
2016-03-09 10:49:04,835 CRIT Supervisor running as root (no user in config file)
2016-03-09 10:49:04,875 INFO RPC interface 'supervisor' initialized
2016-03-09 10:49:04,875 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2016-03-09 10:49:04,875 INFO supervisord started with pid 1
2016-03-09 10:49:05,878 INFO spawned: 'redash_celery' with pid 18
2016-03-09 10:49:05,879 INFO spawned: 'redash_server' with pid 19
2016-03-09 10:49:05,881 INFO spawned: 'redash_celery_scheduled' with pid 20
[2016-03-09 10:49:06 +0000] [19] [INFO] Starting gunicorn 19.4.5
[2016-03-09 10:49:06 +0000] [19] [INFO] Listening at: http://0.0.0.0:5000 (19)
[2016-03-09 10:49:06 +0000] [19] [INFO] Using worker: sync
[2016-03-09 10:49:06 +0000] [33] [INFO] Booting worker with pid: 33
[2016-03-09 10:49:06 +0000] [34] [INFO] Booting worker with pid: 34
^C2016-03-09 10:49:06,077 WARN received SIGINT indicating exit request
2016-03-09 10:49:06,077 INFO waiting for redash_celery, redash_server, redash_celery_scheduled to die
2016-03-09 10:49:06,078 INFO stopped: redash_celery_scheduled (terminated by SIGTERM)
[2016-03-09 10:49:06 +0000] [35] [INFO] Booting worker with pid: 35
[2016-03-09 10:49:06 +0000] [42] [INFO] Booting worker with pid: 42
[2016-03-09 10:49:06,184][PID:34][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06,185][PID:33][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06,186][PID:35][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06,194][PID:18][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06 +0000] [19] [INFO] Handling signal: term
[2016-03-09 10:49:06,231][PID:18][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06,231][PID:33][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-03-09 10:49:06,231][PID:34][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
    main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 304, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 464, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 484, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 222, in find_app
[2016-03-09 10:49:06 +0000] [34] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/opt/redash/current/redash/__init__.py", line 51, in <module>
    reset_new_version_status()
  File "/opt/redash/current/redash/version_check.py", line 34, in reset_new_version_status
    latest_version = get_latest_version()
  File "/opt/redash/current/redash/version_check.py", line 40, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 588, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 381, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 299, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 281, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting localhost:6379. Connection refused.
```

**Comment by jeffwidman** [comment]
@fs-bussy-j-daniel see #911 for basic docker instructions if you're just trying to get up and running quickly.
