### ISSUE TITLE
facing internal server error after clicking on queries option 

### ISSUE THREAD

**Issue by govindpawa** [getredash/redash#6778]
<img width="1440" alt="image" src="https://github.com/getredash/redash/assets/55016702/ca12e25d-4947-4955-afdb-a4bcfa8c3a10">

**Comment by clearnote01** [comment]
looking at logs would be the best bet, since this doesn't tell anything. i have seen such problems often when environment variables aren't configured probably, so that could be the case.

**Comment by govindpawa** [comment]
Hi clear note1
facing internal server i have solved this issue but after this we are facing 

scheduler are not running and schema are not loading 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 104, in _verify_signature
    h.verify(data[-32:])
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/primitives/hmac.py", line 66, in verify
    ctx.verify(signature)
  File "/usr/local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:
