### ISSUE TITLE
Redash can't refresh mongodb schema unless all collections are granted

### ISSUE THREAD

**Issue by jimethn** [getredash/redash#6808]
### Issue Summary

We only want to grant redash read access to a subset of the collections in a mongodb database. (In our use case, it's because some of the collections contain PII we don't want to expose.) As such, we granted our redash user `find` on only the specific collections we want to allow, along with `listCollections`.

When we try to query this data source, redash throws an error "Schema refresh failed. Please try again later." We are still able to query it through redash, but the collection list in the schema panel remains empty.

### Steps to Reproduce

1. Create a mongo database with 2 collections
2. Create a redash user and grant it `find` on only 1 of the collections
3. Add the datasource to redash
4. Redash fails to refresh schema, schema list is unavailable

In the logs we see

```
2024-03-11 15:57:37	[2024-03-11 19:57:37,939][PID:5071][WARNING][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_schema job.id=cf572fbb-54ce-4e91-b99e-25bee23ecda0 Failed refreshing schema for the data source: redacted
2024-03-11 15:57:37	Traceback (most recent call last):
2024-03-11 15:57:37	  File "/app/redash/tasks/queries/maintenance.py", line 171, in refresh_schema
2024-03-11 15:57:37	    ds.get_schema(refresh=True)
2024-03-11 15:57:37	  File "/app/redash/models/__init__.py", line 198, in get_schema
2024-03-11 15:57:37	    schema = query_runner.get_schema(get_stats=refresh)
2024-03-11 15:57:37	  File "/app/redash/query_runner/mongodb.py", line 244, in get_schema
2024-03-11 15:57:37	    columns = self._get_collection_fields(db, collection_name)
2024-03-11 15:57:37	  File "/app/redash/query_runner/mongodb.py", line 228, in _get_collection_fields
2024-03-11 15:57:37	    for d in db[collection_name].find().sort([("$natural", 1)]).limit(1):
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
2024-03-11 15:57:37	    if len(self.__data) or self._refresh():
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 1073, in _refresh
2024-03-11 15:57:37	    self.__send_message(q)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/cursor.py", line 955, in __send_message
2024-03-11 15:57:37	    address=self.__address)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1347, in _run_operation_with_response
2024-03-11 15:57:37	    exhaust=exhaust)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1465, in _retryable_read
2024-03-11 15:57:37	    return func(session, server, sock_info, slave_ok)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1341, in _cmd
2024-03-11 15:57:37	    unpack_res)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/server.py", line 136, in run_operation_with_response
2024-03-11 15:57:37	    _check_command_response(first)
2024-03-11 15:57:37	  File "/usr/local/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
2024-03-11 15:57:37	    raise OperationFailure(msg % errmsg, code, response)
2024-03-11 15:57:37	pymongo.errors.OperationFailure: not authorized on redacted to execute command { find: "key", filter: {}, sort: { $natural: 1 }, limit: 1, lsid: { id: UUID("1ac0037a-f0b2-4fc8-ae28-cf0d09a6ee9b") }, $clusterTime: { clusterTime: Timestamp(1710187057, 205), signature: { hash: BinData(0, 0A1329D10FFB135FF1C6C99E458B46E10F6CF7E6), keyId: 7308403787817811969 } }, $db: "redacted", $readPreference: { mode: "primaryPreferred" } }
2024-03-11 15:57:37	[2024-03-11 19:57:37,942][PID:5071][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_schema job.id=cf572fbb-54ce-4e91-b99e-25bee23ecda0 task=refresh_schema state=failed ds_id=177 runtime=0.03
2024-03-11 15:57:37	[2024-03-11 19:57:37,945][PID:11460][INFO][rq.worker] schemas: 7a36415f-3e9f-4667-be9d-8319a579739d
```

### Technical details:

Redash gets the mongo schema by executing [these find queries](https://github.com/getredash/redash/blob/d554136f7056d73b0e97840ee924087f27a27468/redash/query_runner/mongodb.py#L209-L230) against [every collection](https://github.com/getredash/redash/blob/d554136f7056d73b0e97840ee924087f27a27468/redash/query_runner/mongodb.py#L244) in the DB. If any of the find queries error, an exception is thrown and the entire schema refresh fails.

**Comment by jimethn** [comment]
We are on the latest non-dev release, 10.1.0. I think this was actually fixed in [this PR](https://github.com/getredash/redash/pull/5734). Maybe I'm wrong, but it looks to me like the try/except should cause an empty list to return and the schema will still be populated. In that case, I guess we just need to upgrade to a dev release.

**Comment by jimethn** [comment]
Closing this as a duplicate of https://github.com/getredash/redash/issues/5733, but it would be nice to get a new official release.
