### ISSUE TITLE
Query Based Dropdown is not working

### ISSUE THREAD

**Issue by ShivangPrajapati** [getredash/redash#6985]
### Issue Summary

While using query based dropdown, we see results of query is not listed in dropdown, instead it show no options found. From inspect and redash logs I could see that endpoint "/api/queries/44/dropdowns/114 [GET]" fails, but query 114 individually works fine and returns 1 column and around 190 rows. Here 190 rows seems to be issue. If I limit results to less row, it works fine. Is there a limit for query based dropdown? PFA below logs.

```
server_1            | [2024-05-24 09:39:58,539][PID:32][INFO][metrics] method=GET path=/api/queries/114 endpoint=query status=200 content_type=application/json content_length=1765 duration=41.94 query_count=10 query_duration=19.12
server_1            | [2024-05-24 09:39:58,574][PID:44][ERROR][redash.app] Exception on /api/queries/44/dropdowns/114 [GET]
server_1            | Traceback (most recent call last):
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
server_1            |     rv = self.dispatch_request()
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
server_1            |     return self.view_functions[rule.endpoint](**req.view_args)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
server_1            |     resp = resource(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
server_1            |     return func(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
server_1            |     return self.dispatch_request(*args, **kwargs)
server_1            |   File "/app/redash/handlers/base.py", line 33, in dispatch_request
server_1            |     return super(BaseResource, self).dispatch_request(*args, **kwargs)
server_1            |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
server_1            |     resp = meth(*args, **kwargs)
server_1            |   File "/app/redash/handlers/query_results.py", line 242, in get
server_1            |     return dropdown_values(dropdown_query_id, self.current_org)
server_1            |   File "/app/redash/models/parameterized_query.py", line 36, in dropdown_values
server_1            |     return list(map(pluck, data["rows"]))
server_1            |   File "/app/redash/models/parameterized_query.py", line 15, in _pluck_name_and_value
server_1            |     return {"name": row[name_column], "value": str(row[value_column])}
server_1            | KeyError: 'referral_code'
server_1            | [2024-05-24 09:39:58,575][PID:44][INFO][metrics] method=GET path=/api/queries/44/dropdowns/114 endpoint=query_result_dropdowns status=500 content_type=application/json content_length=36 duration=81.40 query_count=13 query_duration=60.85
```

### Steps to Reproduce

1. Write query which results in 1 column and large number of rows to be used as query based parameter.
2. Write another query which has query based parameter and use query created in step 1.

Ideally results of query 1 should be seen in query 2 dropdown. But instead it shows no options found.

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: To run query using Google Chrome on MacOS
* How did you install Redash: Hosted on aws ec2 instance of ubuntu 18.04 using docker

**Comment by ShivangPrajapati** [comment]
There was another issue. Resolved
