### ISSUE TITLE
Getting tables fails if Redash DB user has no permissions to a schema in PG database

### ISSUE THREAD

**Issue by kfrydel** [getredash/redash#6988]
### Issue Summary

The query executed by this function: https://github.com/getredash/redash/blob/master/redash/query_runner/pg.py#L206 fails with `ERROR:  permission denied for schema XYZ` if the DB user used to access PostgreSQL data source has no permissions to access some schema and the schema contains a partitioned table. It fails on `has_table_privilege(s.nspname || '.' || c.relname, 'select')`.
I suppose that the same happens for materialized views and foreign tables because of `c.relkind IN ('m', 'f', 'p')` condition.

Adding `AND has_schema_privilege(s.nspname, 'usage')` condition to `JOIN pg_namespace` should fix this issue because then the query will not try to check permissions for particular tables if the user cannot access the whole schema.

Stacktrace from logs:
```
[2024-05-23 01:00:26,875][PID:3615879][INFO][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_schema job.id=766d55ee-b9c4-459f-ba56-c032b8321656 task=refresh_schema state=start ds_id=2
[2024-05-23 01:00:26,959][PID:3615879][ERROR][redash.query_runner] permission denied for schema XYZ

[2024-05-23 01:00:26,959][PID:3615879][WARNING][rq.job.redash.tasks.queries.maintenance] job.func_name=redash.tasks.queries.maintenance.refresh_schema job.id=766d55ee-b9c4-459f-ba56-c032b8321656 Failed refreshing schema for the data source: MYDATABASE
Traceback (most recent call last):
  File "/some/path/src/redash/tasks/queries/maintenance.py", line 166, in refresh_schema
    ds.get_schema(refresh=True)
  File "/some/path/src/redash/models/__init__.py", line 215, in get_schema
    schema = query_runner.get_schema(get_stats=refresh)
  File "/some/path/src/redash/query_runner/__init__.py", line 272, in get_schema
    self._get_tables(schema_dict)
  File "/some/path/src/redash/query_runner/pg.py", line 246, in _get_tables
    self._get_definitions(schema, query)
  File "/some/path/src/redash/query_runner/pg.py", line 202, in _get_definitions
    self._handle_run_query_error(error)
  File "/some/path/src/redash/query_runner/__init__.py", line 239, in _handle_run_query_error
    raise Exception(f"Error during query execution. Reason: {error}")
Exception: Error during query execution. Reason: permission denied for schema XYZ
```

### Steps to Reproduce

1. Install Redash
2. Create Postgres DB and dedicated user for Redash
3. Create some schema XYZ
4. Create partitioned tables in schema XYZ
5. Run Redash and  configure Postgres data source
6. Wait for stack trace in logs

### Technical details:

* Redash Version:https://github.com/getredash/redash/commit/19bd3301fadd43a864b493530240e901a319c3eb (built from this commit)
* Browser/OS:Does not matter, not a UI bug. Ubuntu 22.04 but probably also does not matter.
* PostgreSQL: 13.15
* How did you install Redash: by installing a package built from sources

**Comment by eradman** [comment]
Fix merged. Thank you for the detailed report @kfrydel!
