### ISSUE TITLE
Cannot get started

### ISSUE THREAD

**Issue by dhaggy1980** [getredash/redash#7244]
### Issue Summary

I am getting 500 Internal Server Error after running Redash. I have the package installed and I choose my port number and then I get an error page.  Any help would be nice. I'm just trying to find and easier way to get reports to the staff.

This is the error in docker
I'm too new to docker to understand how to even fix this.

2024-12-06 17:27:05 [2024-12-06 23:27:05,673] ERROR in app: Exception on / [GET]
2024-12-06 17:27:05 Traceback (most recent call last):
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2024-12-06 17:27:05     response = self.full_dispatch_request()
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request
2024-12-06 17:27:05     self.try_trigger_before_first_request_functions()
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
2024-12-06 17:27:05     func()
2024-12-06 17:27:05   File "/app/redash/version_check.py", line 85, in reset_new_version_status
2024-12-06 17:27:05     latest_version = get_latest_version()
2024-12-06 17:27:05   File "/app/redash/version_check.py", line 91, in get_latest_version
2024-12-06 17:27:05     return redis_connection.get(REDIS_KEY)
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1264, in get
2024-12-06 17:27:05     return self.execute_command('GET', name)
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 772, in execute_command
2024-12-06 17:27:05     connection = pool.get_connection(command_name, **options)
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 994, in get_connection
2024-12-06 17:27:05     connection.connect()
2024-12-06 17:27:05   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 497, in connect
2024-12-06 17:27:05     raise ConnectionError(self._error_message(e))
2024-12-06 17:27:05 ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

![Screenshot 2024-12-06 172548](https://github.com/user-attachments/assets/515528e7-95c4-46af-870b-30233a5e6c3e)

![Screenshot 2024-12-06 172621](https://github.com/user-attachments/assets/abdb3989-f797-453c-ba20-2b9c64189cde)

### Steps to Reproduce

1. Run the app

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: I'm assuming the current one
* Browser/OS: Firefox - Edge /Windows 11 Docker
* How did you install Redash: link from the page

**Comment by dhaggy1980** [comment]
Oh and I did try changing the port. I did notice the  localhost:6379 but thats not the number I have.

**Comment by dhaggy1980** [comment]
Thanks for the reply, I did this a few days ago, I forgot to update this post. I did install redis after countless hours of trying to figure this out. I used AI to help. There's nothing on the documentation about redis, that I've found anyway. After installing redis I still cannot connect. Redis log tells me it's ready to connect. So I don't know what to do.

**Comment by BowlesCR** [comment]
I suspect this is a (near?) dupe of the problem in https://github.com/getredash/redash/issues/7072
