### ISSUE TITLE
Problem with creating new users

### ISSUE THREAD

**Issue by TonyStarkBy** [getredash/redash#736]
Problems:
1. New users can't login
2. User list not showing
3. Impossible to add any user to any group

How to repeat:
1. Add new user
2. Try to login

```
[2016-01-06 16:36:37,232: ERROR/MainProcess] Task redash.tasks.record_event[3ca6f961-65d7-44ec-b22e-b8a285d926f3] raised unexpected: KeyError('org_id',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.9.0.b1292/redash/tasks.py", line 31, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.9.0.b1292/redash/tasks.py", line 301, in record_event
    models.Event.record(event)
  File "/opt/redash/redash.0.9.0.b1292/redash/models.py", line 1007, in record
    org = event.pop('org_id')
KeyError: 'org_id'
```

Solution is add new user to group, but it cannot be done through web. 
```
update public.users set groups='{2}' where id=%NEW_USER_ID%;
```

**Comment by arikfr** [comment]
I'll fix this. :+1: 

Thanks for reporting these issues w/ 0.9.0.
