### ISSUE TITLE
Alert send Error(AttributeError: 'Organization' object has no attribute 'domain)

### ISSUE THREAD

**Issue by toyama0919** [getredash/redash#738]
Hello.

Alert send Error.

```
01:51:24 worker.1 | [2016-01-07 01:51:24,764: ERROR/MainProcess] Task redash.tasks.check_alerts_for_query[6fd2a1aa-bb2b-4054-a6a1-2487c0bae30c] raised unexpected: AttributeError("'Organization' object has no attribute 'domain'",)
01:51:24 worker.1 | Traceback (most recent call last):
01:51:24 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
01:51:24 worker.1 |     R = retval = fun(*args, **kwargs)
01:51:24 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 31, in __call__
01:51:24 worker.1 |     return super(BaseTask, self).__call__(*args, **kwargs)
01:51:24 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
01:51:24 worker.1 |     return self.run(*args, **kwargs)
01:51:24 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 338, in check_alerts_for_query
01:51:24 worker.1 |     """.format(host=base_url(alert.query.org), alert_id=alert.id, query_id=query.id)
01:51:24 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 309, in base_url
01:51:24 worker.1 |     if org.domain:
01:51:24 worker.1 | AttributeError: 'Organization' object has no attribute 'domain'
```

**Comment by arikfr** [comment]
Fixed. Thanks!

**Comment by toyama0919** [comment]
:blush:
