### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by pjrtb** [getredash/redash#747]
When I'm trying to open redash (commit fdd60b3) I get:

```
[2016-01-08 07:52:37,841][PID:6397][ERROR][redash.wsgi] Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.0.7.1.b1015/redash/controllers.py", line 76, in login
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
```

**Comment by arikfr** [comment]
From the stacktrace it looks like you are running re:dash v0.7.1 with newer dependencies (namely Flask-Login), and hence the error.

**Comment by pjrtb** [comment]
Indeed. For the record - on ubuntu You need to restart not only services 
under supervisord, but the supervisord itself with

```
/etc/init.d/redash_supervisord restart
```

after redash update.
