### ISSUE TITLE
DataError: invalid input syntax for integer: "admin"

### ISSUE THREAD

**Issue by bobrik** [getredash/redash#785]
Latest 0.9.2-RC. When you make a user admin with a checkbox:

![image](https://cloud.githubusercontent.com/assets/89186/12489616/1c1ac55c-c069-11e5-9cee-e97b299f522d.png)

```
[2016-01-21 17:58:21,655][PID:12][ERROR][redash.wsgi] Exception on /api/users/2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/redash/redash/handlers/base.py", line 19, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/redash/redash/handlers/users.py", line 76, in post
    user.update_instance(**params)
  File "/opt/redash/redash/models.py", line 106, in update_instance
    self.save(only=self.dirty_fields)
  File "/opt/redash/redash/models.py", line 93, in save
    super(BaseModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4146, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2751, in execute
    return self.database.rows_affected(self._execute())
  File "/opt/redash/redash/metrics/database.py", line 50, in metered_execute
    result = real_execute(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/redash/redash/metrics/database.py", line 22, in execute_sql
    result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
DataError: invalid input syntax for integer: "admin"
LINE 1: ..." = E'foo@bar.com', "groups" = ARRAY[2, E'admin'] ...
```

Adding to admin group works.

**Comment by arikfr** [comment]
Oops. I forgot about this one.

In 0.9.2, you can make a user an admin by adding him to the "admin" group. I wonder if we should keep this checkbox or remove it ...
