### ISSUE TITLE
Cannot run manage.py tasks

### ISSUE THREAD

**Issue by brettlangdon** [getredash/redash#791]
When we upgraded to the latest version `0.9.1+b1377`, I noticed that `manage.py` stopped working, I get the following error:

```
ubuntu@aws:/opt/redash/current$ ./bin/run ./manage.py users list
[2016-01-22 15:47:14,101][PID:31244][WARNING][redash.query_runner] GoogleSpreadsheet query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,112][PID:31244][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,122][PID:31244][WARNING][redash.query_runner] InfluxDB query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,122][PID:31244][WARNING][redash.query_runner] Presto query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,123][PID:31244][WARNING][redash.query_runner] Vertica query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,123][PID:31244][WARNING][redash.query_runner] TreasureData query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:47:14,124][PID:31244][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
Traceback (most recent call last):
  File "/opt/redash/current/manage.py", line 58, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 341, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1714, in do_teardown_request
    rv = func(exc)
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 39, in calculate_metrics_on_exception
    calculate_metrics(MockResponse(500, '?', -1))
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 17, in calculate_metrics
    request_duration = (time.time() - g.start_time) * 1000
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'start_time'
```

If it helps we are running on the `re:dash` AMI in AWS and I can provide more information if it is needed.

**Comment by tclass** [comment]
you should run it as the redash user `su redash` maybe this works

**Comment by brettlangdon** [comment]
There we go  `sudo -u redash ./bin/run ./manage.py users list` did the trick.

Thanks! Closing.
