### ISSUE TITLE
Cannot grant admin with manage.py

### ISSUE THREAD

**Issue by brettlangdon** [getredash/redash#792]
Running:

```
cd /opt/redash/current
./bin/run ./manage.py users grant_admin "user@domain.com"
```

Produces the following error:

```
ubuntu@aws:/opt/redash/current$ sudo -u redash ./bin/run ./manage.py users grant_admin "user@domain.com"
[2016-01-22 15:57:56,612][PID:31825][WARNING][redash.query_runner] GoogleSpreadsheet query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,622][PID:31825][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,633][PID:31825][WARNING][redash.query_runner] InfluxDB query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,633][PID:31825][WARNING][redash.query_runner] Presto query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,634][PID:31825][WARNING][redash.query_runner] Vertica query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,635][PID:31825][WARNING][redash.query_runner] TreasureData query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,635][PID:31825][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-22 15:57:56,846][PID:31825][ERROR][peewee] UPDATE "users" SET "updated_at" = %s, "created_at" = %s, "org_id" = %s, "name" = %s, "email" = %s, "password_hash" = %s, "groups" = %s, "api_key" = %s WHERE ("users"."id" = %s) [datetime.datetime(2016, 1, 22, 15, 57, 56, 845456), datetime.datetime(2015, 7, 31, 13, 45, 9, 924407, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)), 1, u'User Name', u'user@domain.com', None, [6, 1, 2, 4, 3, 11, 'admin'], u'<hash>', 2]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
DataError: invalid input syntax for integer: "admin"
LINE 1: ...hash" = NULL, "groups" = ARRAY[6, 1, 2, 4, 3, 11, 'admin'], ...
                                                             ^

Traceback (most recent call last):
  File "/opt/redash/redash.0.9.1.b1377/manage.py", line 58, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 341, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1714, in do_teardown_request
    rv = func(exc)
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 39, in calculate_metrics_on_exception
    calculate_metrics(MockResponse(500, '?', -1))
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 17, in calculate_metrics
    request_duration = (time.time() - g.start_time) * 1000
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'start_time'
```

It looks as though it is trying to add `'admin'` to an `integer[]`.

I am currently running version `0.9.1+b1377`

**Comment by GregBowyer** [comment]
This also appears to be a problem with the UI too

**Comment by arikfr** [comment]
Related: #785.

**Comment by npateman** [comment]
I'm also getting this issue, I resorted to the terminal as the UI seems very flaky at putting users into groups and the "admin" checkbox throws an error when checked.
