### ISSUE TITLE
Can't Delete a user

### ISSUE THREAD

**Issue by shishirsharma** [getredash/redash#799]
Getting this error on user deletion on version redash.0.9.1.b1377

```
root@ip-172-31-26-238:/opt/redash/current# sudo -u redash bin/run ./manage.py users delete admin
[2016-01-27 00:29:14,101][PID:30373][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-27 00:29:14,139][PID:30373][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-01-27 00:29:14,333][PID:30373][ERROR][peewee] DELETE FROM "users" WHERE ("email" = %s) [u'admin']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: update or delete on table "users" violates foreign key constraint "events_user_id_fkey" on table "events"
DETAIL:  Key (id)=(26) is still referenced from table "events".

Traceback (most recent call last):
  File "/opt/redash/redash.0.9.1.b1377/manage.py", line 58, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 341, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1714, in do_teardown_request
    rv = func(exc)
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 39, in calculate_metrics_on_exception
    calculate_metrics(MockResponse(500, '?', -1))
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 17, in calculate_metrics
    request_duration = (time.time() - g.start_time) * 1000
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'start_time'
```

**Comment by benmanns** [comment]
I had this issue, too. It looks like the script needs to delete events before deleting a user, or the Postgres DB needs to have the foreign keys set up to automatically delete events. As a workaround, I ran:

```sh
sudo -u redash psql -c 'DELETE FROM events WHERE user_id = <the-user-id>;'
```

**Comment by TonyStarkBy** [comment]
Is it possible to delete user from admin web page?

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6siqvcxh&#x2F;39-admin-should-be-able-to-disable-delete-a-user"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Admin should be able to disable&#x2F;delete a user</a>

**Comment by volcomism** [comment]
Can we get an update when this will be implemented now that it seems you have a final release of v1 ?

**Comment by gppeixoto** [comment]
Any updates? +1 for this feature. We should not depend on direct access to the database to delete an user, it is a very regular operation that should be easy to do so.

**Comment by wa721** [comment]
+ 1, the manage.py is a chore to go through when managing users. A UI feature would be warmly welcomed.

**Comment by ShahSunny** [comment]
Any updates? +1 for this feature.

**Comment by jrbenny35** [comment]
We could use this for the UI tests that we are working on. See the above reference link.

**Comment by kocsmy** [comment]
Enable/Disable user feature PR has been merged 6 days ago: https://github.com/getredash/redash/pull/2380

**Comment by ryanguill** [comment]
disable is not the same as delete.
