### ISSUE TITLE
Worker exited prematurely: signal 9 (SIGKILL)

### ISSUE THREAD

**Issue by Laboratory** [getredash/redash#812]
Hello,

How can I resolve this problem? Or find more details

``````bash
==> /opt/redash/logs/celery_error.log <==
[2016-02-03 17:35:25,761: ERROR/MainProcess] Process 'Worker-6' pid:3653 exited with 'signal 9 (SIGKILL)'

==> /opt/redash/logs/api_error.log <==
[2016-02-03 17:35:25,896][PID:3958][DEBUG][peewee] ('SELECT "t1"."id", "t1"."updated_at", "t1"."created_at", "t1"."name", "t1"."email", "t1"."password_hash", "t1"."groups", "t1"."api_key" FROM "users" AS t1 WHERE ("t1"."id" = %s) LIMIT 1', [1])

==> /opt/redash/logs/celery_error.log <==
[2016-02-03 17:35:26,023: ERROR/MainProcess] Task redash.tasks.execute_query[8ea76498-a195-46fe-894f-83331a551ff6] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

Thanks

**Comment by Laboratory** [comment]
Or this exception:

``````bash
==> /opt/redash/logs/celery_error.log <==
[2016-02-03 18:41:02,653: ERROR/MainProcess] Process 'Worker-9' pid:5878 exited with 'signal 11 (SIGSEGV)'
[2016-02-03 18:41:02,894: ERROR/MainProcess] Task redash.tasks.execute_query[79353595-3acb-4a1f-9c29-628ef7c160c2] raised unexpected: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

**Comment by Laboratory** [comment]
Ok, I found the problem
When I try to execute aggregation query to MongoDB (result should be 100 rows)
My local machine takes all memory (from 400Mb to 4Gb) and swap file (from 100Mb to 900Mb) and after going the crashed
<img width="1194" alt="screen shot 2016-02-03 at 18 59 31" src="https://cloud.githubusercontent.com/assets/1676506/12788051/0a5b597c-caa9-11e5-9530-6a021a655e9b.png">
Why is this happening?

**Comment by arikfr** [comment]
Workers memory usage is a function of the result set. Your query returns
much more data than you think.

Most likely that the aggregation is being ignored or not aggregating as
much as you think.

Try adding a limit to the query to debug this.

**Comment by Laboratory** [comment]
Mongo shell returns 10 rows  (10Kb)
`````mognodb
{ "amount" : 1000, "year" : 2015, "SubRegion" : "Med" }
{ "amount" : 1000, "year" : 2015, "SubRegion" : "Italy" }
{ "amount" : 1000, "year" : 2015, "SubRegion" : "East" }
...
```

**Comment by Laboratory** [comment]
MongoDB can't return result more than 16Mb

**Comment by Laboratory** [comment]
MongoDB `query` works perfect, but `aggregation` with small data set don't work normally

**Comment by arikfr** [comment]
Can you share the query you run?

-- 
Arik Fraimovich

**Comment by Laboratory** [comment]
sure
``````javascript
{
	"collection": "Everything",
	"aggregate ": [{
		"$project": {
			"year": {
				"$year": "$Close Date"
			},
			"CloseDate": "$Close Date",
			"TotalPrice": "$Total Price",
			"SubRegion": "$Sub-Region"
		}
	}, {
		"$match": {
			"year": {
				"$gte": 2015
			}
		}
	}, {
		"$group": {
			"_id": {
				"year": "$year",
				"SubRegion": "$SubRegion"
			},
			"amount": {
				"$sum": "$TotalPrice"
			}
		}
	}, {
		"$project": {
			"_id": 0,
			"amount": "$amount",
			"year": "$_id.year",
			"SubRegion": "$_id.SubRegion"
		}
	}]
}
```

**Comment by arikfr** [comment]
In overview looks ok, can you try running the following Python code and see what result you're getting:

```python
connection_string = "... your mongo connection string ..."
db = pymongo.MongoClient(connection_string)
r = db["Everything"].aggregate([{
        "$project": {
            "year": {
                "$year": "$Close Date"
            },
            "CloseDate": "$Close Date",
            "TotalPrice": "$Total Price",
            "SubRegion": "$Sub-Region"
        }
    }, {
        "$match": {
            "year": {
                "$gte": 2015
            }
        }
    }, {
        "$group": {
            "_id": {
                "year": "$year",
                "SubRegion": "$SubRegion"
            },
            "amount": {
                "$sum": "$TotalPrice"
            }
        }
    }, {
        "$project": {
            "_id": 0,
            "amount": "$amount",
            "year": "$_id.year",
            "SubRegion": "$_id.SubRegion"
        }
    }])
```

And check the contents of `r`?

**Comment by Laboratory** [comment]
I executed this code on the same machine:
``````python
from pymongo import MongoClient
connection_string = "mongodb://xxx.xx.xx.xx:27017/db_name"
client = MongoClient(connection_string)
db = client.db_name
r = db["Everything"].aggregate([{
        "$project": {
            "year": {
                "$year": "$Close Date"
            },
            "CloseDate": "$Close Date",
            "TotalPrice": "$Total Price",
            "SubRegion": "$Sub-Region"
        }
    }, {
        "$match": {
            "year": {
                "$gte": 2015
            }
        }
    }, {
        "$group": {
            "_id": {
                "year": "$year",
                "SubRegion": "$SubRegion"
            },
            "amount": {
                "$sum": "$TotalPrice"
            }
        }
    }, {
        "$project": {
            "_id": 0,
            "amount": "$amount",
            "year": "$_id.year",
            "SubRegion": "$_id.SubRegion"
        }
    }])

print r
```

``````shell
$ time python db_test.py
```

Got result:

``````shell
real	0m4.302s
user	0m0.048s
sys	0m0.008s
```
``````json
{u'ok': 1.0, u'result': [{u'amount': 1000, u'SubRegion': u'EMEA', u'year': 2015}, ... {}]
```

**Comment by vb3** [comment]
any updates on this issue? I am also getting Worker exited prematurely: signal 9 (SIGKILL)

**Comment by Laboratory** [comment]
I'll try it on Monday, thx

**Comment by arikfr** [comment]
@vb3 if it happens constantly with the same query, check if it wasn't killed by the OOM killer.

**Comment by vb3** [comment]
@arikfr thanks. I think that may be the cause, result set too big...

Can you share more details on the OOM killer? How can we check if it was killed by it?
My issue was that the CPU on my host gets pegged at 100% as well with one of the celery workers.

**Comment by matangover** [comment]
I think I was having the same issue:
![image](https://cloud.githubusercontent.com/assets/5028956/21471204/3b2d9844-cab2-11e6-8b07-325c2219fa03.png)

It might be useful to get a better error message in this case, this error is quite confusing.
