### ISSUE TITLE
Admin account broken

### ISSUE THREAD

**Issue by npateman** [getredash/redash#814]
Hi there,

I have somehow managed to break the default "admin" account for redash which seems to have killed everything.  What I had done was I created 2 new administrators and wanted to delete the admin account but couldn't find the option so I removed it from the admin group.

Now I have 2 admins that cannot create datasources, nothing is showing in there, and even after putting the original admin account back in the admins group, no admin options appear for that account.

Any ideas how to resurrect this??

**Comment by npateman** [comment]
The manage python script throws this error,

ubuntu@ip-172-31-44-151:/opt/redash/current$ sudo ./manage.py users list
[2016-02-08 10:02:14,614][PID:19851][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[2016-02-08 10:02:14,657][PID:19851][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
Traceback (most recent call last):
  File "./manage.py", line 58, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 341, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1714, in do_teardown_request
    rv = func(exc)
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 39, in calculate_metrics_on_exception
    calculate_metrics(MockResponse(500, '?', -1))
  File "/opt/redash/redash.0.9.1.b1377/redash/metrics/request.py", line 17, in calculate_metrics
    request_duration = (time.time() - g.start_time) * 1000
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'start_time'

**Comment by arikfr** [comment]
Can you create new users with this new admin accounts? If you can, then it might be that the issue is not with the user account themselves.

Do you see errors in:
1. Browser console?
2. API server log: `/opt/redash/logs/api_error.log`.

As for the error with the CLI, it's something I'm going to fix later today, but in the meantime if you add to `redash/metrics/request.py` on line 17 (in `calculate_metrics` method) the following lines:
```
if 'start_time' not in g:
    return response
```
It should fix it.

**Comment by npateman** [comment]
Hi there,

So in the browser console it says the API is throwing 500 errors, if I go to the error log after viewing the data sources I see the following,

ValidationError: 'db' is a required property

Failed validating 'required' in schema:
    {'properties': {'db': {'title': 'Database name', 'type': 'string'},
                    'host': {'default': '127.0.0.1', 'type': 'string'},
                    'passwd': {'title': 'Password', 'type': 'string'},
                    'port': {'default': 3306, 'type': 'number'},
                    'ssl_cacert': {'title': 'Path to CA certificate file to verify peer against (SSL)',
                                   'type': 'string'},
                    'ssl_cert': {'title': 'Path to client certificate file (SSL)',
                                 'type': 'string'},
                    'ssl_key': {'title': 'Path to private key file (SSL)',
                                'type': 'string'},
                    'use_ssl': {'title': 'Use SSL', 'type': 'boolean'},
                    'user': {'type': 'string'}},
     'required': ['db'],
     'secret': ['passwd'],
     'type': 'object'}

Maybe the db is corrupt?  How can I remove the bindings to start again?

**Comment by arikfr** [comment]
Looks like one of your data sources is missing required settings. You can either edit it or delete it. The CLI has a command to delete data sources, but if you created already queries it will fail. :\

You can start the shell (run `sudo -u redash bin/run ./manage.py shell` from `/opt/redash/current`) and then run:

```
d = models.DataSource..get(models.DataSource.name=="... its name ...")
d.delete_instance(recursive=True)
```

**Comment by arikfr** [comment]
You can also fix its settings there (`d.options = json.dumps({...})`) instead of deleting.

**Comment by npateman** [comment]
Thanks, I deleted the old sources and now it's functioning again.
