### ISSUE TITLE
create_database.sh is failing

### ISSUE THREAD

**Issue by eamonnfaherty** [getredash/redash#834]
I am using the latest docker image: e37fc3b444f5fed3213a72f05b2989c160c032ebf6db3cd96832e8a975f4c458

and the following script is failing: https://github.com/getredash/redash/blob/master/setup/docker/create_database.sh#L9

I get the following error:

Traceback (most recent call last):
  File "/opt/redash/current/manage.py", line 58, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 386, in __exit__
    self.auto_pop(exc_value)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 374, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/ctx.py", line 341, in pop
    self.app.do_teardown_request(exc)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1714, in do_teardown_request
    rv = func(exc)
  File "/opt/redash/current/redash/metrics/request.py", line 39, in calculate_metrics_on_exception
    calculate_metrics(MockResponse(500, '?', -1))
  File "/opt/redash/current/redash/metrics/request.py", line 17, in calculate_metrics
    request_duration = (time.time() - g.start_time) * 1000
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute 'start_time'

**Comment by arikfr** [comment]
You have some error, but it masked by another bug that was fixed in #815. Try running with a more recent Docker image,  like `0.9.2.b1458`.

**Comment by eamonnfaherty** [comment]
thanks. I am over this hurdle and am onto the next.
