### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by crooy** [getredash/redash#879]
Hi,

I just tried to upgrade from 0.8.3 to 0.9.1 and this is what happened

```
out: Traceback (most recent call last):
out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
out:     cursor.execute(sql, params or ())
out: ProgrammingError: column t1.org_id does not exist
out: LINE 1: SELECT "t1"."id", "t1"."org_id", "t1"."type", "t1"."name", "...
out:                           ^
out:
out: Traceback (most recent call last):
out:   File "migrations/0015_add_schedule_query_permission.py", line 4, in <module>
out:     default_group = models.Group.get(models.Group.name=='default')
out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4012, in get
out:     return sq.get()
out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2641, in get
out:     return clone.execute().next()
out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2682, in execute
out:     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
out:   File "/opt/redash/redash.0.9.1.b1377/redash/metrics/database.py", line 50, in metered_execute
out:     result = real_execute(self, *args, **kwargs)
out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
out:     return self.database.execute_sql(sql, params, self.require_commit)
out:   File "/opt/redash/redash.0.9.1.b1377/redash/metrics/database.py", line 22, in execute_sql
out:     result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
out:     self.commit()
out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
out:     reraise(new_type, new_type(*exc_value.args), traceback)
out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
out:     cursor.execute(sql, params or ())
out: peewee.ProgrammingError: column t1.org_id does not exist
out: LINE 1: SELECT "t1"."id", "t1"."org_id", "t1"."type", "t1"."name", "...
```

**Comment by arikfr** [comment]
This was fixed in 0.9.2, but it's not marked as latest yet so the upgrade script doesn't use it by default. Use `deploy_latest_release:stable=false` to upgrade to 0.9.2.

**Comment by crooy** [comment]
Thanks this did solve it!

**Comment by arikfr** [comment]
:+1:
