### ISSUE TITLE
Problem of setting up Vagrant environment

### ISSUE THREAD

**Issue by toru-takahashi** [getredash/redash#887]
I setup re:dash through http://docs.redash.io/en/latest/dev/vagrant.html
When I login re:dash, the following error message is happened.
`ValueError: invalid literal for int() with base 10: 'default'`

I use latest master branch(https://github.com/getredash/redash/commit/a8ece8641aa31e37ca90b4d3ec5b373ebd527225).
Do you have any idea why it happened?

```
vagrant@vagrant-ubuntu-trusty-64:/opt/redash/current$ bin/run honcho start -f Procfile.dev
...
14:26:10 worker.1 | [2016-03-06 14:26:10,108: ERROR/MainProcess] Task redash.tasks.record_event[0c4fbabf-77b0-42ed-9bf6-52f071f15d82] raised unexpected: KeyError('org_id',)
14:26:10 worker.1 | Traceback (most recent call last):
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
14:26:10 worker.1 |     R = retval = fun(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 31, in __call__
14:26:10 worker.1 |     return super(BaseTask, self).__call__(*args, **kwargs)
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
14:26:10 worker.1 |     return self.run(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 325, in record_event
14:26:10 worker.1 |     models.Event.record(event)
14:26:10 worker.1 |   File "/opt/redash/current/redash/models.py", line 1016, in record
14:26:10 worker.1 |     org = event.pop('org_id')
14:26:10 worker.1 | KeyError: 'org_id'
14:26:10 worker.1 | [2016-03-06 14:26:10,133: ERROR/MainProcess] Task redash.tasks.record_event[b12f7aad-1152-4c35-b861-54b8f42b5b07] raised unexpected: KeyError('org_id',)
14:26:10 worker.1 | Traceback (most recent call last):
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
14:26:10 worker.1 |     R = retval = fun(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 31, in __call__
14:26:10 worker.1 |     return super(BaseTask, self).__call__(*args, **kwargs)
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
14:26:10 worker.1 |     return self.run(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 325, in record_event
14:26:10 worker.1 |     models.Event.record(event)
14:26:10 worker.1 |   File "/opt/redash/current/redash/models.py", line 1016, in record
14:26:10 worker.1 |     org = event.pop('org_id')
14:26:10 worker.1 | KeyError: 'org_id'
14:26:10 worker.1 | [2016-03-06 14:26:10,152: ERROR/MainProcess] Task redash.tasks.record_event[28a1ca30-b127-4292-ba8c-3aad59d55112] raised unexpected: KeyError('org_id',)
14:26:10 worker.1 | Traceback (most recent call last):
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
14:26:10 worker.1 |     R = retval = fun(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 31, in __call__
14:26:10 worker.1 |     return super(BaseTask, self).__call__(*args, **kwargs)
14:26:10 worker.1 |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
14:26:10 worker.1 |     return self.run(*args, **kwargs)
14:26:10 worker.1 |   File "/opt/redash/current/redash/tasks.py", line 325, in record_event
14:26:10 worker.1 |     models.Event.record(event)
14:26:10 worker.1 |   File "/opt/redash/current/redash/models.py", line 1016, in record
14:26:10 worker.1 |     org = event.pop('org_id')
14:26:10 worker.1 | KeyError: 'org_id'
14:26:10 web.1    | [2016-03-06 14:26:10,460][PID:2083][WARNING][werkzeug]  * Debugger is active!
14:26:10 web.1    | [2016-03-06 14:26:10,464][PID:2083][INFO][werkzeug]  * Debugger pin code: 430-520-901
14:26:14 web.1    | [2016-03-06 14:26:14,829][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:14] "GET / HTTP/1.1" 500 -
14:26:14 web.1    | Traceback (most recent call last):
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
14:26:14 web.1    |     return self.wsgi_app(environ, start_response)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
14:26:14 web.1    |     return self.app(environ, start_response)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
14:26:14 web.1    |     response = self.make_response(self.handle_exception(e))
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
14:26:14 web.1    |     return original_handler(e)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
14:26:14 web.1    |     reraise(exc_type, exc_value, tb)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
14:26:14 web.1    |     response = self.full_dispatch_request()
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
14:26:14 web.1    |     rv = self.handle_user_exception(e)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
14:26:14 web.1    |     return original_handler(e)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
14:26:14 web.1    |     reraise(exc_type, exc_value, tb)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
14:26:14 web.1    |     rv = self.dispatch_request()
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
14:26:14 web.1    |     return self.view_functions[rule.endpoint](**req.view_args)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
14:26:14 web.1    |     return func(*args, **kwargs)
14:26:14 web.1    |   File "/opt/redash/current/redash/handlers/static.py", line 37, in index
14:26:14 web.1    |     'permissions': current_user.permissions
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
14:26:14 web.1    |     return getattr(self._get_current_object(), name)
14:26:14 web.1    |   File "/opt/redash/current/redash/models.py", line 295, in permissions
14:26:14 web.1    |     Group.select().where(Group.id << self.groups)]))
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2689, in __iter__
14:26:14 web.1    |     return iter(self.execute())
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2682, in execute
14:26:14 web.1    |     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
14:26:14 web.1    |   File "/opt/redash/current/redash/metrics/database.py", line 50, in metered_execute
14:26:14 web.1    |     result = real_execute(self, *args, **kwargs)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2370, in _execute
14:26:14 web.1    |     sql, params = self.sql()
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2656, in sql
14:26:14 web.1    |     return self.compiler().generate_select(self)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1650, in generate_select
14:26:14 web.1    |     return self.build_query(clauses, alias_map)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1542, in build_query
14:26:14 web.1    |     return self.parse_node(Clause(*clauses), alias_map)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1503, in parse_node
14:26:14 web.1    |     sql, params, unknown = self._parse(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1478, in _parse
14:26:14 web.1    |     sql, params = self._parse_map[node_type](node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1406, in _parse_clause
14:26:14 web.1    |     node.nodes, alias_map, conv, node.glue)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1520, in parse_node_list
14:26:14 web.1    |     node_sql, node_params = self.parse_node(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1503, in parse_node
14:26:14 web.1    |     sql, params, unknown = self._parse(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1478, in _parse
14:26:14 web.1    |     sql, params = self._parse_map[node_type](node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1387, in _parse_expression
14:26:14 web.1    |     rhs, rparams = self.parse_node(node.rhs, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1503, in parse_node
14:26:14 web.1    |     sql, params, unknown = self._parse(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1483, in _parse
14:26:14 web.1    |     sql, params = self.parse_node_list(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1520, in parse_node_list
14:26:14 web.1    |     node_sql, node_params = self.parse_node(node, alias_map, conv)
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1505, in parse_node
14:26:14 web.1    |     params = [conv.db_value(i) for i in params]
14:26:14 web.1    |   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 787, in db_value
14:26:14 web.1    |     return value if value is None else self.coerce(value)
14:26:14 web.1    | ValueError: invalid literal for int() with base 10: 'default'
14:26:14 web.1    | [2016-03-06 14:26:14,876][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:14] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
14:26:14 web.1    | [2016-03-06 14:26:14,884][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:14] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
14:26:14 web.1    | [2016-03-06 14:26:14,894][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:14] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
14:26:14 web.1    | [2016-03-06 14:26:14,916][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:14] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
14:26:15 web.1    | [2016-03-06 14:26:15,017][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:15] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
14:26:15 web.1    | [2016-03-06 14:26:15,144][PID:2083][INFO][werkzeug] 10.0.2.2 - - [06/Mar/2016 14:26:15] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
```

**Comment by arikfr** [comment]
From the error it seems that the migrations were not applied.

I recommend dropping the database and recreating it:
(from /opt/redash/currrent on the Vagrant box)
```bash
bin/run ./manage.py database drop_tables
bin/run ./manage.py database create_tables
bin/run ./manage.py users create --admin --password admin "Admin" "admin"
```

**Comment by arikfr** [comment]
(this assumes you don't have anything you want to save in the DB)

**Comment by toru-takahashi** [comment]
Thank you for your advice. It works!
(I don't have data in DB, thanks.)
